### DISCUSSION TITLE
How to disable the second HTTP listener on legacy endpoint 0.0.0.0:55681?

### DISCUSSION THREAD

**Discussion by rgl** [grafana/tempo#1181] [Q&A] [answered]
Is there a way to disable the second HTTP listener on legacy endpoint 0.0.0.0:55681?

At first I though this config would do the trick, but it does not:

```yaml
distributor:
  receivers:
    # see https://github.com/grafana/tempo/blob/v1.2.1/modules/distributor/config.go#L33
    # see https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
```

How do I disable the legacy endpoint 0.0.0.0:55681?
