### DISCUSSION TITLE
I set 'metricsGenerator' to 'true' but no metrics found in prometheus. Please help me.

### DISCUSSION THREAD

**Discussion by pingping95** [grafana/tempo#2157] [Q&A]
Hi.

Im using Grafana tempo , Loki so well.

Im trying to use Grafana tempo Service graph using metrics-generator

My environment : 
AWS EKS(Kubernetes) 1.24 Version
Tempo 1.5.0 version (With Helm chart)

And this is my helm-values.yaml

```
...

  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://kube-prometheus-stack-prometheus:9090/api/v1/write"

...

  overrides:
    {{- toYaml .Values.tempo.global_overrides | nindent 6 }}
    {{- if .Values.tempo.metricsGenerator.enabled }}
        metrics_generator_processors:
        - 'service-graphs'
        - 'span-metrics'
  metrics_generator:
        storage:
          path: "/tmp/tempo/generator/wal"
          remote_write:
            - url: {{ .Values.tempo.metricsGenerator.remoteWriteUrl }}
    {{- end }}

..

  overrides: {}

```

but I can`t find any metrics at prometheus. (https://grafana.com/docs/tempo/latest/metrics-generator/service_graphs/#metrics)

How do i troubleshoot ? If need more information, Please tell me.

**Comment by yvrhdn** [comment]
Hi, what does your configmap look in the end? Especially the `overrides` section. You have `overrides:` twice in your configuration, I'm not sure if the latter will overwrite the first.

**Comment by pingping95** [comment]
@kvrhdn

Hi! Thanks for answering.

This is my tempo configmap. overrieds and metrics_generator.

Is there anything i have to change ?

```
overrides:
      per_tenant_override_config: /conf/overrides.yaml
      metrics_generator_processors:
      - 'service-graphs'
      - 'span-metrics'
metrics_generator:
      storage:
        path: "/tmp/tempo/generator/wal"
        remote_write:
          - url: http://kube-prometheus-stack-prometheus:9090/api/v1/write


BinaryData
====

Events:  <none>
```

Ans this is my tempo Logs.

```
k logs tempo-0 -n monitoring -c tempo | grep -i generator

level=info ts=2023-03-01T10:37:21.395767655Z caller=module_service.go:82 msg=initialising module=metrics-generator-ring
level=info ts=2023-03-01T10:37:21.395886293Z caller=client.go:255 msg="value is nil" key=collectors/metrics-generator index=1
level=info ts=2023-03-01T10:37:21.397083978Z caller=module_service.go:82 msg=initialising module=metrics-generator
level=info ts=2023-03-01T10:37:21.397129229Z caller=basic_lifecycler.go:261 msg="instance not found in the ring" instance=tempo-0 ring=metrics-generator
level=info ts=2023-03-01T10:37:22.212520839Z caller=instance.go:46 tenant=single-tenant msg="creating WAL" dir=/tmp/tempo/generator/wal/single-tenant
level=info ts=2023-03-01T10:37:22.216884414Z caller=db.go:332 tenant=single-tenant component=wal msg="replaying WAL, this may take a while" dir=/tmp/tempo/generator/wal/single-tenant/wal
```

<img width="962" alt="image" src="https://user-images.githubusercontent.com/67780144/222255212-69c103f7-7662-4192-8591-9d53c0a0be09.png">

Thanks.
