### DISCUSSION TITLE
Shutdown takes 10s even without any activity

### DISCUSSION THREAD

**Discussion by snicoll** [grafana/tempo#3451] [Q&A]
I am evaluating Tempo using docker compose `version=main-23f9d00, branch=main, revision=23f9d002f`.

I have postgres, grafana, tempo, and prometheus defined with what looks like vanilla configuration for Tempo:

```yaml
server:
  http_listen_port: 3200
distributor:
  receivers:
    zipkin:
storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://host.docker.internal:9090/api/v1/write
        send_exemplars: true
overrides:
  metrics_generator_processors: [ service-graphs, span-metrics ]
```

What I notice is that `docker compose down` is taking around 10s consistently, because Tempo takes that amount of time to shutdown. The three other services take around 0.1s to stop.

I've tried to look at the ingester configuration and played with it a little bit but that 10sec shutdown "delay" still applies. Does anybody know where that could come from? Thanks!
