### DISCUSSION TITLE
Memcached timeout related question

### DISCUSSION THREAD

**Discussion by edgarkz** [grafana/tempo#3553] [Q&A]
Hi,
1.Can you please assist with tempo queries logging the following timeouts from memcached? 
Looking into memcached metrics I don't see anything hitting max connections or so.

2.should we scale up more instances of memcached? the chart supports it but will be any benefit from multiple instances?
single memcached instance deployed from distributed tempo helm chart

eks 1.26
tempo 2.4.1 distributed  via helm chart

`level=error ts=2024-03-28T21:20:22.175685654Z caller=memcached.go:153 msg="Failed to get keys from memcached" err="memcache: connect timeout to 10.100.213.119:11211"
level=error ts=2024-03-28T21:20:22.175931644Z caller=memcached.go:153 msg="Failed to get keys from memcached" err="memcache: connect timeout to 10.100.213.119:11211"
level=error ts=2024-03-28T21:20:22.434598693Z caller=memcached.go:236 msg="failed to put to memcached" name=parquet-footer|bloom|frontend-search err="server=10.100.213.119:11211: memcache: connect timeout to 10.100.213.119:11211"
level=error ts=2024-03-28T21:20:23.133903161Z caller=memcached.go:236 msg="failed to put to memcached" name=parquet-footer|bloom|frontend-search err="server=10.100.213.119:11211: memcache: connect timeout to 10.100.213.119:11211"
level=error ts=2024-03-28T21:20:24.174768798Z caller=memcached.go:236 msg="failed to put to memcached" name=parquet-footer|bloom|frontend-search err="server=10.100.213.119:11211: memcache: connect timeout to 10.100.213.119:11211"
level=error ts=2024-03-28T21:20:24.175104043Z caller=memcached.go:236 msg="failed to put to memcached" name=parquet-footer|bloom|frontend-search err="server=10.100.213.119:11211: memcache: connect timeout to 10.100.213.119:11211"
level=error ts=2024-03-28T21:20:24.195413573Z caller=memcached.go:236 msg="failed to put to memcached" name=parquet-footer|bloom|frontend-search err="server=10.100.213.119:11211: memcache: connect timeout to 10.100.213.119:11211"
level=error ts=2024-03-28T21:20:24.195483153Z caller=memcached.go:236 msg="failed to put to memcached" name=parquet-footer|bloom|frontend-search err="server=10.100.213.119:11211: memcache: connect timeout to 10.100.213.119:11211"
level=error ts=2024-03-28T21:20:24.195515305Z caller=memcached.go:236 msg="failed to put to memcached" name=parquet-footer|bloom|frontend-search err="server=10.100.213.119:11211: memcache: connect timeout to 10.100.213.119:1121`

**Comment by joe-elliott** [comment]
We see similar logs when a memcached cluster becomes overwhelmed and generally respond by scaling up the cluster. Sizing and operating memcached on large clusters is still something we're working out so I'd love to compare notes.

One thing that can help is separating your cache configs. I notice that your logs indicate that you're using one cache cluster and all roles are configured together (`parquet-footer|bloom|frontend-search`). If you keep one cluster but simply break the config apart then Tempo will metric and log them independently which may help us determine if this is related to one of the roles.

```
cache:
    caches:
        - memcached:
            host: <some cluster>
          roles:
            - bloom
            - parquet-footer
            - ...
```
becomes
```
cache:
    caches:
        - memcached:
            host: <some cluster>
          roles:
            - bloom
        - memcached:
            host: <some cluster>
          roles:
            - parquet-footer
        - ...
```

I'll also point out that we set `max_idle_conns` to 100 on all clusters. Honestly not sure how tuned that is. Like I said, we are exploring this space right now.

We also set connections on our memcached servers: `-c 4096` and monitor them by watching the `memcached_current_connections` metric.

@electron0zero has a bit more experience here and my have insights.
