### DISCUSSION TITLE
Finding approximation of "compression ratio" for parquet storage

### DISCUSSION THREAD

**Discussion by ovidiubuligan** [grafana/tempo#3774] [General]
One way I tried to find out was to divide  the total received network trafic by the `distributor` (since it is all OTLP)   , by the size of the storage bucket size  .Something doesn't look right since the total storage for `10` days is larger than the distributor received network trafic in `10` days  .
```promql
sum(
   increase(container_network_receive_bytes_total{namespace="tempo" , pod=~"grafana-tempo-distributor.*" }[10d]
)/1024/1024/1024) #Gb
```
OTLP  Network traffic received in 10 days is `430Gb` while total storage in the bucket is `~1.5 terabytes`  for 10 days retention (includes meta.json and index.json but they are small)

Interestingly trying to load a parquet(v2) file of `300Mb` from a sample block in python pandas gives out of memory error .
```python
# Read the Parquet file into a DataFrame
df = pd.read_parquet(parquet_file_path)   # <-- out of memory
```   

I would expect the total size of the bucket to be less than the raw OTLP spans received  for the same time frame  . Does someone know why this is not the case  ?

**Comment by joe-elliott** [comment]
A few things tha may shed some light on this.

First, I believe `container_network_receive_bytes_total` is compressed proto. Can you also try review `tempo_distributor_bytes_received_total`. That is size in uncompressed proto and will give us more information about what may be going on.

Second, are you running in distributed mode with RF3? In this case Tempo is writing ~3x the data to object storage. We atttempt to dedupe this data using the compactors but have recently discovered that deduplication is not as effective as previously thought. cc @mapno. Also know we are currently investigating an RF1 architecture to reduce Tempo TCO and improve performance.

I have not used personally python pandas to load our parquet files so I can't say what the issue may be. I use this tool when I want to investigate a file:

https://github.com/stoewer/parquet-cli

It has a number of options and is easy to debug and modify for custom investigations of a file.

**Reply by ovidiubuligan** [reply]
1. Using `tempo_distributor_bytes_received_total` is `7 `times larger  than `container_network_receive_bytes_total` . **I guess this is good?** 

2. We are running the distributed version (helm chart)  with mostly default settings which looks to have  `RF3`  . We only run a single compactor instance since it looks to be enough. 
```yaml
compactor:
  compaction:
    block_retention: 240h
    compacted_block_retention: 1h
    compaction_cycle: 30s
    compaction_window: 15m
    max_block_bytes: 107374182400
    max_compaction_objects: 6000000
    max_time_per_tenant: 5m
    retention_concurrency: 10
    v2_in_buffer_bytes: 5242880
    v2_out_buffer_bytes: 20971520
    v2_prefetch_traces_count: 1000
  ring:
    kvstore:
      store: memberlist
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  ring:
    kvstore:
      store: memberlist
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
    tokens_file_path: /var/tempo/tokens.json
  max_block_bytes: 524288000
```

3. I also get some quite high stats on the k8s attributes with low cardinality using the `tempo cli ` (for about 100 blocks): 
```
Top 15 span attributes by size
name: db.statement           size: 350 MB   (23.76%)
name: graphql.json_request   size: 222 MB   (15.07%)
name: aaaaaaaaaaaaaaa        size: 143 MB   (9.68%)
name: graphql.query          size: 121 MB   (8.23%)
name: peer.service           size: 92 MB    (6.28%)
name: CCCCCCCCCCC            size: 92 MB    (6.27%)
name: bbbbbbbbb              size: 68 MB    (4.61%)
name: http.host              size: 44 MB    (2.95%)
name: net.peer.name          size: 31 MB    (2.08%)
name: http.user_agent        size: 26 MB    (1.79%)
name: db.name                size: 26 MB    (1.77%)
name: user_agent.original    size: 26 MB    (1.76%)
name: peer.address           size: 22 MB    (1.53%)
name: http.route             size: 20 MB    (1.37%)
name: upstream.address       size: 17 MB    (1.14%)
Top 8 resource attributes by size
name: service.instance.id   size: 725 MB   (27.47%)     # <--  !!!  we have a max of ~400 pods and  and a churn rate of 1,2 pods per hour
name: k8s.pod.uid           size: 592 MB   (22.42%)       # <--  
name: k8s.pod.start_time    size: 477 MB   (18.06%)
name: k8s.deployment.name   size: 421 MB   (15.94%)      # we only only have ~30 deployments 
name: k8s.node.name         size: 250 MB   (9.48%)
name: k8s.pod.ip            size: 172 MB   (6.50%)
name: service.version       size: 3.2 MB   (0.12%)
name: <null>                size: 0 B      (0.00%)
```
Kind of wierd that  `k8s.pod.uid` takes up that much , or even `k8s.deployment.name` with `421 MB` which we have only ~30 that are constant strings.  Can I index these resource columns somehow ?


4. Thoughts on Apache Arrow and it's querying engines ?  I saw there are some efforts with OTEL Arrow to make OTLP even more compressed [dynamic arrow schema blog](https://arrow.apache.org/blog/2023/06/26/our-journey-at-f5-with-apache-arrow-part-2/))  . Also arrow format creator critiques parquet for it's complexity and even suggest to use some form of arrow as storage [Wes McKinney (creator of pandas)](https://www.youtube.com/watch?v=YhF8YR0OEFk)
