### DISCUSSION TITLE
Getting Duplicate Spans

### DISCUSSION THREAD

**Discussion by natenberenstein** [grafana/tempo#3919] [Q&A] [answered]
# Components/Environment
- otel-collector (helm chart | app v0.104.0)
- tempo (helm chart | app v2.5.0)
- k3s cluster (v1.30.2+k3s1)

# Problem
Getting duplicate spans in Tempo (see figures below).
![image](https://github.com/user-attachments/assets/378b0362-f487-4b2d-90fb-8fb84ad95b08)

![image](https://github.com/user-attachments/assets/ed49e1cf-d6f6-4bb3-a5f7-f775755020bf)

# Architecture/Code
I'm using the otel-collector and tempo helm charts, both of which are deployed to my k3s cluster.  Traces from applications are pushed to an OpenTelemetry Collector, and then pushed to the Tempo backend so they can be viewed in Grafana.  Here is the values file for the opentelemetry collector and tempo component.

**opentelemetry-collector-deployment.yaml**
```yaml
mode: deployment

image:
  repository: otel/opentelemetry-collector-k8s

# We only want one of these collectors - any more and we'd produce duplicate data
replicaCount: 1

presets:
  # enables the k8sclusterreceiver and adds it to the metrics pipelines
  clusterMetrics:
    enabled: false
  # enables the k8sobjectsreceiver to collect events only and adds it to the logs pipelines
  kubernetesEvents:
    enabled: false
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true
    extractAllPodAnnotations: true
podMonitor:
  enabled: true
serviceMonitor:
  enabled: true
ports:
  metrics:
    enabled: true
config:
  processors:
    k8sattributes:
      pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
  exporters:
    otlp:
      endpoint: tempo-distributor.tempo.svc.cluster.local:4317
      tls:
        insecure: true
    otlphttp:
      endpoint: http://tempo-distributor.tempo.svc.cluster.local:4318
      tls:
        insecure: true
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317
    zipkin:
      endpoint: 0.0.0.0:9411
  service:
    telemetry:
      logs:
        level: DEBUG
        development: true
        encoding: json
    pipelines:
      metrics: null
      logs: null
      traces:
        processors: [ k8sattributes, batch ]
        receivers: [ otlp, zipkin ]
        exporters: [ otlp, otlphttp ]
```

**tempo-values.yaml**
```yaml
global:
  clusterDomain: 'cluster.local'
global_overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
reportingEnabled: false
gateway:
  enabled: true
storage:
  trace:
    backend: s3
    s3: ...
    wal:
      path: /var/tempo/wal
traces:
  zipkin:
    enabled: true
    receiverConfig:
      endpoint: 0.0.0.0:9411
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
distributor:
  config:
    log_received_spans:
      enabled: true
      include_all_attributes: true
metaMonitoring:
  serviceMonitor:
    enabled: true
```

# Discussion
I'm not sure what could be causing the spans to be duplicated in Tempo.  Maybe this tells me something about my application, or maybe Tempo/Otel-collector is appending the duplicate spans.   What do you think could be causing this duplication?

**Comment by joe-elliott** [comment]
This is a new one on me. I would recommend using the distributor's debugging capabilities to log what spans are received. Then we can determine if this issue is occurring in Tempo or not.

Distributor config:

https://grafana.com/docs/tempo/latest/configuration/#distributor

the block you are interested in is:

```
distributor:
    log_received_spans:
        [enabled: <boolean> | default = false]
        [include_all_attributes: <boolean> | default = false]
        [filter_by_status_error: <boolean> | default = false]
```

This should not be left on in production envs, but is a good debugging tool in test setups.

**Reply by natenberenstein** [reply, marked as answer]
Thanks for the response @joe-elliott!  I looked into the distributor logs and did find some duplicates.  The logs didn't provide much info, but it did lead me to the root problem.  The reason for why there were duplicate spans was due to my opentelemetry collector configuration, where I added two exporters to the trace pipeline. In my opentelemetry files value, I specified two exporters: `otlp` and `otlphttp`.  It seems like providing both to the traces pipeline within the `exporters` array would cause the spans to be duplicated.

```yaml
conifg:
  ...
  pipelines:
      metrics: null
      logs: null
      traces:
        ...
        exporters: [ otlp, otlphttp ]
```
To resolve this, I just removed one of the exporters and ended up receiving unique spans instead of duplicates.
