### DISCUSSION TITLE
Distributor queue full errors

### DISCUSSION THREAD

**Discussion by brajeshpalod** [grafana/tempo#4515] [General]
Hey Team, 

We are running a microservice mode deployment for tempo and are getting a lot of errors for queue full for the distributor `tempo_distributor_queue_pushes_failures_total` and gone through the below discussion https://github.com/grafana/tempo/discussions/3053. I have tried to override the distributor queue size with [metrics_generator_forwarder_queue_size](https://grafana.com/docs/tempo/latest/configuration/#overrides). However, Increasing the queue size parameters has not increased the queue in distributors.  I have checked via metrics `tempo_distributor_queue_length` which is still getting on 100 as max for queue even when I have configured for 500 in metrics_generator_forwarder_queue_size as override.

Could you please suggest me how to override the distributor push queue from default value?

**Comment by joe-elliott** [comment]
Can you share your config? Overrides can be tricky. I have to review the code sometimes to know how they are applied.

**Comment by brajeshpalod** [comment]
Override file looks like below:
```
apiVersion: v1
data:
  overrides.yaml: |
    overrides:
        defaults:
            metrics_generator_forwarder_queue_size: 200
            metrics_generator_forwarder_workers: 4
        super_user:
            ingestion_burst_size_bytes: 2e+07
            ingestion_rate_limit_bytes: 2e+07
            max_bytes_per_trace: 3e+07
            max_traces_per_user: 100000
kind: ConfigMap
metadata:
  name: tempo-overrides

```

I have metrics generator stateful set with override conf mounted as /overrides and tempo config have overrides path of override conf.
deployment conf
```
      containers:
      - args:
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=512
        - -target=metrics-generator
        - -config.expand-env=true
        volumeMounts:
        - mountPath: /overrides
          name: overrides
      volumes:
      - configMap:
          name: tempo-overrides
        name: overrides
```
tempo conf
```
    metrics_generator:
        metrics_ingestion_time_range_slack: 60s
        processor:
            service_graphs:
                dimensions:
                    - env
                    - product_id
                max_items: 65000
                wait: 15s
            span_metrics:
                dimensions:
                    - env
                    - product_id
                    - http.status_code
                    - http.method
                    - http.request.method
                    - http.response.status_code
     overrides:
        max_bytes_per_trace: 4e+07
        max_traces_per_user: 0
        metrics_generator_processors:
            - service-graphs
            - span-metrics
        per_tenant_override_config: /overrides/overrides.yaml   

```

**Comment by joe-elliott** [comment]
Your problem may be here:

```
apiVersion: v1
data:
  overrides.yaml: |
    overrides:
        defaults:
            metrics_generator_forwarder_queue_size: 200
            metrics_generator_forwarder_workers: 4
        super_user:
            ingestion_burst_size_bytes: 2e+07
            ingestion_rate_limit_bytes: 2e+07
            max_bytes_per_trace: 3e+07
            max_traces_per_user: 100000
kind: ConfigMap
metadata:
  name: tempo-overrides
```

When Tempo matches an overrides block it takes all values from that block. So if it's matching a tenant against "super_user" that includes an implied setting `metrics_generator_forwarder_queue_size: 0` which is being overriden by the default of 100. Perhaps try something like:

```
apiVersion: v1
data:
  overrides.yaml: |
    overrides:
        defaults:
            metrics_generator_forwarder_queue_size: 200
            metrics_generator_forwarder_workers: 4
        super_user:
            ingestion_burst_size_bytes: 2e+07
            ingestion_rate_limit_bytes: 2e+07
            max_bytes_per_trace: 3e+07
            max_traces_per_user: 100000
            metrics_generator_forwarder_queue_size: 200
            metrics_generator_forwarder_workers: 4
kind: ConfigMap
metadata:
  name: tempo-overrides
```

**Comment by brajeshpalod** [comment]
@joe-elliott  I have applied the new config as below:
```
apiVersion: v1
data:
  overrides.yaml: |
    overrides:
        defaults:
            metrics_generator_forwarder_queue_size: 200
            metrics_generator_forwarder_workers: 4
        super_user:
            ingestion_burst_size_bytes: 2e+07
            ingestion_rate_limit_bytes: 2e+07
            max_bytes_per_trace: 3e+07
            max_traces_per_user: 100000
            metrics_generator_forwarder_queue_size: 200
            metrics_generator_forwarder_workers: 4
kind: ConfigMap
metadata:
  name: tempo-overrides
```
However, I don't see the increase in queue length for the distributor. 
![image](https://github.com/user-attachments/assets/2a7b5cda-fdba-49f5-a672-e95bc0668671)

Also, my tenant is in metrics - tenant="single-tenant"

**Comment by brajeshpalod** [comment]
@joe-elliott Please find the override config single-tenant `http://localhost:3200/status/overrides/single-tenant`
```
User-configurable overrides
User-configurable overrides are not enabled
Runtime overrides
Source of runtime overrides: default overrides

ingestion:
  rate_strategy: local
  rate_limit_bytes: 15000000
  burst_size_bytes: 20000000
read:
  max_bytes_per_tag_values_query: 5000000
metrics_generator:
  processors:
  - service-graphs
  - span-metrics
  ingestion_time_range_slack: 0s
global:
  max_bytes_per_trace: 40000000
```

Overides for defaults - `http://localhost:3200/status/overrides/defaults` which supposed to be global but considered as tenant.

```
User-configurable overrides
User-configurable overrides are not enabled
Runtime overrides
Source of runtime overrides: defaults

metrics_generator:
  forwarder:
    queue_size: 200
    workers: 4
  ingestion_time_range_slack: 0s
```
My understanding is that what all configuration overrides in defaults will be global and will be passed to all tenants.  but it looks like it considering defaults as tenant name `defaults` and apply these settings to defaults as tenant not as global. 
document which I am referring - https://grafana.com/docs/tempo/latest/configuration/#standard-overrides

**Comment by brajeshpalod** [comment]
@joe-elliott I have got it working but not sure that is correct approach. 
```
apiVersion: v1
data:
  overrides.yaml: |
    overrides:
        defaults:
            metrics_generator_forwarder_queue_size: 200
            metrics_generator_forwarder_workers: 4
        super_user:
            ingestion_burst_size_bytes: 2e+07
            ingestion_rate_limit_bytes: 2e+07
            max_bytes_per_trace: 3e+07
            max_traces_per_user: 100000
            metrics_generator_forwarder_queue_size: 200
            metrics_generator_forwarder_workers: 4
        single-tenant:
            ingestion_burst_size_bytes: 2e+07
            ingestion_rate_limit_bytes: 2e+07
            max_bytes_per_trace: 3e+07
            max_traces_per_user: 100000
            metrics_generator_forwarder_queue_size: 200
            metrics_generator_forwarder_workers: 4
kind: ConfigMap
metadata:
  name: tempo-overrides
```

**Comment by joe-elliott** [comment]
ok, I see. Yes, your config is setup so that a tenant named "default" gets these settings:

```
    overrides:
        defaults:
            metrics_generator_forwarder_queue_size: 200
            metrics_generator_forwarder_workers: 4
        ...
```

This file definition is here https://grafana.com/docs/tempo/latest/configuration/#runtime-overrides

That "defaults" block goes in your primary config. To take your config above something like:

```
    metrics_generator:
        metrics_ingestion_time_range_slack: 60s
        processor:
            service_graphs:
                dimensions:
                    - env
                    - product_id
                max_items: 65000
                wait: 15s
            span_metrics:
                dimensions:
                    - env
                    - product_id
                    - http.status_code
                    - http.method
                    - http.request.method
                    - http.response.status_code
     overrides:
        per_tenant_override_config: /overrides/overrides.yaml   
        defaults:
          <config options here>
```
