### DISCUSSION TITLE
Issues of automatically scaling Distributor and Ingesters

### DISCUSSION THREAD

**Discussion by chazapp** [grafana/tempo#4717] [General]
Hello world,
We are using Tempo with the `tempo-distributed` Helm Chart in clusters where our traffic varies throughout the day, with up to 60Mb/s of received spans during peaks, but low received spans (<5Mb/s) at night.   

I'm looking for up-to-date information about the issue of automatically scaling distributors and ingesters in Tempo microservices.  We currently have a fixed number of oversized ingesters running 24/7, and have to bump them up from time to time as our systems grow and more and more services rely on distributed tracing. I'd like to configure our Tempo instance in such a way that it uses what it needs and scales up and down based on the actual workload and throughput of spans.  

I have found multiple places that say that autoscaling of ingester is a bad idea, but the threads are old and do not go in the details about the _why_. Why is autoscaling of Ingesters a bad idea ? Is it still ? 

---

References:

[Helm Chart values ingester autoscaling parameter](https://github.com/grafana/helm-charts/blob/5bae43a05122dca0dcc20e7d268658092530e5ba/charts/tempo-distributed/values.yaml#L131C21-L133C146): 
> "WARNING: Autoscaling ingesters can result in lost data. Only do this if you know what you're doing."

[08/08/2022 #1275](https://github.com/grafana/tempo/issues/1275#issuecomment-1208520681)
> Yes, autoscaling on the ingesters is a bad idea :).

---

My plan was to:
 <details><summary>1. Enable Ingester flush_all_on_shutdown</summary>

```yaml
# values.yaml
ingester:
  config:
    flush_all_on_shutdown: true
```
</details>

 <details><summary>2. Rewrite ingestion limits as global parameters</summary>

```yaml
#values.yaml
global_overrides:
  defaults:
     ingestion:
       rate_strategy: global
       burst_size_bytes: 200000000 # 200Mb/s burst ingestion max
       rate_limit_bytes: 100000000 # 100Mb/s ratelimit

       max_traces_per_user: 0 # Disable per ingester limit
       max_global_traces_per_user: 500000 # 500k concurrent live traces
```

</details>

<details><summary>3. Write a KEDA Autoscaler for Distributor</summary>

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tempo-distributor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tempo-distributor
  minReplicaCount: 2 # minimum HA
  maxReplicaCount: 20 # Maximum within rate_limit_bytes at 10mb/s /distrbutor
  fallback:
    failureThreshold: 3
    replicas: 5
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring:9090/
        query: |
          sum(rate(tempo_distributor_bytes_received_total[5m]))
        threshold: 10000000 # 1 replica / 10MB/s traffic
```
</details>

<details><summary>4. Write a KEDA Autoscaler for Ingester</summary>

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tempo-ingester
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: tempo-ingester
  minReplicaCount: 2 # minimum HA
  maxReplicaCount: 40 # Maximum within rate_limit_bytes at 5mb/s /ingester
  fallback:
    failureThreshold: 3
    replicas: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring:9090/
        query: |
          sum(rate(tempo_distributor_bytes_received_total[5m]))
        threshold: 5000000 # 1 replica / 5MB/s traffic
```
</details>

Are there any issues with this plan ?

Thank you !
