### DISCUSSION TITLE
Enlarge local_blocks.max_block_duration trigger many of "dropped sample for series" log output

### DISCUSSION THREAD

**Discussion by bangau1** [grafana/tempo#4801] [Q&A]
Hi all,

Using tempo 2.7.1 with following configuration, I get this many logs:
```
ts=2025-03-07T08:02:11.04428161Z caller=dedupe.go:112 tenant=single-tenant component=remote level=info remote_name=prometheus url=http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write msg="Dropped sample for series that was not explicitly dropped via relabelling" ref=85210
```

The config:
```
metricsGenerator:
  processor:
    local_blocks:
      trace_idle_period: 1m
      flush_to_storage: true
      flush_check_period: 1m
      max_block_duration: 30m # default it's 1m, but enlarge this since 1m of data.parquet block size is only 300KB
```
So the only thing that I changed is to enable flush_to_storage and increase the `max_block_duration`. I tried experimenting it with smaller block duration to like 10m, the error is gone. Any idea what error is it (and the root cause is) and how to workaround this?
