### DISCUSSION TITLE
Need help understanding on what the local_block flush and delete block actually does

### DISCUSSION THREAD

**Discussion by bangau1** [grafana/tempo#4843] [Q&A]
Hi all,

So I have running the metricsGenerator with local_block processor. This is the config I have:
```
      local_blocks:
        trace_idle_period: 1m
        flush_to_storage: true # set to true 
        flush_check_period: 1m
        max_block_duration: 30m # by default it's using 1m (our case, it generates 300KB parquet block). So increasing to 30m to make it around 8-10 MB size.

        # Duration to keep blocks in the ingester after they have been flushed. Default 1h. Increase to 2h to minimize data lose in case we're doing maintenance window
        complete_block_timeout: 2h

        # Whether server spans should be filtered in or not.
        # If enabled, only parent spans or spans with the SpanKind of `server` will be retained
        filter_server_spans: false 
```

In particular, I enable `flush_to_storage` to `true`. I have impression that it will store the historical local block data into GCS bucket (where other trace block are stored by the ingester, cmiiw).

Looking at the metrics-generator pod's log below, there's some delay between it's being flushed and got deleted.
```
level=info ts=2025-03-13T03:38:00.506770095Z caller=processor.go:413 org_id=single-tenant msg="flushed block to storage" block=a5f60910-1ad3-4ac1-b335-872a5904d792
level=info ts=2025-03-13T05:37:44.234692633Z caller=processor.go:584 org_id=single-tenant msg="deleting flushed complete block" block=a5f60910-1ad3-4ac1-b335-872a5904d792
```

So before it got deleted, I can access it on my gcs bucket: 
```
$ gsutil ls gs://<bucket>/single-tenant/a5f60910-1ad3-4ac1-b335-872a5904d792/
bloom-0
data.parquet
index
meta.json
```

but then, after the `"deleting flushed complete block"` log appeared, I can't access it on the gcs bucket anymore. So I wonder how the local_block access it's historical data ?
