### DISCUSSION TITLE
Query tempo traces in grafana only last 30 minutes?

### DISCUSSION THREAD

**Discussion by gpcmol** [grafana/tempo#4971] [Q&A]
In grafana v11.5.2, I'm trying to explore my traces from before 30 minutes from now.
They only show up from the last 30 minutes.

I see that there is a configuration in tempo which defaults om 30m (which i left like this.:
```
[query_backend_after: <duration> | default = 30m ]
```
I expect that the backend is then quried?

this is my tempo compactor configuration:
```
    compactor:
      compaction:
        block_retention: 48h
        compacted_block_retention: 1h
        compaction_cycle: 30s
        compaction_window: 1h
        max_block_bytes: 107374182400
        max_compaction_objects: 6000000
        max_time_per_tenant: 5m
        retention_concurrency: 10
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 1000
```

I've seen these issues:
https://github.com/grafana/tempo/issues/2650 and https://github.com/grafana/tempo/issues/4877
I'm not sure if this is related?

My question is. Which configuration do i need to request traces before 30 minutes from now?
