### DISCUSSION TITLE
Tempo Metrics-Generator OOMKills

### DISCUSSION THREAD

**Discussion by IMandrikov** [grafana/tempo#5296] [Q&A]
Hi,

I’m having issues with deploying the metrics-generator in my cluster, where the throughput reaches 1.4 million spans/sec (see attached picture). The metrics-generator has been deployed on the largest available node with 256 GB of memory, but it still gets OOMKilled (also shown in the picture).

According to my calculations, it should require around 400 GB of memory, but that’s not possible in our cluster setup.

Are there any parameters I could tune to reduce memory usage? I’ve already tried running it in distributed mode, but that didn’t help.

I’ve attached the ConfigMap for reference.

Thanks in advance!

tempo-configmap:
[tempo-cm-live.txt](https://github.com/user-attachments/files/20771495/tempo-cm-live.txt)
metrics-generator memory usage (y-axis in Megabytes):
<img width="1222" alt="image" src="https://github.com/user-attachments/assets/58f5ccf1-dd55-46f4-8e04-d7adf9e934b2" />
Throughput (last 24h)
<img width="1419" alt="image" src="https://github.com/user-attachments/assets/b6b0a5e8-4613-430b-ab7f-a65c1b918215" />

**Comment by joe-elliott** [comment]
Do you only have one metrics generator? I would definitely recommend scaling out. Especially with 1M+ spans/second.

Metrics generators do _a lot_ and are susceptible to inflated memory especially if you are running local blocks and flushing them (which you are). Know that this will massively improve in the Tempo 3.0 rearchitecture.

Metrics generators are particularly susceptible to long running traces. We recently diagnosed this issue in our own cells and merged this PR to help: https://github.com/grafana/tempo/pull/5346. It maybe worth trying this commit in your own Tempo cluster to see if it helps.

Consider tuning flush_check_period and trace_idle_period. See if these settings help. They will more aggressively flush trace data from memory to disk:

```
metrics_generator:
    processor:
        local_blocks:
            flush_check_period: 5s
            trace_idle_period: 5s
```

**Reply by IMandrikov** [reply]
Hi @joe-elliott 
I applied the settings you mentioned. From the /status endpoint:
```
overrides:
  main:
    ingestion:
      rate_limit_bytes: 52500000
      burst_size_bytes: 20000000
      max_traces_per_user: 300000
    metrics_generator:
      generate_native_histograms: ""
      processor:
        local_blocks:
          flush_check_period: 5s
          trace_idle_period: 5s
```

I deployed 3 metrics-generators on 3 256Gi nodes, the picture looks better:
![image](https://github.com/user-attachments/assets/ea44531b-b7b1-4a28-a54f-13db20b109ae)
at least they are up for around 7min until get OOMKilled.

Should i scale out even more?
Might be very pricy, currently we use Loki to create metrics form span logs. 
Not sure if traceql metrics might help to replace it in this case...
