### ISSUE TITLE
Tempo distributed example gives "Query error Metric request" error in Grafana

### ISSUE THREAD

**Issue by hkailantzis** [grafana/tempo#1171]
**Describe the bug**

**To Reproduce**

Used the following the example to deploy on minikube:
https://github.com/grafana/tempo/blob/main/example/helm/microservices-extras.yaml

changed only this in my case: 
```
- name: JAEGER_COLLECTOR_URL
  value: http://tempo-distributed-distributor:14268
```

deploy Helm chart of Tempo in distributed mode: config:

```
traces:
  jaeger:
    grpc: true
    thriftHttp: true
    thrift_binary: true
    thrift_compact: true
  zipkin: true
  otlp:
    http: true
    grpc: true
  opencensus: true
```

deploy prometheus operator stack with Grafana enabled.
deploy Loki in distributed mode

set derived field in Loki data source: 
Query: ${__value.raw}  with internal link enabled and set to Tempo datasource.
TraceID ->regex: traceId (\w+)

getting "Query error Metric request error" in Grafana.

Issue was also described here: https://github.com/grafana/tempo/issues/1024

but no matter what I tried I keep getting the same error in Grafana.  "**Query error Metric request error**". Any hints/tips would be great. Thank you!

**Expected behavior**

**Environment:**
 minikube

**Additional Context**

![Screen Shot 2021-12-11 at 10 07 58 AM](https://user-images.githubusercontent.com/2778156/145671110-3d34793e-241b-47c2-a6c6-c45916ca8b51.png)
