### ISSUE TITLE
Not Found Body: trace not found

### ISSUE THREAD

**Issue by XiaoWeiKIN** [grafana/tempo#1179]
Trace cannot be queried after a period of time, but it was available before. Will S3 archive the data?
before:
![image](https://user-images.githubusercontent.com/20626345/146318324-f939a521-4e3e-4994-9c00-2bbbf373acde.png)
after:
![image](https://user-images.githubusercontent.com/20626345/146318435-0b444690-df59-49fe-802c-b28f90edd63d.png)

**Comment by joe-elliott** [comment]
Overall retention is controlled by the `block_retention` option:

https://grafana.com/docs/tempo/latest/configuration/#compactor

Traces being visible or not is also dependent on polling options in your querier, query-frontend and other components. If you share your config it might help diagnose your issue.

**Comment by XiaoWeiKIN** [comment]
Thanks for your reply, I am deploying using the example in `example/tempo-s3.yaml` and I see that the `block_retention`option has a value of `1h`。

```
compactor:
  compaction:
    compaction_window: 1h              # blocks in this time window will be compacted together
    max_block_bytes: 100_000_000        # maximum size of compacted blocks
    block_retention: 1h
    compacted_block_retention: 10m
    flush_size_bytes: 5242880
```
