### ISSUE TITLE
Unable to setup TLS for receivers: 'protocols.grpc' has invalid keys: tls

### ISSUE THREAD

**Issue by Poweranimal** [grafana/tempo#1193]
**Describe the bug**
Hi,
I'm not able to setup tls for the `distributor/receivers/otlp/protocols/grpc`.
Trying to setup tls causes the following error:
```
error running Tempo" err="failed to init module services error initialising module: distributor: failed to create distributor error reading receivers configuration for otlp: 1 error(s) decoding:\n\n* 'protocols.grpc' has invalid keys: tls
```

**To Reproduce**
1. Start Tempo (1.2.1)
2. Use provided config (see below)

**Expected behavior**
Expecting to setup tls for tempo's receivers.

**Environment:**
`tempo.yaml`:
```yaml
auth_enabled: false
search_enabled: false
compactor:
  compaction:
    compacted_block_retention: 24h
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
          tls:
            cert_file: /etc/tempo/tls/otel/tls.crt
            key_file: /etc/tempo/tls/otel/tls.key
ingester:
  {}
server:
  http_listen_port: 3100
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
```
