### ISSUE TITLE
Make `compactionCycle` configurable

### ISSUE THREAD

**Issue by annanay25** [grafana/tempo#1232]
**Is your feature request related to a problem? Please describe.**

As of now, the `compactionCycle` defaults to 500ms. https://github.com/grafana/tempo/blob/2674b233d8663852f2ccc65cc47edfee36caba23/tempodb/compactor.go#L60

This gets tough to work with on local development setups where logs are spammed with compactor cycle logs
```
tempo_1                     | level=info ts=2022-01-19T10:37:14.0120974Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
tempo_1                     | level=info ts=2022-01-19T10:37:14.0122882Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
tempo_1                     | level=info ts=2022-01-19T10:37:14.5105278Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
tempo_1                     | level=info ts=2022-01-19T10:37:14.5108502Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
tempo_1                     | level=info ts=2022-01-19T10:37:15.0127511Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
tempo_1                     | level=info ts=2022-01-19T10:37:15.0129207Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
tempo_1                     | level=info ts=2022-01-19T10:37:15.510125Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
tempo_1                     | level=info ts=2022-01-19T10:37:15.5102975Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant

```

**Describe the solution you'd like**

Make the compactionCycle configurable (but continue to default to 500ms) so we can configure that on local dev setups.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by joe-elliott** [comment]
Isn't this controlled by:
https://github.com/grafana/tempo/blob/main/modules/storage/config.go#L33

**Comment by annanay25** [comment]
Is it? I can't find any references to that.

I think we decoupled blocklist poll from compaction cycle at some point. It looks like `compactionCycle = 500 * time.Millisecond` is used directly here:
https://github.com/grafana/tempo/blob/2674b233d8663852f2ccc65cc47edfee36caba23/tempodb/compactor.go#L69

**Comment by joe-elliott** [comment]
Yup, you're right. I was mixing this up with polling. We made this change to make Tempo compaction more performant in multi-tenant scenarios.

**Comment by irizzant** [comment]
Hello
I have Tempo configured as single-binary as shown below:
```yaml
tempo.yaml:
----
compactor:
    compaction:
        compacted_block_retention: 24h
distributor:
    receivers:
        jaeger:
            protocols:
                grpc: null
                thrift_http: null
        otlp:
            protocols:
                grpc:
                    max_recv_msg_size_mib: 134
                http: null
ingester: {}
overrides:
    per_tenant_override_config: /conf/overrides.yaml
search_enabled: true
server:
    grpc_server_max_recv_msg_size: 1.34217728e+08
    grpc_server_max_send_msg_size: 1.34217728e+08
    http_listen_port: 3200
storage:
    trace:
        backend: s3
        local:
            path: /tmp/tempo/traces
        s3:
            access_key: ${S3_ACCESS_KEY}
            bucket: tempo
            endpoint: minio.minio.svc.cluster.local:9000
            insecure: true
            secret_key: ${S3_SECRET_KEY}
        wal:
            path: /var/tempo/wal
```

My log is flooded with:
```
level=info ts=2022-01-27T07:50:05.070960756Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2022-01-27T07:50:05.570976485Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2022-01-27T07:50:05.571021965Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2022-01-27T07:50:06.071009329Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2022-01-27T07:50:06.071042285Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2022-01-27T07:50:06.571154297Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2022-01-27T07:50:06.571257306Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2022-01-27T07:50:07.071018868Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2022-01-27T07:50:07.071065822Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2022-01-27T07:50:07.57123936Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2022-01-27T07:50:07.571284612Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2022-01-27T07:50:08.071262099Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2022-01-27T07:50:08.071342711Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
```

Is it a problem with my configuration?
