### ISSUE TITLE
Grafana-agent incorrectly tag traces received from Kubernetes pod

### ISSUE THREAD

**Issue by chenfeilee** [grafana/tempo#1284]
**Describe the bug**
We have deployed grafana-agent to AWS EKS for collection of traces. We were seeing different tag values (via the kubernetes service discovery) for different spans of the same trace. 

Seem like it was because the running pod (which the traces were being sent from) has the same private ip address as another completed pod.

**To Reproduce**
1. Deploy grafana-agent on AWS EKS
2. Start sending traces to grafana-agent
3. Look for trace in Grafana

**Expected behavior**
Spans being tagged correctly (in this case would be to only include metadata from the running pod at the time when the traces were received)

**Environment:**
 - Infrastructure: AWS EKS

**Additional Context**

<img width="604" alt="image" src="https://user-images.githubusercontent.com/90743057/153897023-1fb8b2f7-425b-480c-a995-efc0e99abb1f.png">
<img width="654" alt="image" src="https://user-images.githubusercontent.com/90743057/153897162-e1a5feab-404d-4005-9c07-2b58657944e7.png">

<img width="608" alt="image" src="https://user-images.githubusercontent.com/90743057/153897198-846a9e7f-36a8-4adc-826f-397fa5b5b209.png">
<img width="654" alt="image" src="https://user-images.githubusercontent.com/90743057/153897215-c6143f2e-358a-4c19-82ad-732f24f9bfc2.png">

**Comment by chenfeilee** [comment]
@joe-elliott any thoughts on this? thanks.

**Comment by mapno** [comment]
Hi @chenfeilee! The Grafana Agent uses Prometheus Service Discovery to get metadata from Kubernetes. It should be possible to drop `Succeeded` pods using PromSD config.

When using [`role: pod`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod), there is a metadata label `__meta_kubernetes_pod_phase`, that contains the pod's status. You could use that label to add a [relabel config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) and drop targets that have status `Suceeded`. This way, completed pods will be dropped and traces will be tagged only with `Running` pods' metadata.

Example config:
```yaml
traces:
    configs:
        - name: <name>
        ...
        scrape_configs:
            - job_name: <job-name>
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: drop
                  source_labels:
                    - __meta_kubernetes_pod_phase
                  regex: Succeeded
                  ....
```
