### ISSUE TITLE
Create features section in Tempo config

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#1287]
**Is your feature request related to a problem? Please describe.**
Tempo is gradually gaining optional features/components that can be enabled/disabled globally. We already have `search_enabled` and https://github.com/grafana/tempo/pull/1282 adds `metrics_generator_enabled`.

These toggles control major features usually impacting multiple components.

**Describe the solution you'd like**
To make it easier to find these toggles we can group them in a global section `features`, i.e.:

```yaml
features:
  multitenancy_enabled: true
  search_enabled: true
  metrics_generator_enabled: false
```

**Describe alternatives you've considered**
We can just not do this and keep the status quo:

```yaml
multitenancy_enabled: true
search_enabled: true
distributor:
  metrics_generator_enabled: true
  # ...
```

Or move them all to the top-level:

```yaml
multitenancy_enabled: true
search_enabled: true
metrics_generator_enabled: true
```

This is probably fine for now but might become impractical if we add many toggles 🤷🏻 

**Additional context**
