### ISSUE TITLE
Replace Ports 55680 to 4317 in docker-compose examples

### ISSUE THREAD

**Issue by gschmutz** [grafana/tempo#1293]
Wouldn't it be correct to now replace the ports `55680` with `4317` and `55681` with `4318` in all the examples? 

```
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../local/tempo-local.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "55680"  # otlp grpc
      - "55681"  # otlp http
      - "9411"   # zipkin
```

Of course inside a docker-compose stack, the `4317` works without having it in the `ports` list but I find it a bit missleading.
