### ISSUE TITLE
Unable to see Traces in Tempo Explore. 

### ISSUE THREAD

**Issue by pkrishnanreflexion** [grafana/tempo#1308]
**Describe the bug**
Traces are ingested into Tempo and when I query Tempo, the result status is 200, but unable to see the spans.

**To Reproduce**
1. Start Tempo & Grafana using following docker compose
```
version: "3"

services:
    tempo:
       image: grafana/tempo:latest
        container_name: tempo
        ports:
            - "3200:3200"
            - "14250:14250"
        volumes:
            - ./tempo/config/tempo-local.yaml:/etc/tempo-local.yaml
            - tempo-data:/tmp/tempo
        command: -config.file=/etc/tempo-local.yaml
        networks:
            - elastic-jaeger

    loki:
        image: grafana/loki:latest
        container_name: loki
        ports:
            - "3100:3100"
        volumes:
            - ./loki/config/loki-local-config.yaml:/loki/local-config.yaml
            - loki-data:/loki
        command: -config.file=/loki/local-config.yaml -log.level=info
        networks:
            - elastic-jaeger

    grafana:
        image: grafana/grafana:8.2.5
        ports:
                - 0.0.0.0:3000:3000
        networks:
                - elastic-jaeger

volumes:
    loki-data:
        # driver: local
    tempo-data:
        # driver: local
networks:
    elastic-jaeger:
        driver: bridge
```
3. This is my tempo config yaml

```
server:
  http_listen_port: 3200
  grpc_server_max_send_msg_size: 1000000
distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
      protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
        grpc:                          # for a production deployment you should only enable the receivers you need!
  log_received_traces: true


ingester:
  trace_idle_period: 10s               # the length of time after a trace has not received spans to consider it complete and flush it
  max_block_bytes: 1_000_000           # cut the head block when it hits this size or ...
  max_block_duration: 5m               #   this much time passes

compactor:
  compaction:
    compaction_window: 1h              # blocks in this time window will be compacted together
    max_block_bytes: 100_000_000       # maximum size of compacted blocks
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local                     # backend configuration to use
    block:
      bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
      index_downsample_bytes: 1000     # number of bytes per index record
      encoding: zstd                   # block encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    wal:
      path: /tmp/tempo/wal             # where to store the the wal locally
      encoding: snappy                 # wal encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100                 # worker pool determines the number of parallel requests to the object store backend
      queue_depth: 10000

search_enabled: true

overrides:
   max_bytes_per_trace: 10000000
   max_search_bytes_per_trace: 10000

```
4. This is screenshot of tempo ingesting logs.
<img width="1125" alt="Screen Shot 2022-02-24 at 9 00 14 AM" src="https://user-images.githubusercontent.com/94964199/155689910-4ff4d9bd-3249-4ff8-8b13-4eba8939fe97.png">

5.  This is screenhost of tempo/metrics showing 
<img width="762" alt="Screen Shot 2022-02-25 at 2 56 57 PM" src="https://user-images.githubusercontent.com/94964199/155693813-c653ca31-bc0a-4e79-a4f2-ac5b0fed11cc.png">
<img width="745" alt="Screen Shot 2022-02-25 at 2 58 59 PM" src="https://user-images.githubusercontent.com/94964199/155693835-dd901432-e2a1-414a-9c2c-a17c7c6441ca.png">

**Expected behavior**

A search for the traceID in Grafana (8.2.5) Tempo explore, is not showing the span.
Sometimes it returns a "Metric request error", while at other times, it returns the trace but spans cannot be seen.
<img width="954" alt="Screen Shot 2022-02-25 at 3 18 55 PM" src="https://user-images.githubusercontent.com/94964199/155693941-061f13df-9ee0-41b1-9f13-a75634fd7a40.png">
<img width="557" alt="Screen Shot 2022-02-25 at 3 18 47 PM" src="https://user-images.githubusercontent.com/94964199/155693969-44355036-9173-49de-9a12-0e4c99fefec7.png">

However a CURL command to retrieve trace however fetches data.

<img width="1770" alt="Screen Shot 2022-02-25 at 3 27 40 PM" src="https://user-images.githubusercontent.com/94964199/155695041-1cffec77-c82c-4d83-90cf-0458a18c6398.png">

**Environment:**
 Docker-compose deployment on a MacOS machine
