### ISSUE TITLE
Query limits don't work or work unexpectedly 

### ISSUE THREAD

**Issue by symmetriac** [grafana/tempo#1392]
**Describe the bug**
Query limits don't work or work unexpectedly  

**To Reproduce**
Make a query in grafana with tempo datasource with limit parameter, for example 1000. Looking at query inspector in response object there is an array with more than 1000 elements.
Also max_result_limit not respected. 

query frontend settings:
```
query_frontend:
  max_outstanding_per_tenant: 2000
  search:
    default_result_limit: 100
    max_result_limit: 1500
    concurrent_jobs: 300
    max_duration: 168h
```

Tested on tempo-querier traces with the same time range of 2 days:

with limit set to 1000 (less than max_result_limit)

<img width="1149" alt="Снимок экрана 2022-04-18 в 13 12 17" src="https://user-images.githubusercontent.com/46437352/163793978-8a99307a-3a4e-49c0-b1a8-8aa2c4e00e27.png">

with limit greater than max_result_limit

<img width="1149" alt="Снимок экрана 2022-04-18 в 13 16 28" src="https://user-images.githubusercontent.com/46437352/163794394-8c5f4bbf-6735-4e45-9744-629c50ae8357.png">

Same issue when querying via search api.
Is this behavior expected or am I missing some settings for this limits?

**Expected behavior**
When limit is set greater than max_result_limit response objects count is equal to max_result_limit.

**Environment:**
 - Infrastructure: Kubernetes, Grafana (v8.4.4)
 - Deployment tool: helm

**Additional Context**
