### ISSUE TITLE
[minor] "compaction cycle complete" over and over again

### ISSUE THREAD

**Issue by haf** [grafana/tempo#1423]
**Describe the bug**
When starting tempo like so

```
  tempo:
    image: grafana/tempo:1.3.2
    restart: unless-stopped
    networks:
      app:
        aliases:
        - tempo
        - tempo.app.svc
    command:
    - "-search.enabled=true"
    - "-config.file=/etc/tempo.yaml"
    volumes:
    - .tools/dc/tempo.yaml:/etc/tempo.yaml
    ports:
    - "14268"      # jaeger ingest
    - "3200"       # tempo
    - "4317:4317"  # <== primary: otlp grpc # used by OTLPSpanExporter
    - "4318"       # otlp http
    - "9411"       # zipkin
```
and writing a bunch of traces to it you see a very long list of log messages after a few day's uptime; "level=info ts=2022-05-05T13:11:42.360777173Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant"

The config and setup is taken from the docker-compose samples in this repo.

config:

```yaml
auth_enabled: false

server:
  http_listen_port: 3200

distributor:
  log_received_traces: true
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
      protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
        thrift_http:                   #

        # tcp/4317:
        grpc:                          # for a production deployment you should only enable the receivers you need!

        thrift_binary:
        thrift_compact:

    zipkin:

    otlp:
      protocols:
        http:
        grpc:

storage:
  trace:
    backend: local
    block:
      encoding: zstd
    wal:
      path: /tmp/tempo/wal
      encoding: none
    local:
      path: /tmp/tempo/blocks
```

**To Reproduce**
Start tempo

**Expected behavior**
I don't a compaction cycle every second.

**Environment:**
 - Infrastructure: macOS, docker-compose
