### ISSUE TITLE
python otel jaeger exporter,tempo query not data

### ISSUE THREAD

**Issue by tonycody** [grafana/tempo#1432]
python opentelemetry instrument install
```shell
pip install opentelemetry-sdk
pip install opentelemetry-distro
pip install opentelemetry-exporter-jaeger-proto-grpc
```

Testing python scripts:

```python
import time

from opentelemetry import trace
from opentelemetry.exporter.jaeger.proto import grpc
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import (BatchSpanProcessor,ConsoleSpanExporter)
from opentelemetry.sdk.resources import SERVICE_NAME, Resource

trace.set_tracer_provider(TracerProvider(
    resource=Resource.create({SERVICE_NAME: "my-helloworld-service"})
    ))
tracer = trace.get_tracer(__name__)

# Create a JaegerExporter to send spans with gRPC
# If there is no encryption or authentication set `insecure` to True
# If server has authentication with SSL/TLS you can set the
# parameter credentials=ChannelCredentials(...) or the environment variable
# `EXPORTER_JAEGER_CERTIFICATE` with file containing creds.

jaeger_exporter = grpc.JaegerExporter(
    collector_endpoint="localhost:14250",
    insecure=True,
)

trace.get_tracer_provider().add_span_processor(
    BatchSpanProcessor(ConsoleSpanExporter())
)

trace.get_tracer_provider().add_span_processor(
        BatchSpanProcessor(jaeger_exporter)
        )

# create some spans for testing
with tracer.start_as_current_span("foo") as foo:
    time.sleep(0.1)
    foo.set_attribute("my_atribbute", True)
    foo.add_event("event in foo", {"name": "foo1"})
    with tracer.start_as_current_span(
        "bar", links=[trace.Link(foo.get_span_context())]
    ) as bar:
        time.sleep(0.2)
        bar.set_attribute("speed", 100.0)

        with tracer.start_as_current_span("baz") as baz:
            time.sleep(0.3)
            baz.set_attribute("name", "mauricio")

        time.sleep(0.2)

    time.sleep(0.1)
```

Exporting to Jaeger is normal and can be queried
<img width="1950" alt="image" src="https://user-images.githubusercontent.com/6773121/168757043-8986dbf9-3845-4d82-ada5-8918fae6943d.png">

Exports to Tempo cannot be queried,There was no hint
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/6773121/168756435-10948b1d-2bf6-41a2-8e1c-de8a39dd77c9.png">

grafana tempo query result data:
```json
{
    "results": {
        "B": {
            "frames": [
                {
                    "schema": {
                        "name": "Trace",
                        "refId": "B",
                        "meta": {
                            "preferredVisualisationType": "trace"
                        },
                        "fields": [
                            {
                                "name": "traceID",
                                "type": "string",
                                "typeInfo": {
                                    "frame": "string"
                                }
                            },
                            {
                                "name": "spanID",
                                "type": "string",
                                "typeInfo": {
                                    "frame": "string"
                                }
                            },
                            {
                                "name": "parentSpanID",
                                "type": "string",
                                "typeInfo": {
                                    "frame": "string"
                                }
                            },
                            {
                                "name": "operationName",
                                "type": "string",
                                "typeInfo": {
                                    "frame": "string"
                                }
                            },
                            {
                                "name": "serviceName",
                                "type": "string",
                                "typeInfo": {
                                    "frame": "string"
                                }
                            },
                            {
                                "name": "serviceTags",
                                "type": "string",
                                "typeInfo": {
                                    "frame": "string"
                                }
                            },
                            {
                                "name": "startTime",
                                "type": "number",
                                "typeInfo": {
                                    "frame": "float64"
                                }
                            },
                            {
                                "name": "duration",
                                "type": "number",
                                "typeInfo": {
                                    "frame": "float64"
                                }
                            },
                            {
                                "name": "logs",
                                "type": "string",
                                "typeInfo": {
                                    "frame": "string"
                                }
                            },
                            {
                                "name": "references",
                                "type": "string",
                                "typeInfo": {
                                    "frame": "string"
                                }
                            },
                            {
                                "name": "tags",
                                "type": "string",
                                "typeInfo": {
                                    "frame": "string"
                                }
                            }
                        ]
                    },
                    "data": {
                        "values": [
                            [],
                            [],
                            [],
                            [],
                            [],
                            [],
                            [],
                            [],
                            [],
                            [],
                            []
                        ]
                    }
                }
            ]
        }
    }
}
```

**Comment by joe-elliott** [comment]
This code is using Jaeger GRPC which is supported by Tempo but not turned on by default. This config turns on all ingestion protocols:

https://github.com/grafana/tempo/blob/4e0f12da3cd2d665e5933bb402b06ca66efe5d7a/example/docker-compose/local/tempo-local.yaml#L6-L19

You may also want to use the `log_received_traces` configuration option under distributor:

https://grafana.com/docs/tempo/latest/configuration/#distributor

This option should not be used in production but is a good way to confirm that Tempo is receiving traces.

**Comment by tonycody** [comment]
> 



> This code is using Jaeger GRPC which is supported by Tempo but not turned on by default. This config turns on all ingestion protocols:
> 
> https://github.com/grafana/tempo/blob/4e0f12da3cd2d665e5933bb402b06ca66efe5d7a/example/docker-compose/local/tempo-local.yaml#L6-L19
> 
> You may also want to use the `log_received_traces` configuration option under distributor:
> 
> https://grafana.com/docs/tempo/latest/configuration/#distributor
> 
> This option should not be used in production but is a good way to confirm that Tempo is receiving traces.

However, there is no problem with otel javaagent use, so why is there a problem with python client export?

**Comment by tonycody** [comment]
> 



> This code is using Jaeger GRPC which is supported by Tempo but not turned on by default. This config turns on all ingestion protocols:
> 
> https://github.com/grafana/tempo/blob/4e0f12da3cd2d665e5933bb402b06ca66efe5d7a/example/docker-compose/local/tempo-local.yaml#L6-L19
> 
> You may also want to use the `log_received_traces` configuration option under distributor:
> 
> https://grafana.com/docs/tempo/latest/configuration/#distributor
> 
> This option should not be used in production but is a good way to confirm that Tempo is receiving traces.



> > However, there is no problem with otel javaagent use, so why is there a problem with python client export?
> 
> Likely they are using different protocols. OTel Java agent is likely using OTel GRPC which Tempo consumes in its default configuration. The python snippet you showed is using Jaeger GRPC.

The OTel javaagent export method also specifies the port number 14250 used by jaeger.

**Comment by tonycody** [comment]
> > However, there is no problem with otel javaagent use, so why is there a problem with python client export?
> 
> Likely they are using different protocols. OTel Java agent is likely using OTel GRPC which Tempo consumes in its default configuration. The python snippet you showed is using Jaeger GRPC.

I adjusted the tempo.yaml configuration and tried again, but still could not query traceId Span data. The current phenomenon is that traceId is present in TEMPO, but Span data is empty. You can use the configuration I provided below to test it out.

# Python OTel example:

## before
```shell
pip install opentelemetry-sdk
pip install opentelemetry-distro
pip install opentelemetry-exporter-jaeger-proto-grpc
```

```python
import time

from opentelemetry import trace
from opentelemetry.exporter.jaeger.proto.grpc import JaegerExporter
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import (BatchSpanProcessor,ConsoleSpanExporter)
from opentelemetry.sdk.resources import SERVICE_NAME, Resource

trace.set_tracer_provider(TracerProvider(
    resource=Resource.create({SERVICE_NAME: "my-helloworld-service"})
    ))
tracer = trace.get_tracer(__name__)

jaeger_exporter = JaegerExporter(
     collector_endpoint="your_backend_ip:14250",
    insecure=True,
)

trace.get_tracer_provider().add_span_processor(
    BatchSpanProcessor(ConsoleSpanExporter())
)

trace.get_tracer_provider().add_span_processor(
    BatchSpanProcessor(jaeger_exporter)
)

# create some spans for testing
with tracer.start_as_current_span("foo") as foo:
    time.sleep(0.1)
    foo.set_attribute("my_atribbute", True)
    foo.add_event("event in foo", {"name": "foo1"})
    with tracer.start_as_current_span(
        "bar", links=[trace.Link(foo.get_span_context())]
    ) as bar:
        time.sleep(0.2)
        bar.set_attribute("speed", 100.0)

        with tracer.start_as_current_span("baz") as baz:
            time.sleep(0.3)
            baz.set_attribute("name", "mauricio")

        time.sleep(0.2)

    time.sleep(0.1)
```

# docker-compose.yaml
```yaml
tempo:
    image: grafana/tempo:1.4.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./data:/tmp/tempo
    #restart: unless-stopped  
    ports:
            #- "14268:14268"  # jaeger ingest, Jaeger - Thrift HTTP
      - "14250:14250"  # Jaeger - GRPC
        #- "55680:55680"  # OpenTelemetry
      - "3200:3200"    # Tempo
        #- "16686:16686"
grafana:
    image: grafana/grafana:8.5.0
    user: "0"
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
        #- GF_AUTH_ANONYMOUS_ENABLED=true
        #- GF_AUTH_ORG_ROLE=Editor
        #- GF_AUTH_DISABLE_LOGIN_FORM=true
        #- GF_AUTH_ANONYMOUS_ORG_NAME="Main Org."
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana:/var/lib/grafana
```

# tempo.yaml
```yaml
auth_enabled: false

server:
  http_listen_port: 3200

distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
      protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver
        grpc:                          # for a production deployment you should only enable the receivers you need!
  log_received_traces: true

ingester:
  trace_idle_period: 10s               # the length of time after a trace has not received spans to consider it complete and flush it
  #traces_per_block: 1_000_000
  max_block_duration: 5m               #   this much time passes

compactor:
  compaction:
    compaction_window: 1h              # blocks in this time window will be compacted together
    max_compaction_objects: 1000000    # maximum size of compacted blocks
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /tmp/tempo/wal            # where to store the the wal locally
      #bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
      #index_downsample: 10             # number of traces per index record
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100                 # the worker pool mainly drives querying, but is also used for polling the blocklist
      queue_depth: 10000
```
