### ISSUE TITLE
Metrics-generator should filter out spans based upon attributes

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#1482]
**Is your feature request related to a problem? Please describe.**
If the metrics-generator is enabled for a tenant, it will generate metrics for all traces that are ingested. In some cases it would be nice if we could only generate metrics for a subset of spans.

Example:
- don't collect metrics for traces that don't have the attribute `http.code`
- only generate metrics for spans from service XXX

**Describe the solution you'd like**
It should be possible to configure filters that include/exclude spans based upon their attributes.

**Describe alternatives you've considered**
There is no alternative AFAIK. You could drop the metrics when remote writing them, but that is definitely not ideal.

**Additional context**

**Comment by faustodavid** [comment]
What do you think of having filters a bit similar to the OpenTelemetry Collector but just for the metrics processors?

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/coreinternal/processor/filterspan/filterspan.go

It will allow multiple **includes** or **excludes** filters that can be defined using **regexp** or **strict** match type.

```yaml
metrics_generator:
  processor:
    span_metrics:
      dimensions:
        - http.method
        - http.host
      span_filters:
        include:
          - match_type: regexp
            attributes:
              - key: http.method
                value: "GET|POST|PUT|DELETE|HEAD|OPTIONS|TRACE"
        exclude:
         - match_type: strict
           attributes:
            - key: http.host
              value: "some-host-name"
```
