### ISSUE TITLE
Service graph not created from Zipkin trace

### ISSUE THREAD

**Issue by mecseid** [grafana/tempo#1495]
**Describe the bug**
Made some request like the attached trace JSON, but the metrics_generator not created any metric about service graph.

**To Reproduce**
I attached the JSON export of the trace.
[trace.json.txt](https://github.com/grafana/tempo/files/8918752/trace.json.txt)

**Expected behavior**
Generate service graph with 4 service (api-gateway, sales-service, crm-service, document-generator-service).

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Version: 1.4.1

**Configuration**
Attached tempo.yaml file:
```yaml
    metrics_generator_enabled: true
    metrics_generator:
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090/api/v1/write
            send_exemplars: true
    multitenancy_enabled: false
    search_enabled: true
    compactor:
      compaction:
        compacted_block_retention: 744h
    distributor:
      receivers:
            opencensus: null
            zipkin:
              endpoint: 0.0.0.0:9411
    ingester:
          {}
    server:
          http_listen_port: 3100
    storage:
          trace:
            backend: local
            local:
              path: /var/tempo/traces
            wal:
              path: /var/tempo/wal
    overrides:
          metrics_generator_processors:
          - service-graphs
          - span-metrics
          per_tenant_override_config: /conf/overrides.yaml
```
