### ISSUE TITLE
2x memory increase after upgrade

### ISSUE THREAD

**Issue by anjmao** [grafana/tempo#1516]
**Describe the bug**
After upgrading from tempo grafana/tempo:1e8583d9 to grafana/tempo:1.4.1 memory usage increased from 4Gib to 8Gib. CPU usage also increased.
<img width="1647" alt="Screenshot 2022-06-27 at 22 27 33" src="https://user-images.githubusercontent.com/3028012/176029768-8aa572bb-b942-4b95-aaa2-b2ea4bda8b47.png">

**To Reproduce**
Helm chart version grafana/tempo 0.15.4 (Grafana Tempo Single Binary Mode)

Helm values
```yaml
fullnameOverride: tempo
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3100"
  prometheus.io/path: "/metrics"
tempo:
  retention: 48h
  storage:
    trace:
      backend: local
  resources:
    requests:
      cpu: "2"
      memory: 8Gi
    limits:
      memory: 8Gi
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 80Gi
```

**Expected behavior**
No memory  and cpu increase after upgrade.

**Environment:**
 - Infrastructure: Kubernetes 1.22
 - Deployment tool: helm

**Additional Context**
Nothing specific, sometimes I see errors:
```
rpc error: code = FailedPrecondition desc = LIVE_TRACES_EXCEEDED: max live traces exceeded for tenant single-tenant: per-user traces limit (local: 10000 global: 0 actual local: 10000) exceeded
```
Will need to increase live traces limit, but I was hitting this limits with old version too.
