### ISSUE TITLE
Add generic dashboard for metrics from tempo

### ISSUE THREAD

**Issue by dusatvoj** [grafana/tempo#1542]
**Describe the solution you'd like**

I have docker-compose deployment so the K8s dashboards are not good for me. It would be great if there is a dashboard like for prometheus 2.0 for tempo's data from `/metrics` endpoint (havent found any JSON yet or any dashboard at grafana.com)

**Additional context**

Smth like this: https://grafana.com/grafana/dashboards/3662

for generic usage like this

```
- job_name: 'local-tempo'
    static_configs:
      - targets:
          - 'tempo:3200'
```
