### ISSUE TITLE
query-frontend fails to start with the recomended search options

### ISSUE THREAD

**Issue by Symbianx** [grafana/tempo#1543]
**Describe the bug**
Using the recomended search options described in the [docs](https://grafana.com/docs/tempo/latest/operations/backend_search/#query-frontend) causes the query frontend service to fail to start with the following log:
```
failed parsing config: failed to parse configFile /conf/tempo.yaml: yaml: unmarshal errors:
  line 27: field hedge_requests_at not found in type frontend.SearchConfig
  line 29: field hedge_requests_up_to not found in type frontend.SearchConfig
```

**To Reproduce**
1. Configure the query-frontend with the `hedge_requests_at` and `hedge_requests_up_to` flags.
2. Start the query-frontend with version 1.4.1

**Expected behavior**
Should not crash the container

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: yaml

**Additional Context**
query_frontend config:
```yaml
query_frontend:
  # When increasing concurrent_jobs, also increase the queue size per tenant,
  # or search requests will be cause 429 errors.
  max_outstanding_per_tenant: 2000
  search:
    # At larger scales, increase the number of jobs attempted simultaneously,
    # per search query.
    concurrent_jobs: 2000
    # If set to a non-zero value a second request will be issued at the provided duration. Recommended to
    # be set to p99 of search requests to reduce long tail latency.
    hedge_requests_at: 5s
    # The maximum number of requests to execute when hedging. Requires hedge_requests_at to be set.
    hedge_requests_up_to: 3
```
