### ISSUE TITLE
Scalable Single Binary: Compactor ring not created

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1594]
The scalable single binary does not correctly create the compactor ring. The consequence of this is that the different instances of the Tempo process will attempt to compact the same blocks repeatedly.

Steps to reproduce:
- start the scalable single binary
- note that `/compator/ring` returns 404

**Comment by zalegrala** [comment]
It looks like it works if we include a ring config in our examples.  Is that where you saw this?

I'll update to include the ring config in our examples a bit.

**Comment by LeonD9** [comment]
> It looks like it works if we include a ring config in our examples. Is that where you saw this?
> 
> I'll update to include the ring config in our examples a bit.

@zalegrala When i tried adding the compactor ring in single binary:
```
compactor:
  ring:
    kvstore:
      store: memberlist
  compaction:
    compacted_block_retention: 24h
```
i started getting the following errors:
```
level=error ts=2022-07-24T14:39:20.41574298Z caller=frontend_processor.go:64 msg="error contacting frontend" address=10.12.3.20:9095 err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.12.3.20:9095: connect: connection refused\""
level=error ts=2022-07-24T14:39:20.424880016Z caller=frontend_processor.go:64 msg="error contacting frontend" address=10.12.3.20:9095 err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.12.3.20:9095: connect: connection refused\""
level=error ts=2022-07-24T14:39:20.453041883Z caller=frontend_processor.go:64 msg="error contacting frontend" address=10.12.3.20:9095 err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.12.3.20:9095: connect: connection refused\""
level=error ts=2022-07-24T14:39:20.589358082Z caller=frontend_processor.go:64 msg="error contacting frontend" address=10.12.3.20:9095 err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.12.3.20:9095: connect: connection refused\""
level=error ts=2022-07-24T14:39:20.745808117Z caller=frontend_processor.go:64 msg="error contacting frontend" address=10.12.3.20:9095 err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.12.3.20:9095: connect: connection refused\""
level=debug ts=2022-07-24T14:39:21.119964774Z caller=memberlist_client.go:821 msg="CAS attempt failed" err="no change detected" retry=true
level=debug ts=2022-07-24T14:39:22.120917467Z caller=memberlist_client.go:821 msg="CAS attempt failed" err="no change detected" retry=true
level=debug ts=2022-07-24T14:39:23.122101609Z caller=memberlist_client.go:821 msg="CAS attempt failed" err="no change detected" retry=true
level=debug ts=2022-07-24T14:39:24.122305606Z caller=memberlist_client.go:821 msg="CAS attempt failed" err="no change detected" retry=true
level=debug ts=2022-07-24T14:39:25.123284634Z caller=memberlist_client.go:821 msg="CAS attempt failed" err="no change detected" retry=true
level=debug ts=2022-07-24T14:39:26.124355601Z caller=memberlist_client.go:821 msg="CAS attempt failed" err="no change detected" retry=true
```
without compactor ring the pods start fine, this is my configuration:
```
multitenancy_enabled: false

search_enabled: true

metrics_generator_enabled: true

compactor:
  compaction:
    compacted_block_retention: 24h

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
  log_received_traces: true

ingester:
  trace_idle_period: 10s
  lifecycler:
    ring:
      kvstore:
        store: memberlist
    heartbeat_period: 100ms

server:
  http_listen_port: 3100
  log_level: debug

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - tempo-headless.kube-system.svc.cluster.local:7946
  
  storage:
  trace:
    backend: s3
    s3:
      bucket: example
      endpoint: s3.example.amazonaws.com
      region: example
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  frontend_worker:
    frontend_address: tempo-headless.kube-system.svc.cluster.local:9095

query_frontend:
  search:
    max_duration: 0

overrides:
  max_traces_per_user: 0
  max_search_bytes_per_trace: 0
  ```
  
  am i missing something in my configuration for compactor ring to work correctly?

**Comment by zalegrala** [comment]
This might be the difference between Single Binary and Scalable Single Binary.  The first mode is meant to be a stand-alone single instance, where as the second is to be running all components on each instance, but where there are several instances that use the ring to coordinate the work. Which mode are you working with in this case?

**Comment by LeonD9** [comment]
> This might be the difference between Single Binary and Scalable Single Binary. The first mode is meant to be a stand-alone single instance, where as the second is to be running all components on each instance, but where there are several instances that use the ring to coordinate the work. Which mode are you working with in this case?

@zalegrala i am using       `-target=scalable-single-binary` from what i understand in this mode the rings for all micro services should work.

**Comment by zalegrala** [comment]
That sounds right as far as which mode you are using.  Is your pod listening on :9095?  A connection refused is different than the 404 reported in this issue.  What does `netstat -luntp` give you from within the container?

**Comment by LeonD9** [comment]
@zalegrala Yeah the pod listens on port 9095, its weird because connection refused only happens when i add compaction ring, without it there are no errors.
```
tcp        0      0 :::3100                 :::*                    LISTEN      1/tempo
tcp        0      0 :::4317                 :::*                    LISTEN      1/tempo
tcp        0      0 :::4318                 :::*                    LISTEN      1/tempo
tcp        0      0 :::9095                 :::*                    LISTEN      1/tempo
tcp        0      0 :::7946                 :::*                    LISTEN      1/tempo
```

**Comment by LeonD9** [comment]
@zalegrala the ip of both pods refuse to connect to the compactor ring for some reason, i get this error when i check the status: `context: canceled`
this is the status i saw from the api:
```
GET /status/services
+------------------------+----------+--------------+
| SERVICE NAME           |   STATUS | FAILURE CASE |
+------------------------+----------+--------------+
| compactor              | Failed | context: canceled             |
| distributor            |  Running |              |
| ingester               |  Running |              |
| memberlist-kv          |  Running |              |
| metrics-generator      |  Running |              |
| metrics-generator-ring |  Running |              |
| overrides              |  Running |              |
| querier                |  Running |              |
| query-frontend         |  Running |              |
| ring                   |  Running |              |
| server                 |  Running |              |
| store                  |  Running |              |
+------------------------+----------+--------------+
```
and this is the config of compactor:
```
compactor:
    ring:
        kvstore:
            store: memberlist
            prefix: collectors/
            consul:
                host: localhost:8500
                acl_token: ""
                http_client_timeout: 20s
                consistent_reads: false
                watch_rate_limit: 1
                watch_burst_size: 1
            etcd:
                endpoints: []
                dial_timeout: 10s
                max_retries: 10
                tls_enabled: false
                tls_cert_path: ""
                tls_key_path: ""
                tls_ca_path: ""
                tls_server_name: ""
                tls_insecure_skip_verify: false
                username: ""
                password: ""
            multi:
                primary: ""
                secondary: ""
                mirror_enabled: false
                mirror_timeout: 2s
        heartbeat_period: 5s
        heartbeat_timeout: 1m0s
        wait_stability_min_duration: 1m0s
        wait_stability_max_duration: 5m0s
        instance_id: tempo-1
        instance_interface_names:
            - eth0
            - en0
        instance_port: 0
        instance_addr: ""
        wait_active_instance_timeout: 10m0s
    compaction:
        chunk_size_bytes: 5242880
        flush_size_bytes: 31457280
        compaction_window: 1h0m0s
        max_compaction_objects: 6000000
        max_block_bytes: 107374182400
        block_retention: 336h0m0s
        compacted_block_retention: 24h0m0s
        retention_concurrency: 10
        iterator_buffer_size: 1000
        max_time_per_tenant: 5m0s
        compaction_cycle: 30s
    override_ring_key: compactor
```
 It fails from logs after this:
 ```
    level=info ts=2022-07-27T10:34:47.671641975Z caller=compactor.go:144 msg="waiting until compactor ring topology is stable" min_waiting=1m0s max_waiting=5m0s`
    level=debug ts=2022-07-27T10:34:47.67633373Z caller=memberlist_client.go:821 msg="CAS attempt failed" err="no change detected" retry=true
```
 
All the other services/rings run correctly only compactor when ring is enabled fails.

**Comment by zalegrala** [comment]
Hi @LeonD9 May I have the complete config you are providing to the SSB?  Obscure any secrets, and I'll try to test locally.  I'm a little confused because I included a test in #1597 that checks the ring endpoint.

**Comment by LeonD9** [comment]
@zalegrala Here is the complete configuration i use that has the compactor ring error:
```
multitenancy_enabled: false

search_enabled: true

metrics_generator_enabled: true

compactor:
  compaction:
    compacted_block_retention: 24h
  ring:
    kvstore:
      store: memberlist

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
  log_received_traces: true

ingester:
  trace_idle_period: 10s
  lifecycler:
    ring:
      kvstore:
        store: memberlist
    heartbeat_period: 100ms

server:
  grpc_server_max_send_msg_size: 20000000
  grpc_server_max_recv_msg_size: 20000000
  http_listen_port: 3100
  log_level: info

metrics_generator:
  registry:
    collection_interval: 1s
  storage:
    path: /var/tempo
    remote_write:
      - url: http://prometheus-server.kube-system.svc.cluster.local:9090/api/v1/write
        send_exemplars: true

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - tempo-headless.kube-system.svc.cluster.local:7946

storage:
  trace:
    backend: s3
    s3:
      bucket: example
      endpoint: s3.example.amazonaws.com
      region: example
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  frontend_worker:
    frontend_address: tempo-headless.kube-system.svc.cluster.local:9095

query_frontend:
  search:
    max_duration: 0

overrides:
  max_traces_per_user: 0
  max_search_bytes_per_trace: 0
  metrics_generator_processors: ['service-graphs', 'span-metrics']
```

**Comment by zalegrala** [comment]
Hi @LeonD9, apologies for the delay here.

I was able to test this config using the docker compose example in the repo and had to make a few changes.  Here is only the changes that I made compared to the configuration above, most of which was changing the receivers and the addresses in question here.

```yaml
querier:
  frontend_worker:
    frontend_address: tempo1:9095
distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
        thrift_binary:
        thrift_compact:
    otlp:
      protocols:
        grpc: null
        http: null
memberlist:
  join_members:
    - tempo1:7946
```

[This config](https://github.com/grafana/tempo/blob/main/example/docker-compose/scalable-single-binary/tempo-scalable-single-binary.yaml) is a good starting place for SSB mode.  Specifically the join members there, but the situation may vary due to kubernetes.

Let me know what you think.

**Comment by LeonD9** [comment]
Hey @zalegrala sorry for the delay in response,
I tried changing memberlist and frontend_address to:
```
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - tempo-0.tempo-headless.kube-system.svc.cluster.local:7946
  - tempo-1.tempo-headless.kube-system.svc.cluster.local:7946
  
  querier:
  frontend_worker:
    frontend_address: tempo-1.tempo-headless.kube-system.svc.cluster.local:9095
  ```
  
  still got the same issues and the pods are unable to start, its weird that it happens only with compactor ring.
