### ISSUE TITLE
Configuration for querier.frontend_worker.grpc_client_config.max_recv_msg_size doesn't seem to work?

### ISSUE THREAD

**Issue by mariusvniekerk** [grafana/tempo#1596]
# Describe the bug

When trying to query very large traces in grafana it gives the follow error.

## Error message in grafana
```
failed to get trace with id: 19d5517f5f92a4c58286b227773b81cc 
Status: 500 Internal Server Error Body: error querying ingesters in Querier.FindTraceByID: 
rpc error: 
code = ResourceExhausted 
desc = grpc: received message after decompression larger than max (104857601 vs. 104857600)
```

This is in spite of the following being in my configuration file for tempo

## tempo config yaml
```yaml

server:
  http_listen_port: 3200
  grpc_server_max_recv_msg_size: 200_000_000
  grpc_server_max_send_msg_size: 200_000_000

querier:
  frontend_worker:
    grpc_client_config:
      max_recv_msg_size: 200_000_000
      max_send_msg_size: 200_000_000
```

Is there another component that also needs to updated with this new value?

# To Reproduce
1. Run tempo docker container with the configuration above and generate a very large trace.
```
docker.io/grafana/tempo                 latest        b11ca097701b  5 hours ago   81.6 MB
```
2. Query the trace in grafana

# Expected behavior

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: docker-compose

If the query on grafana fails with this size limit I would expect it to use the limit configured.

**Comment by mariusvniekerk** [comment]
<img width="878" alt="Screen Shot 2022-07-22 at 12 18 32" src="https://user-images.githubusercontent.com/73973/180481663-101fde6b-5a3d-40cc-842e-2bf597ecd9dd.png">

**Comment by joe-elliott** [comment]
Using the provided config file in the original post I am running:

```
go run ./cmd/tempo --storage.trace.backend=local --storage.trace.wal.path=/tmp/tempo/wal --storage.trace.local.path=/tmp/tempo/traces --config.file=test.yaml
```

I can then `curl http://localhost:3200/status/config` and see that the values have been set correctly:

```
GET /status/config
---
target: all
metrics_generator_enabled: false
http_api_prefix: ""
server:
    grpc_server_max_recv_msg_size: 200000000
    grpc_server_max_send_msg_size: 200000000
...
querier:
  frontend_worker:
    grpc_client_config:
      max_recv_msg_size: 200000000
      max_send_msg_size: 200000000
```

So the values seem to be loaded correctly from the config file. I also put some debug print lines into where we instantiate the frontend worker and it seemed to correctly pass this config to GRPC when it instantiated the connection.

When you pass the config options shown can you confirm that `/status/config` is showing the expected values?

**Comment by kago-dk** [comment]
I can confirm that /status/config shows the expected values, while I still get the error shown in the description.

**Comment by cameronbraid** [comment]
I've hit this same issue, please change to make these fields configurable

**Comment by cameronbraid** [comment]
aah, I think the issue is caused by a different config :

```
query_frontend:
    search:
        target_bytes_per_job: 104857600
```

increasing this fixed it for me

**Comment by cameronbraid** [comment]
> aah, I think the issue is caused by a different config :
> 
> ```
> query_frontend:
>     search:
>         target_bytes_per_job: 104857600
> ```
> 
> increasing this fixed it for me

Sorry, this is incorrect, I was loading a smaller trace by accident when testing it.

**Comment by zalegrala** [comment]
Is this still an issue for folks, or do we have a workaround?

**Comment by sy-bee** [comment]
For anyone coming here, this is what solved the issue for me: increase the `max_recv_msg_size` / `grpc_server_max_recv_msg_size` one byte over it's `*send*` counterpart. Example:
```
server:
      grpc_server_max_recv_msg_size: 20000001
      grpc_server_max_send_msg_size: 20000000
```

**Comment by sy-bee** [comment]
This is still an issue no matter which value I set for the max receiver - it always receive 1 byte more and generates a log like:
```{"caller":"rate_limited_logger.go:27","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (20000002 vs. 20000001)","level":"error","msg":"pusher failed to consume trace data","ts":"2024-03-19T10:31:14.658927083Z"}```

**Comment by zalegrala** [comment]
Are you in a position to test the change in https://github.com/grafana/tempo/pull/3208 ?  I can build an image if that's helpful.  If so, you will want to read the changelog from your current version up to the image version.

**Comment by dariusj1** [comment]
yepp, same here. I have a tempo setup in k8s and this one-byte-off error is getting really annoying.

I had bypassed it before by lowering batch size, but then it reoccurred. Now I've lowered it down to 500, IDK how long it'll last until the next one-byte-off.

Where does that 1 byte spillover come from anyway...?

**Comment by joe-elliott** [comment]
I feel like there are a lot of different issues related to the same config. I see both write path (distributors/ingesters) and read path (query-frontend/queriers/ingesters). I am a bit confused b/c we don't see these issues internally and when we do they make sense (i.e. the grpc message is simply larger than the configured size).

Internally we have the following config on all Tempo components. The exact numbers vary but the same fields are set:
```
server:
    grpc_server_max_recv_msg_size: 1.34217728e+08
    grpc_server_max_send_msg_size: 1.34217728e+08
```

We then also have the following config on the querier:
```
querier:
    frontend_worker:
        grpc_client_config:
            max_send_msg_size: 1.34217728e+08
```

Hopefully this will help folks work out this issue.

**Comment by fculpo** [comment]
Hi, just encountered same issue (off by one byte exactly):

from the sender (alloy): `XXX responded with HTTP Status Code 429, Message=grpc: received message after decompression larger than max (10485761 vs. 10485760),`

from the receiver (tempo): `{"caller":"rate_limited_logger.go:27","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (10485761 vs. 10485760)","level":"error","msg":"pusher failed to consume trace data","ts":"2024-08-26T12:03:28.883708979Z"}`

The exactly 1 bytes excess no matter the actuel limit is something interesting to dig in I think.

**Comment by vsomwanshi** [comment]
I'm seeking for an information where i could set below parameters to certain value.

```
server:
  grpc_server_max_recv_msg_size: 15000000
  grpc_server_max_send_msg_size: 15000000
```

I do not find any option to change it under `TempoStack` configuration as it is getting overwritten automatically.

```
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: dev-tempostack
  namespace: grafana-tempo-dev
spec:
  observability:
    grafana:
      instanceSelector: {}
    metrics: {}
    tracing:
      jaeger_agent_endpoint: 'localhost:6831'
  resources:
    total:
      limits:
        cpu: '6'
        memory: 15Gi
  search:
    defaultResultLimit: 20
    maxDuration: 0s
  managementState: Managed
  limits:
    global:
      ingestion:
        ingestionBurstSizeBytes: 15000000
        ingestionRateLimitBytes: 15000000
        maxBytesPerTrace: 50000000
      query:
        maxSearchDuration: 0s
  serviceAccount: dev-tempostack
  images: {}
  template:
    compactor:
      replicas: 3
    distributor:
      component:
        replicas: 1
      tls:
        enabled: false
    gateway:
      component: {}
      enabled: false
      ingress:
        route: {}
    ingester:
      replicas: 1
    querier:
      replicas: 2
    queryFrontend:
      component:
        replicas: 1
      jaegerQuery:
        enabled: true
        ingress:
          route:
            termination: edge
          type: route
        monitorTab:
          enabled: false
          prometheusEndpoint: ''
  replicationFactor: 1
  storage:
    secret:
      name: grafana-tempo-cos
      type: s3
    tls:
      enabled: false
  storageSize: 100Gi
  hashRing:
    memberlist: {}
  retention:
    global:
      traces: 12h0m0s
```

Any leads would be really helpful, Thanks !!
