### ISSUE TITLE
tempo-query in query-frontent needs r/w pod fs

### ISSUE THREAD

**Issue by rlex** [grafana/tempo#1621]
**Describe the bug**
When running tempo with r/o rootfs, following error is printed: 
```
2022-08-07T14:09:06.263Z [ERROR] tempo-query: plugin init error: error="open /tmp/plugin164587256: read-only file system" timestamp=2022-08-07T14:09:06.263Z
```

**To Reproduce**
Install tempo-distributed chart with following values:
```
        tempo:
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
```
Observe tempo-query container in tempo-query-frontend crashing.

The key is readOnlyRootFilesystem: true

**Expected behavior**
Container should start

**Environment:**
 - Infrastructure: k8s
 - Deployment tool: helm

**Additional Context**
Related PR: https://github.com/grafana/helm-charts/pull/1672
