### ISSUE TITLE
Errors form distributor "context deadline exceeded" 

### ISSUE THREAD

**Issue by javdet** [grafana/tempo#1624]
**Describe the bug**
I have a lot of dropped traces. Errors form distributors 
```
level=error ts=2022-08-08T12:54:50.237305922Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context deadline exceeded"
level=error ts=2022-08-08T12:55:01.377532608Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context canceled"
level=error ts=2022-08-08T12:55:20.983607767Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context deadline exceeded"
level=error ts=2022-08-08T12:55:34.83259462Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context deadline exceeded"
level=error ts=2022-08-08T12:55:38.333709329Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context deadline exceeded"
level=error ts=2022-08-08T12:55:41.23312395Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context canceled"
level=error ts=2022-08-08T12:55:44.841565822Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context canceled"
level=error ts=2022-08-08T12:56:01.016239081Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context canceled"
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Tempo from helm chart tempo-distributed 0.20.3 and Grafana agent 0.25.1
2. Perform Operations (Write)

**Tempo configuration**
```
multitenancy_enabled: false
search_enabled: true
compactor:
  compaction:
    block_retention: 700h
    iterator_buffer_size: 800
  ring:
    kvstore:
      store: memberlist
distributor:
  ring:
    kvstore:
      store: memberlist
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
          endpoint: 0.0.0.0:14268
querier:
  frontend_worker:
    frontend_address: tempo-query-frontend-discovery:9095
ingester:
  trace_idle_period: 1m
  lifecycler:
    ring:
      replication_factor: 2
      kvstore:
        store: memberlist
    tokens_file_path: /var/tempo/tokens.json
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
    - tempo-gossip-ring
overrides:
  max_search_bytes_per_trace: 0
  ingestion_burst_size_bytes: 60000000
  ingestion_rate_limit_bytes: 50000000
  max_bytes_per_trace: 9000000
server:
  http_listen_port: 3100
  log_level: info
  log_format: logfmt
  grpc_server_max_recv_msg_size: 4194304
  grpc_server_max_send_msg_size: 4194304
storage:
  trace:
    backend: s3
    s3:
      bucket: m2-tempo-prod
      region: us-central1
      access_key: ******
      secret_key: ******
    blocklist_poll: 5m
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
    cache: memcached
    memcached:
      consistent_hash: true
      host: tempo-memcached
      service: memcached-client
      timeout: 500ms
metrics_generator:
  ring:
    kvstore:
      store: memberlist
  storage:
    path: /var/tempo/wal
```
** Grafana agent remote write **
```
traces:
      configs:
        - name: jaeger
          receivers:
            ...
          batch:
            send_batch_size: 8192
            timeout: 20s
          remote_write:
            - endpoint: tempo-distributor.observability.svc.cluster.local:14250
              insecure: true
              insecure_skip_verify: true
              protocol: grpc
              format: jaeger
              sending_queue:
                queue_size: 5000
              retry_on_failure:
                max_elapsed_time: 30s
```
**Expected behaviour**
Distributors don't drop traces

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**
Metric `tempo_discarded_spans_total`
```
tempo_discarded_spans_total{container="distributor", endpoint="http", instance="10.107.156.36:3100", job="tempo-distributor", namespace="observability", pod="tempo-distributor-75db5b54cb-k6tl2", reason="internal_error", service="tempo-distributor", tenant="single-tenant"}
```

**Comment by joe-elliott** [comment]
Does this occur once you reach a certain threshold of spans or bytes per second? Replication factor 2 is also a weird config. We have used it in the past, but haven't touched it for probably over a year. It's hard to guarantee any behavior when using it.

**Comment by javdet** [comment]
As I see by metric tempo_distributor_spans_received_total - about 20 spans per second and 2 Mb/s. I've changed replicas to 3 and see the same errors. Additional information: I have 6 distributors and 12 ingestors. Should I increase some limits?

**Comment by joe-elliott** [comment]
it seems like your spans are 100KB each? that is extremely large for a single span. I'm guessing you will need to increase the write timeout between the distributor and the ingester.

```
distributor:
  ingester_client:
    remote_timeout: 5s (default)
```

You could also try reducing the batch size you push to tempo.

**Comment by javdet** [comment]
Thanks for advice. I increased remote_timeout up to 20s and reduce batch_size to 4096. It seems that throughput increased but I see a lot of errors yet

**Comment by mac2000** [comment]
Having similar issue, but discovered it from another side

having "microservices" setup in kubernetes

in average tempo distributor consumes approx 500mb of ram

but from time to time memory usage spikes dramatically till OOM

hypthis: there is a bunch of services talking to each other and somehow some of them are not sending traces to tempo, which makes distributor queue them till receiving all data - which may describe why its happening

but then I also found such an error in distributor logs

if that's will help I can grab some metrics/and or logs to figure out whats going on

at moment just increasing memory, already to 4gb

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/88868/189870664-75f20f62-b1d3-4ead-898c-da4fd1eb2b27.png">

but I bed it wont solve the problem


attaching config, but nocing fancy here, except few minor tuning for other issues we have found earlier:

<details>
<summary>tempo.yml</summary>

```yml
multitenancy_enabled: false
search_enabled: true

server:
  # http_listen_port: 3200
  log_level: info
  #log_level: debug
  #log_format: json

  # this one is related to relatively "big" payloads
  # seems like this settings do nothing when we are sendin to :4317 (grpc) - we are receving "grpc: received message larger than max (7157694 vs. 4194304)" and sending to :4318 (http) we receinving "received message after decompression larger than max (4194305 vs. 4194304)"
  # but with this setting :4318 (http) becomes working
  # default value is 4194304 we are increased it x10 times
  grpc_server_max_recv_msg_size: 41943040
  grpc_server_max_send_msg_size: 41943040

distributor:
  ring:
    kvstore:
      store: memberlist
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
      

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist

metrics_generator_enabled: true
overrides:
  # this one seems to be causing "size of search data exceeded max search bytes limit"
  # found at https://github.com/grafana/tempo/commit/09d455bd2f0fdabff318bd2a78e7824b19416c50
  max_search_bytes_per_trace: 200000
  metrics_generator_processors: 
  - service-graphs
  - span-metrics
metrics_generator:
  ring:
    kvstore:
      store: memberlist
  processor:
    service_graphs:
      # MaxItems is the amount of edges that will be stored in the store. default is 10K
      # seems to be causing: "skipped processing of spans" dropped X spans
      max_items: 20000
    span_metrics:
      dimensions:
        - db.system
        - db.name
        # added by http client instrumentation libraries
        - http.method
        - http.host
        - http.route
        # added by apollo gateway with help of overriden exporter
        - gateway.service
        - graphql.operation

  storage:
    path: /var/tempo/wal
    remote_write:
      - url: http://prometheus/api/v1/write
        send_exemplars: true



querier:
  frontend_worker:
    frontend_address: tempo-query-frontend-discovery:9095

compactor:
  ring:
    kvstore:
      store: memberlist
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: azure
    azure:
      storage-account-name: REDACTED
      container-name: REDACTED
      storage-account-key: REDACTED
    wal:
      path: /var/tempo/wal

memberlist:
  abort_if_cluster_join_fails: false
  join_members:
    - tempo-gossip-ring

```

</details>


will be glad to provide any additional data

**Comment by joe-elliott** [comment]
Those are pretty dramatic spikes in memory. What does your traffic look like during those spikes? Can you use `tempo_distributor_bytes_received_total` to determine if traffic is increasing?

The distributor does not queue span data, but it does queue metrics data. If you have the metrics generator component enabled then perhaps there is some queueing going on. Maybe check `tempo_distributor_forwader_queue_length` ? It will tell you if queueing is occuring.

**Comment by mac2000** [comment]
Hm, @joe-elliott thank you for a suggestion, i did not even thing about that, indeed we have metrics enabled with some dimensions

<details>
<summary>metrics config snippet</summary>

```yml
metrics_generator_enabled: true
overrides:
  # this one seems to be causing "size of search data exceeded max search bytes limit"
  # found at https://github.com/grafana/tempo/commit/09d455bd2f0fdabff318bd2a78e7824b19416c50
  max_search_bytes_per_trace: 200000
  metrics_generator_processors: 
  - service-graphs
  - span-metrics
metrics_generator:
  ring:
    kvstore:
      store: memberlist
  processor:
    service_graphs:
      # MaxItems is the amount of edges that will be stored in the store. default is 10K
      # seems to be causing: "skipped processing of spans" dropped X spans
      max_items: 20000
    span_metrics:
      dimensions:
        - db.system
        - db.name
        # added by http client instrumentation libraries
        - http.method
        - http.host
        - http.route
        # added by apollo gateway with help of overriden exporter
        - gateway.service
        - graphql.operation
```

</details>

We have linear increase of traffic for a first half of the day and linear decrease in second (e.g. like in usual consumer website)

From curiosity here is what I have found from various metrics:

just for reference memory usage of distributor

<img width="844" alt="image" src="https://user-images.githubusercontent.com/88868/190083998-99a66e21-6554-47d0-b1e1-5c03425d043b.png">

memory usage of mertics generator

<img width="844" alt="image" src="https://user-images.githubusercontent.com/88868/190084079-54073460-c831-476f-97d7-7a170af3f9aa.png">

even so we have overall usual daily increase of traffic both bytes and spans metrics were not spiking

<img width="846" alt="image" src="https://user-images.githubusercontent.com/88868/190084276-86a738ef-1989-483d-8108-be142de7de80.png">

and here is interesting one, 10ish minutes before first memory spike I see increase of queue, but I can not say it is huge

<img width="845" alt="image" src="https://user-images.githubusercontent.com/88868/190084461-708f979b-063e-4523-8966-61c8d00f9ca9.png">

in general right after we start seeing that distributor does not see metrics generator as a client

<img width="852" alt="image" src="https://user-images.githubusercontent.com/88868/190084667-7af6a1a6-693b-4a30-9204-d809f6151be2.png">

but theoretically it is kind of fine, e.g. after restart distributor was not added to ring yet, or something like that

---

from metrics generator side the only thing in logs happened right before is this one:

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/88868/190085172-d89c094f-78af-4d7d-949d-bfc62240459d.png">

and from distributor logs I see quadrillion of 

> failed to pushToQueue traces to tenant single-tenant queue: queue is full

so it seems like indeed the memory usage is related to this queues

then the question will be - isn't there any setting which will prevent this queue to fill up (e.g. just drop metrics in such an case)

the only related issue I have found here is #1541 but it seems like that not relates here
