### ISSUE TITLE
Jaeger UI shows incorrect list of traces - service name filter bug

### ISSUE THREAD

**Issue by pavolloffay** [grafana/tempo#1647]
**Describe the bug**
![Screenshot of Jaeger UI](https://user-images.githubusercontent.com/5618424/184936354-a64c0b2c-b1f1-48a7-a575-825468796bf9.jpg)

The search query specifies `driver` service and the result shows traces from `jaeger-query` service.
If `jaeger-query` service is specified traces from other services (e.g. `driver`) are shown as well.

Note very long time range and tempo config has enabled search with search `max_duration: 0` (unlimited time range query). The issue is present in Grafana UI with Jaeger data source with narrow timerange. 

![Screenshot of Explore - Jaeger _ Jaeger - Grafana](https://user-images.githubusercontent.com/5618424/184937847-7932012b-1255-45aa-9dbb-9f2ea4b64eba.jpg)

**To Reproduce**

Tempo monolith helm chart
```yaml
# helm template tempo-cluster -f tempo-monolith-helm-values.yaml  --namespace test-tempo grafana/tempo --version 0.15.8  > tempo-local-manifests.yaml
# docker run -it --rm --net=host grafana/grafana-oss
# add Tempo or Jaeger datasource
# http://localhost:16686/trace/7863ef3526a1b594
# http://localhost:16686/api/traces/7863ef3526a1b594

# it creates volumeClaimTemplates
persistence:
  enabled: false

extraVolumes:
  - name: data
    emptyDir:
      medium: "Memory"

tempoQuery:
  # version should include fix in tempo-query to correctly set time range
  tag: main-07746da

tempo:
  retention: 24h
  searchEnabled: true
  extraVolumeMounts:
  - mountPath: /var/tempo
    name: data
  storage:
    trace:
      # refer https://github.com/grafana/tempo/tree/master/docs/tempo/website/configuration
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

```

Tempo configmap:

```yaml
# Source: tempo/templates/configmap-tempo.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo
  namespace: test-tempo
  labels:
    helm.sh/chart: tempo-0.15.8
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo-cluster
    app.kubernetes.io/version: "1.4.1"
    app.kubernetes.io/managed-by: Helm
data:
  overrides.yaml: |
    overrides:
      {}
  tempo.yaml: |
    multitenancy_enabled: false
    search_enabled: true
    query_frontend:
      search: 
        max_duration: 0
    compactor:
      compaction:
        compacted_block_retention: 24h
    distributor:
      receivers:
            jaeger:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:14250
                thrift_binary:
                  endpoint: 0.0.0.0:6832
                thrift_compact:
                  endpoint: 0.0.0.0:6831
                thrift_http:
                  endpoint: 0.0.0.0:14268
            opencensus: null
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
    ingester:
          {}
    server:
          http_listen_port: 3100
    storage:
          trace:
            backend: local
            local:
              path: /var/tempo/traces
            wal:
              path: /var/tempo/wal
    overrides:
          per_tenant_override_config: /conf/overrides.yaml
```

**Expected behavior**
I wanted to see traces only that contain spans from the service specified in the search.

**Environment:**
 - Infrastructure: k8s
 - Deployment tool: helm ` helm template tempo-cluster -f tempo-local-values.yaml --namespace test-tempo grafana/tempo --version 0.15.8  > tempo-local-manifests.yaml`

**Additional Context**
