### ISSUE TITLE
scalable single binary memory leak

### ISSUE THREAD

**Issue by LeonD9** [grafana/tempo#1699]
**Describe the bug**
When running tempo scalable single binary statefulset on kubernetes with large traffic(100k+ spans per second) one/two pods start memory leaking and the rest has average memory usage.

![image](https://user-images.githubusercontent.com/86968998/187178962-3e09bd06-0af4-4563-a7d4-5d8539080c4a.png)
![image](https://user-images.githubusercontent.com/86968998/187186815-dfd6af82-1523-4627-9b13-906fdcd9bd17.png)

**To Reproduce**
1. Start Tempo single scalable binary version 1.5 as statefulset in k8s with the config below
2. Start Open telemetry collector version 0.58.0 as deployment in k8s with the config below
3. Run application that writes a large amount of spans per second to reach 100k+ spans

**Expected behavior**
All pods have the same memory usage ( traffic seems to be balanced )

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - 5 Pods of tempo single scalable binary version 1.5 run as statefulset
 - 5 Pods of open telemetry collector version 0.58.0 run as deployment

**Additional Context**
This is the configuration i use in tempo:
```
multitenancy_enabled: false

search_enabled: true

metrics_generator_enabled: true

compactor:
  ring:
    kvstore:
      store: memberlist
    wait_stability_min_duration: 10s
  compaction:
    block_retention: 168h
    compacted_block_retention: 1h
    flush_size_bytes: 5242880
    compaction_cycle: 5s
    compaction_window: 5m
    iterator_buffer_size: 100

distributor:
  ring:
    kvstore:
      store: memberlist
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
  log_received_spans:
    enabled: true
    include_all_attributes: true
    filter_by_status_error: false
  search_tags_deny_list:
    - "os.type"
    - "os.description"
    - "process.command_line"
    - "k8s.pod.uid"
    - "otel.library.name"
    - "net.peer.ip"

ingester:
  trace_idle_period: 1s
  flush_check_period: 1s
  lifecycler:
    ring:
      kvstore:
        store: memberlist
    heartbeat_period: 100ms
  complete_block_timeout: 200ms
  max_block_duration: 1s

server:
  grpc_server_max_send_msg_size: 20000000
  grpc_server_max_recv_msg_size: 20000000
  http_listen_port: 3100
  log_level: info

metrics_generator:
  registry:
    collection_interval: 1s
  storage:
    path: /var/tempo
    remote_write_flush_deadline: 5s
    remote_write:
      - url: http://prometheus-server.kube-system.svc.cluster.local:9090/api/v1/write
        send_exemplars: true
  processor:
    service_graphs:
      max_items: 100000

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - tempo-headless.kube-system.svc.cluster.local:7946

storage:
  trace:
    backend: s3
    s3:
      bucket: example
      endpoint: s3.example-1.amazonaws.com
      region: example-1
      hedge_requests_at: 500ms
      hedge_requests_up_to: 2
    search:
      chunk_size_bytes: 500000
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 1000
      queue_depth: 100000

querier:
  query_timeout: 2m
  frontend_worker:
    frontend_address: tempo-headless.kube-system.svc.cluster.local:9095
  search:
    query_timeout: 2m
    external_hedge_requests_at: 500ms
    external_hedge_requests_up_to: 4

query_frontend:
  query_shards: 100
  search:
    max_duration: 0
    query_backend_after: 200ms
    query_ingesters_until: 200ms
    target_bytes_per_job: 419430400

overrides:
  max_traces_per_user: 0
  max_search_bytes_per_trace: 0
  max_bytes_per_trace: 50000000
  ingestion_burst_size_bytes: 200000000
  ingestion_rate_limit_bytes: 150000000
  metrics_generator_processors: ['service-graphs', 'span-metrics']

```

Otel collector config:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        keepalive:
          server_parameters:
            max_connection_idle: 10s
            max_connection_age: 20s
            max_connection_age_grace: 20s
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 60
    spike_limit_percentage: 20
  batch: {}
  k8sattributes:
    auth_type: serviceAccount
    passthrough: false

    extract:
      metadata:
      - k8s.namespace.name
      - k8s.node.name
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.pod.start_time
      - k8s.deployment.name

    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection

  filter:
    spans:
      exclude:
        match_type: strict
        span_names:
          - /metrics

exporters:
  otlp/tempo:
    endpoint: dns:///tempo-headless.kube-system.svc.cluster.local:4317
    tls:
      insecure: true
      insecure_skip_verify: true
    balancer_name: "round_robin"

extensions:
  health_check:
     endpoint: 0.0.0.0:13133
  memory_ballast:
    size_in_percentage: 20

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - k8sattributes
      - filter
      - batch 
      exporters:
      - otlp/tempo
  extensions:
  - health_check
  - memory_ballast
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
      address: 0.0.0.0:8888
```

Ingester Push latency during test:
![image](https://user-images.githubusercontent.com/86968998/187180174-16b5b281-3ce4-47ba-8fb0-287a15246e3c.png)
