### ISSUE TITLE
[Metrics-Generator] Unimplemented Service Error Forwarder.go 

### ISSUE THREAD

**Issue by chriskuchin** [grafana/tempo#1702]
**Describe the bug**
I am trying to launch the metrics generator on Tempo 1.5.0 in microservices mode. I am running this on ECS not K8s. I believe I have everything configured appropriately. However, when the distributor tries to forward to the metrics generator I get a grpc error `rpc error: code = Unimplemented desc = unknown service tempopb.MetricsGenerator`.

There are no logs from the metrics-generator nodes other than startup. 

Not sure if i missed a config or what for this error. This is the first time I have tried to spin up the metrics-generator target

## Metrics Generator
```yml
GET /status/version
tempo, version  (branch: HEAD, revision: fd5743d5d)
  build user:       
  build date:       
  go version:       go1.18.5
  platform:         linux/arm64
GET /status/services
+-------------------+---------+--------------+
| SERVICE NAME      |  STATUS | FAILURE CASE |
+-------------------+---------+--------------+
| memberlist-kv     | Running |              |
| metrics-generator | Running |              |
| overrides         | Running |              |
| server            | Running |              |
+-------------------+---------+--------------+
GET /status/endpoints
+--------------------+-------------------------+
| NAME               | REGEX                   |
+--------------------+-------------------------+
| /debug/pprof       | ^/debug/pprof           |
| /memberlist        | ^/memberlist$           |
| /metrics           | ^/metrics$              |
| /ready             | ^/ready$                |
| /status            | ^/status$               |
| /status/{endpoint} | ^/status/(?P<v0>[^/]+)$ |
+--------------------+-------------------------+
```

Config Diff
```yml
GET /status/config
---
compactor:
    compaction:
        flush_size_bytes: 5242880
        max_block_bytes: 100000000
distributor:
    receivers:
        otlp:
            protocols:
                grpc: null
                http: null
ingester:
    lifecycler:
        ring:
            replication_factor: 2
memberlist:
    join_members:
        - dnssrv+tempo-distributor.service.obs.rtops.xyz
        - dnssrv+tempo-ingester.service.obs.rtops.xyz
        - dnssrv+tempo-querier.service.obs.rtops.xyz
        - dnssrv+tempo-query-frontend.service.obs.rtops.xyz
        - dnssrv+tempo-compactor.service.obs.rtops.xyz
metrics_generator:
    storage:
        path: /tmp/tempo/metrics
        remote_write:
            - follow_redirects: true
              metadata_config:
                max_samples_per_send: 500
                send: true
                send_interval: 1m
              queue_config:
                batch_send_deadline: 5s
                capacity: 2500
                max_backoff: 5s
                max_samples_per_send: 500
                max_shards: 200
                min_backoff: 30ms
                min_shards: 1
              remote_timeout: 30s
              url: http://mimir-distributor.service.obs.rtops.xyz:9009/api/v1/push
        wal:
            max_wal_time: 0
            min_wal_time: 0
            stripe_size: 0
            truncate_frequency: 0s
            wal_segment_size: 0
metrics_generator_enabled: true
overrides:
    metrics_generator_processors:
        - service-graphs
        - span-metrics
querier:
    frontend_worker:
        frontend_address: tempo-query-frontend.service.obs.rtops.xyz:9095
server:
    http_listen_port: 9009
storage:
    trace:
        backend: s3
        block:
            bloom_filter_false_positive: 0.05
            index_downsample_bytes: 1000
        pool:
            max_workers: 100
        s3:
            bucket: routeapp-tempo-traces
            endpoint: s3.dualstack.us-east-1.amazonaws.com
            region: us-east-1
        wal:
            path: /tmp/tempo/wal
target: metrics-generator
usage_report:
    reporting_enabled: false
```

## Distributor

Status endopint

```
GET /status/version
tempo, version  (branch: HEAD, revision: fd5743d5d)
  build user:       
  build date:       
  go version:       go1.18.5
  platform:         linux/arm64
GET /status/services
+------------------------+---------+--------------+
| SERVICE NAME           |  STATUS | FAILURE CASE |
+------------------------+---------+--------------+
| distributor            | Running |              |
| memberlist-kv          | Running |              |
| metrics-generator-ring | Running |              |
| overrides              | Running |              |
| ring                   | Running |              |
| server                 | Running |              |
+------------------------+---------+--------------+
GET /status/endpoints
+-------------------------+---------------------------+
| NAME                    | REGEX                     |
+-------------------------+---------------------------+
| /debug/pprof            | ^/debug/pprof             |
| /ingester/ring          | ^/ingester/ring$          |
| /memberlist             | ^/memberlist$             |
| /metrics                | ^/metrics$                |
| /metrics-generator/ring | ^/metrics-generator/ring$ |
| /ready                  | ^/ready$                  |
| /status                 | ^/status$                 |
| /status/{endpoint}      | ^/status/(?P<v0>[^/]+)$   |
+-------------------------+---------------------------+
```

Config Diff
```
GET /status/config
---
compactor:
    compaction:
        flush_size_bytes: 5242880
        max_block_bytes: 100000000
distributor:
    receivers:
        otlp:
            protocols:
                grpc: null
                http: null
ingester:
    lifecycler:
        ring:
            replication_factor: 2
memberlist:
    join_members:
        - dnssrv+tempo-distributor.service.obs.rtops.xyz
        - dnssrv+tempo-ingester.service.obs.rtops.xyz
        - dnssrv+tempo-querier.service.obs.rtops.xyz
        - dnssrv+tempo-query-frontend.service.obs.rtops.xyz
        - dnssrv+tempo-compactor.service.obs.rtops.xyz
metrics_generator:
    storage:
        path: /tmp/tempo/metrics
        remote_write:
            - follow_redirects: true
              metadata_config:
                max_samples_per_send: 500
                send: true
                send_interval: 1m
              queue_config:
                batch_send_deadline: 5s
                capacity: 2500
                max_backoff: 5s
                max_samples_per_send: 500
                max_shards: 200
                min_backoff: 30ms
                min_shards: 1
              remote_timeout: 30s
              url: http://mimir-distributor.service.obs.rtops.xyz:9009/api/v1/push
        wal:
            max_wal_time: 0
            min_wal_time: 0
            stripe_size: 0
            truncate_frequency: 0s
            wal_segment_size: 0
metrics_generator_enabled: true
overrides:
    metrics_generator_processors:
        - service-graphs
        - span-metrics
querier:
    frontend_worker:
        frontend_address: tempo-query-frontend.service.obs.rtops.xyz:9095
server:
    http_listen_port: 9009
storage:
    trace:
        backend: s3
        block:
            bloom_filter_false_positive: 0.05
            index_downsample_bytes: 1000
        pool:
            max_workers: 100
        s3:
            bucket: routeapp-tempo-traces
            endpoint: s3.dualstack.us-east-1.amazonaws.com
            region: us-east-1
        wal:
            path: /tmp/tempo/wal
target: distributor
usage_report:
    reporting_enabled: false
```

Runtime Config
```
GET /status/runtime_config
defaults:
  ingestion_rate_strategy: local
  ingestion_rate_limit_bytes: 15000000
  ingestion_burst_size_bytes: 20000000
  search_tags_allow_list: null
  max_traces_per_user: 10000
  max_global_traces_per_user: 0
  max_search_bytes_per_trace: 5000
  metrics_generator_ring_size: 0
  metrics_generator_processors:
  - service-graphs
  - span-metrics
  metrics_generator_max_active_series: 0
  metrics_generator_collection_interval: 0s
  metrics_generator_disable_collection: false
  metrics_generator_forwarder_queue_size: 0
  metrics_generator_forwarder_workers: 0
  metrics_generator_processor_service_graphs_histogram_buckets: []
  metrics_generator_processor_service_graphs_dimensions: []
  metrics_generator_processor_span_metrics_histogram_buckets: []
  metrics_generator_processor_span_metrics_dimensions: []
  block_retention: 0s
  max_bytes_per_tag_values_query: 5000000
  max_search_duration: 0s
  max_bytes_per_trace: 5000000
  per_tenant_override_config: ""
  per_tenant_override_period: 10s
overrides: {}
```
**Environment:**
 - ECS/Fargate

**Comment by mapno** [comment]
Hi @chriskuchin. Thanks for opening the issue. This is a very strange error. I haven't seen it before.

Does it reproduce with frequency or was it a one-off? I'm thinking it could be a race condition during start-up, but I'm not sure.

**Comment by chriskuchin** [comment]
I have rolling restarted my entire cluster and it's consistently still doing it

**Comment by chriskuchin** [comment]
My push metric for metrics-generator is 100% failing since I started it up. 

I have restarted both distributors and metrics-generators in varying orders. Honestly what it feels like is I missed a config so the grpc endpoint wasn't activated on the node or it's hitting the wrong nodes with the requests but my ring looks correct so not sure

**Comment by joe-elliott** [comment]
Two things to check/try. First, I noticed that a metrics-generator DNS entry is not present in your memberlist config:
```
memberlist:
    join_members:
        - dnssrv+tempo-distributor.service.obs.rtops.xyz
        - dnssrv+tempo-ingester.service.obs.rtops.xyz
        - dnssrv+tempo-querier.service.obs.rtops.xyz
        - dnssrv+tempo-query-frontend.service.obs.rtops.xyz
        - dnssrv+tempo-compactor.service.obs.rtops.xyz
```
We should add an entry so all of our metrics generators are participating in the memberlist cluster. This will allow the distributors to know they exist. Although I'll admit that I would have expected a different error if this is the issue.

Secondly, on one of your distributors, let's check to see what it thinks the metrics-generator ring looks like. On any distributor having the issue see what `metrics-generator/ring` tells us. It will look something like this:

![image](https://user-images.githubusercontent.com/2272392/187501017-97b70d18-ec7a-4ba7-a67c-709aa637014d.png)

**Comment by chriskuchin** [comment]
@joe-elliott Thanks for getting back to me.

Yeah i noticed the missing entry in the join but assumed that since the metrics-generators were joining everyone else even if they weren't being joined it would work. 

I have gone ahead and added my dns record to the join_members and that doesn't seem to have altered the problem.

My metrics-generator ring looks like:

![image](https://user-images.githubusercontent.com/56319639/187552118-af285e9e-1c7b-4986-b8d2-ecde5979e300.png)

Updated config now looks like (it is the same on metrics-generator and distributor)

```yaml
---
compactor:
    compaction:
        flush_size_bytes: 5242880
        max_block_bytes: 100000000
distributor:
    receivers:
        otlp:
            protocols:
                grpc: null
                http: null
ingester:
    lifecycler:
        ring:
            replication_factor: 2
memberlist:
    join_members:
        - dnssrv+tempo-metrics-generator.service.obs.rtops.xyz
        - dnssrv+tempo-distributor.service.obs.rtops.xyz
        - dnssrv+tempo-ingester.service.obs.rtops.xyz
        - dnssrv+tempo-querier.service.obs.rtops.xyz
        - dnssrv+tempo-query-frontend.service.obs.rtops.xyz
        - dnssrv+tempo-compactor.service.obs.rtops.xyz
metrics_generator:
    storage:
        path: /tmp/tempo/metrics
        remote_write:
            - follow_redirects: true
              metadata_config:
                max_samples_per_send: 500
                send: true
                send_interval: 1m
              queue_config:
                batch_send_deadline: 5s
                capacity: 2500
                max_backoff: 5s
                max_samples_per_send: 500
                max_shards: 200
                min_backoff: 30ms
                min_shards: 1
              remote_timeout: 30s
              url: http://mimir-distributor.service.obs.rtops.xyz:9009/api/v1/push
        wal:
            max_wal_time: 0
            min_wal_time: 0
            stripe_size: 0
            truncate_frequency: 0s
            wal_segment_size: 0
metrics_generator_enabled: true
overrides:
    metrics_generator_processors:
        - service-graphs
        - span-metrics
querier:
    frontend_worker:
        frontend_address: tempo-query-frontend.service.obs.rtops.xyz:9095
server:
    http_listen_port: 9009
storage:
    trace:
        backend: s3
        block:
            bloom_filter_false_positive: 0.05
            index_downsample_bytes: 1000
        pool:
            max_workers: 100
        s3:
            bucket: routeapp-tempo-traces
            endpoint: s3.dualstack.us-east-1.amazonaws.com
            region: us-east-1
        wal:
            path: /tmp/tempo/wal
target: distributor
usage_report:
    reporting_enabled: false
```
