### ISSUE TITLE
Metrics generator stopped generating span metrics for a tenant

### ISSUE THREAD

**Issue by suraciii** [grafana/tempo#1720]
**Describe the bug**

We have 4 tenants in a tempo cluster, after a point of time (at about 2022-09-05 17:17:00), one of those tenants has no span metrics generated any more, other tenants have no such issue.

After we restarted metrics-generator, it started to generate metrics for this tenant again

**To Reproduce**
Sorry that I don't find a way to reproduce this issue

**Environment:**
 - Infrastructure: Kubernetes

**Additional Context**

1. Some related metrics:

`rate(tempo_metrics_generator_spans_received_total{component="metrics-generator", tenant="infra"}[$__rate_interval])`:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/13304483/188592207-af5587c6-bc44-4863-bbcb-493545b42212.png">

`tempo_metrics_generator_registry_collections_total{component="metrics-generator", tenant="infra"}`:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/13304483/188593115-dcc7cf29-2afc-436e-88aa-5f56f875b314.png">

`rate(prometheus_remote_storage_sent_batch_duration_seconds_count{component="metrics-generator", tenant="infra"}[$__rate_interval])`:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/13304483/188592333-99ee6e81-d360-4875-a447-9569e1d6f295.png">

2. *No error/warning logs from metrics-generator at that time*

3. Tenant's config:
```yaml
infra:
    ingestion_rate_limit_bytes: 31457280
    ingestion_burst_size_bytes: 41943040
    max_traces_per_user: 50000
    metrics_generator_processors:
      - span-metrics
    block_retention: 168h
```
