### ISSUE TITLE
OOM when starting the Ingester

### ISSUE THREAD

**Issue by arielmoraes** [grafana/tempo#1825]
**Describe the bug**
If the WAL file is big when the ingester restarts, ie. by rolling out, the memory usage increases very fast going beyond the limits. Our conclusion is whenever the instance starts it tries to load all not flushed blocks into memory.

**To Reproduce**
Leave the ingester working for a few minutes receiving a lot of spans and then restart the instance.

**Expected behavior**
When starting the memory should be kept within the limit boundary.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm (distributed Tempo, last version)

Ingester metrics:
![image](https://user-images.githubusercontent.com/6741634/197221258-8a4e45fb-2cb0-453f-af27-088645e6a145.png)
That image shows spikes of 10-15 Gb, but we had even higher spikes of 30-40 Gb.

A workaround is to delete the WAL files.

Maybe that is related to the max size of each block, but the blocks shouldn't be loaded into memory on start.

**Comment by joe-elliott** [comment]
Thanks for reporting this issue! There are a lot of factors that would result in increased memory on startup. Can you share your config? Also, in the issue you say you are using the "last version". Can you clarify if that's 1.5.0 or tip of main?

**Comment by raphaelquati** [comment]
HI @joe-elliott , I work with @arielmoraes .

Yes, we are using Tempo version 1.5.0 (Helm chart version 0.26.8)

The config (after helm apply):

```yaml
compactor:
  compaction:
    block_retention: 168h
  ring:
    kvstore:
      store: memberlist
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    zipkin:
      endpoint: 0.0.0.0:9411
  ring:
    kvstore:
      store: memberlist
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 2
    tokens_file_path: /var/tempo/tokens.json
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
  - tempo-tempo-distributed-gossip-ring
metrics_generator:
  processor:
    service_graphs:
      dimensions: []
      histogram_buckets:
      - 0.1
      - 0.2
      - 0.4
      - 0.8
      - 1.6
      - 3.2
      - 6.4
      - 12.8
      max_items: 10000
      wait: 10s
      workers: 10
    span_metrics:
      dimensions: []
      histogram_buckets:
      - 0.002
      - 0.004
      - 0.008
      - 0.016
      - 0.032
      - 0.064
      - 0.128
      - 0.256
      - 0.512
      - 1.02
      - 2.05
      - 4.1
  registry:
    collection_interval: 15s
    external_labels: {}
    stale_duration: 15m
  ring:
    kvstore:
      store: memberlist
  storage:
    path: /var/tempo/wal
    remote_write:
    - url: https://<URL>/api/prom/push
    remote_write_flush_deadline: 1m
metrics_generator_enabled: true
multitenancy_enabled: false
overrides:
  max_bytes_per_trace: 30000000
  max_search_bytes_per_trace: 500000
  max_traces_per_user: 50000
  per_tenant_override_config: /conf/overrides.yaml
querier:
  frontend_worker:
    frontend_address: tempo-tempo-distributed-query-frontend-discovery:9095
    grpc_client_config:
      max_send_msg_size: 713928746
search_enabled: true
server:
  grpc_server_max_recv_msg_size: 713928746
  grpc_server_max_send_msg_size: 713928746
  http_listen_port: 3100
  log_format: logfmt
  log_level: info
storage:
  trace:
    azure:
      container-name: <containername>
      storage-account-key: <accountkey>
      storage-account-name: <accountname>
    backend: azure
    blocklist_poll: 5m
    cache: memcached
    local:
      path: /var/tempo/traces
    memcached:
      consistent_hash: true
      host: tempo-tempo-distributed-memcached
      service: memcached-client
      timeout: 500ms
    wal:
      path: /var/tempo/wal

```
