### ISSUE TITLE
Temp ingestion throttled for traces sent via http

### ISSUE THREAD

**Issue by ChrisSteinbach** [grafana/tempo#1835]
**Describe the bug**

Shipping traces from an OpenShift project using the grafana-agent to both a cluster-local and a remote Tempo deployment, we see throttling in the grafana-agent's log:

`caller=exporterhelper/queued_retry.go:215 msg="Exporting failed. Will retry the request after interval." component=traces traces_config=default kind=exporter data_type=traces name=otlphttp/1 error="Throttle (0s), error: error exporting items, request to http://<tempo-route-with-distributor-otlp-http-service>:80/v1/traces responded with HTTP Status Code 503" interval=6.271563799s`

While it is true that we are shipping a lot of traces, it is never more than 450 spans/s and **the exact same data is being shipped via gRCP to the local, identically configured cluster without any throttling**.

Here's what the grafana-agent config looks like:

```
              remote_write:
                - endpoint: "<tempo-distributor-svc>:4317"
                  insecure: true
                  protocol: grpc
                - endpoint: "http://<tempo-route-with-distributor-otlp-http-service>:80"
                  protocol: http
                  insecure: true
```

Here are the limits we have already attempted to increase (i.e. those passes to the distributor):

```
overrides:
  ingestion_burst_size_bytes: 200000000
  ingestion_rate_limit_bytes: 200000000
  max_bytes_per_trace: 300000000
  max_traces_per_user: 300000000
```

**To Reproduce**
1. Deploy two identical Tempo installations via the tempo-distributed helm chart version 0.26.5 on OpenShift
2. Configure one Tempo installation with a route to the distributor-otlp-http-service service
3. Configure one or more applications(s) to produce 400+ spans/s
4. Configure the grafana-agent to ship these traces via the gRCP endpoint to one Tempo installation and the HTTP endpoint to the other (see config above)
5. Observe the grafana-agent log(s) for Throttling messages

**Expected behavior**

Throttling will be reported in the grafana-agent log, but only for the http remote_write endpoint.

**Environment:**
 - Infrastructure: OpenShift 4.10
 - Deployment tool: helm

**Additional Context**
