### ISSUE TITLE
[Metrics generator] Ability to toggle off latency metrics entirely

### ISSUE THREAD

**Issue by AlexDHoffer** [grafana/tempo#2013]
**Is your feature request related to a problem? Please describe.**

We have lots of instrumentation in our stack but like the metrics-generator for getting request rates for specific endpoints with added dimensionality. However, we don't have much interest in the latency metrics. But, because we have such high traffic and high metric flows, the latency metrics add an intense degree of cardinality that can tank our remote write instance. 

One can disable most of the buckets (it still leaves +Inf and 0 buckets) by setting the histograms to [null]. But I'd like to turn them off entirely to make administration of this tool in a high volume environment simpler.

This, for example, is not ideal when I don't care about latency metrics:

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/19369483/214374208-7dca5f79-6336-40e3-b091-2c4ab32053f1.png">

**Describe the solution you'd like**

Turn off latency histograms but keep request rate data.

**Describe alternatives you've considered**

Setting buckets to [null] allows you to reduce the latency cardinality, but not remove it.

**Comment by joe-elliott** [comment]
This is a good idea. Currently we have `service-graphs` and `span-metrics` as processor options. Splitting `span-metrics` into two options makes sense. Maybe:

```
metrics_generator_processors:
- span-metrics-counts
- span-metrics-latency
- service-graphs
```

Then if the config only specifies `span-metrics` it enables both of them?

**Comment by AlexDHoffer** [comment]
@joe-elliott That would make sense to me. It probably bears mentioning to anybody that comes to this issue you can work around this by configuring your remote write to discard the samples before they reach your Prometheus, e.g.:

````
        - url: 'http://remotewrite-prometheus-internal-server-1.remotewrite-prometheus-internal-server-headless.monitoring.svc.cluster.local:9090/api/v1/write'
          name: remotewrite-internal-1
          write_relabel_configs:
            - source_labels: [__name__]
              regex: 'traces_spanmetrics_latency_bucket'
              action: drop
````

But it would still be nice to reduce the load on the generator itself.
