### ISSUE TITLE
Max retries exceeded with url: /v1/traces SSLError

### ISSUE THREAD

**Issue by markuman** [grafana/tempo#2018]
**Describe the bug**

Our python fastapi client is sending it's telemetry data over https to tempo

```
opentelemetry-distro = "^0.36b0"
opentelemetry-exporter-otlp = "^1.15.0"
opentelemetry-instrumentation-fastapi = "^0.36b0"
```
**tempo.yml**

```yml
distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: tempo.xxx.de:4318
          tls:
            cert_file: /etc/ssl/tempo.xxx.de.crt
            key_file: /etc/ssl/tempo.xxx.de.key
        grpc:
          endpoint: tempo.xxx.de:4319
          tls:
            cert_file: /etc/ssl/tempo.xxx.de.crt
            key_file: /etc/ssl/tempo.xxx.de.key
```

Sometimes a day we see now

```
HTTPSConnectionPool(host='tempo.xxx.de', port=4318): Max retries exceeded with url: /v1/traces (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2633)')))
```

**To Reproduce**

No idea

**Expected behavior**

No SSL error all the time

**Environment:**
 - Infrastructure: baremetal/ubuntu 22.04
 - Deployment tool: ansible
 - 
**Additional Context**

**Comment by markuman** [comment]
Maybe I've found a related tempo error in syslog now

> Jan 25 12:27:03 somehost tempo[66459]: level=info ts=2023-01-25T12:27:03.40438227Z caller=trace.go:83 msg="size of search data exceeded max search bytes limit" maxSearchBytes=5000 discardedBytes=7056

But I'm not sure if this is related. because it matches the timestamp

> January 25, 2023 at 12:27:03 PM GMT+1

---

> SSLError requests.adapters in send
> 
> HTTPSConnectionPool(host='tempo.xxx.de', port=4318): Max retries exceeded with url: /v1/traces (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2633)')))

**Comment by joe-elliott** [comment]
I'm honestly unsure where that error is coming from. We use the OTLP receivers and I'd believe this error is either in that codebase or the go tcp/ssl/http2/grpc stack.

> Jan 25 12:27:03 somehost tempo[66459]: level=info ts=2023-01-25T12:27:03.40438227Z caller=trace.go:83 msg="size of search data exceeded max search bytes limit" maxSearchBytes=5000 discardedBytes=7056

This is unrelated. It's an error that is logged when the size of a search tags or tag values exceeds a configured maximum.

Are you pushing from your application(s) directly to Tempo? I would recommend trying the Grafana Agent or the OTEL collector to set up a trace pipeline. It will buffer and retry traces if there are errors.

**Comment by markuman** [comment]
@joe-elliott 

> Are you pushing from your application(s) directly to Tempo? I would recommend trying the Grafana Agent or the OTEL collector to set up a trace pipeline. It will buffer and retry traces if there are errors.

The application is pushing directly to tempo.

> I'm honestly unsure where that error is coming from. We use the OTLP receivers and I'd believe this error is either in that codebase or the go tcp/ssl/http2/grpc stack.

the `http` endpoint is used, not the `grpc`.  

I've change the setup and let nginx do the SSL

**nginx**
```
server {

    listen 4318 ssl;
    server_name tempo.xxx.de;
    ssl_certificate           /etc/ssl/xx.de.crt;
    ssl_certificate_key       /etc/ssl/xxx.de.key;
    access_log            /var/log/nginx/otlp.access.log;
    location / {

      proxy_pass http://localhost:4320;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   }
}
```

**tempo**
```yml
distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: localhost:4320
          # tls:
          #   cert_file: /etc/ssl/tempo.xxx.de.crt
          #   key_file: /etc/ssl/tempo.xxx.de.key
        grpc:
          endpoint: tempo.xxx.de:4319
          tls:
            cert_file: /etc/ssl/tempo.xxx.de.crt
            key_file: /etc/ssl/tempo.xxx.de.key

```

However, the error looks the same, but nginx sees only a 200 status code

```
10.115.3.191 - - [26/Jan/2023:08:45:10 +0000] "POST /v1/traces HTTP/1.1" 200 0 "-" "OTel OTLP Exporter Python/1.15.0"
10.115.3.191 - - [26/Jan/2023:08:45:10 +0000] "POST /v1/traces HTTP/1.1" 200 0 "-" "OTel OTLP Exporter Python/1.15.0"
```

```
HTTPSConnectionPool(host='tempo.xxx.de', port=4318): Max retries exceeded with url: /v1/traces (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2633)')))
```

**Comment by thomaschaaf** [comment]
for us it was actually that the otel http sdks did not work with the current version of tempo v1. (https://github.com/grafana/tempo/issues/1746)

**Comment by joe-elliott** [comment]
thx @thomaschaaf. if this is the issue then it should be fixed in 2.0. @markuman are you able to test this? 2.0rc-0 images exist here:

https://hub.docker.com/layers/grafana/tempo/2.0.0-rc.0/images/sha256-05add2afe5cfebd8f4a8b6a1efab51bdbbb3c13eaa5a23740fd76571c060a110?context=explore

**Comment by markuman** [comment]
Sure, I'll try it nextweek and will provide a feedback.

**Comment by markuman** [comment]
So we're on tempo 2.0 for 3 days. But it changes nothing. The error image is the same.

```
              - name: OTEL_RESOURCE_ATTRIBUTES
                value: "service.name=pyapi_{{ APP_ENV }}"
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: https://tempo.xxx.de:4318
              - name: OTEL_EXPORTER_OTLP_PROTOCOL
                value: http/protobuf
              - name: OTEL_METRICS_EXPORTER
                value: "none"
              - name: BOTO_DISABLE_COMMONNAME
                value: "true"
              - name: START_CMD
                value: gunicorn
              - name: OTEL_EXPORTER_OTLP_TIMEOUT
                value: "30000"
              - name: OTEL_EXPORTER_OTLP_TRACES_TIMEOUT
                value: "30000"
              - name: OTEL_EXPORTER_OTLP_METRICS_TIMEOUT
                value: "30000"
              - name: OTEL_EXPORTER_OTLP_LOGS_TIMEOUT
                value: "30000"

```

But also 

```
OTEL_EXPORTER_OTLP_ENDPOINT: tempo.xxx.de:4319
OTEL_EXPORTER_OTLP_PROTOCOL: grpc
```

does not change anything

**Comment by zalegrala** [comment]
Skipping over the nginx bit above and thinking just about Tempo listening on TLS, you could verify TLS on the server side using the `openssl` command, something like the following should indicate that TLS negotiation has succeeded.
```
openssl s_client -connect tempo.trace.svc.cluster.example:9095
```

I have success with a config like the following, similar to what was posted above.

```
server:
    grpc_tls_config:
        cert_file: /tls/tls.crt
        key_file: /tls/tls.key
        client_auth_type: VerifyClientCertIfGiven
        client_ca_file: /tls/ca.crt
distributor:
    receivers:
        jaeger:
            protocols:
                grpc:
                    tls:
                        ca_file: /tls/ca.crt
                        cert_file: /tls/tls.crt
                        key_file: /tls/tls.key
                thrift_http: null
        otlp:
            protocols:
                grpc: null
```

Note that my clients are pushing traces using GRPC, not HTTP, and so I don't enable TLS on the HTTP endpoint because I want Prometheus to scrape in HTTP.

We had to make an update to the vulture in order for it to negotiate in TLS as well.  I assume the same is try for the Python client.

https://github.com/grafana/tempo/blob/main/cmd/tempo-vulture/main.go#L287-L292

Given that we see the `ssl.c` error above, I'm wondering, what does the client configuration for Python look like to enable TLS?

**Comment by markuman** [comment]
@zalegrala yes. that works fine

```
openssl s_client -connect tempo.xxx.de:443
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = *.xxx.de
verify return:1
---
Certificate chain
 0 s:CN = *.xxx.de
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 20 18:42:51 2023 GMT; NotAfter: Apr 20 18:42:50 2023 GMT
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 20 19:14:03 2021 GMT; NotAfter: Sep 30 18:14:03 2024 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGHTCCBQWgAwIBAgISA79aRGtefYsXkSpSDscClVJLMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMzAxMjAxODQyNTFaFw0yMzA0MjAxODQyNTBaMBYxFDASBgNVBAMM
CyoubGVra2VyLmRlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAmTt7
YxYlAE/0KVZdX7Ui2fD+s9FfnrCXMF2YXWw/M46LzKLS1uH9LbPFSk5wjZEIX3MP
bjLRSZVPNbthuVi/qNJOWUgbR+TWA0Xz8sGqJq39cflLtPR2GyTJDwf1G6UL3rRn
sGOJsEtpSzl2aYrZ1ifZI0oED+JBtz9gogZzL6wi10BYUI/vaeznEJ3e7DpALl88
cw9JqRwDoCNETtTSzMhwGxA1Tn01SSxmYD+vbW4IM8dqGjpOCZEbqfMk32gW8ryR
ujUwWVLVDIdn5rTgYbsMTbBNZkdL2a4rF3oZtUJy2EMg97PsHyYY5hG4qUtoageA
5USSRan88SQUKC5zza4/YaZ50QeYxsqu5DxJpnP7UIvpJuqtsRpQboLO58pVVt1x
4jJuTyIsZ8A+3MCpQoStP98P46P6v/t4frRae2Ny51lycVV01Jz926+GUX/G3aUl
Qmu4qHUcw3W5PD0ODjBVBPiRgL57BkbcaRDGRFf8qyoz5KtG4emb2Bu3ofSkZRDS
O2tj1N/uxYsCAZioDJhRdV4kF0bPX7i/GMiVs12/tGFwFpd3ACu2NqJvCSlVUouJ
LnJIf/y292+oJKH1sZeigozWKeg7aS4wiCFNHPJjZ9jNTzImLVwsJ0i4CXU2LeEI
A4l4K3aXUFjvQGAOW5QuTOpItkw6a1+owQ+4GlsCAwEAAaOCAkcwggJDMA4GA1Ud
DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
AQH/BAIwADAdBgNVHQ4EFgQUJPw3S0rl4VnHloNDbhc38VvlWaswHwYDVR0jBBgw
FoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUF
BzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9y
My5pLmxlbmNyLm9yZy8wFgYDVR0RBA8wDYILKi5sZWtrZXIuZGUwTAYDVR0gBEUw
QzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDov
L2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdgB6
MoxU2LcttiDqOOBSHumEFnAyE4VNO9IrwTpXo1LrUgAAAYXQtI5MAAAEAwBHMEUC
IQDaMacSpA0y0rUO+GNaO0wJBoGRsMsumnRcFLp/hfcWjwIgT3i1+5FOnTTsARV+
25C3hTgp9WOk11s/6OVe3Wu32tkAdwC3Pvsk35xNunXyOcW6WPRsXfxCz3qfNcSe
HQmBJe20mQAAAYXQtI46AAAEAwBIMEYCIQDtGo1fSgai/C+lzc3FiRsjJjCeXcf1
OINurUYzWxzsWgIhAJwZzoeiKLqlmmWSifnz3FxLBJDTMFbGm6ABMjtWjy38MA0G
CSqGSIb3DQEBCwUAA4IBAQAZ83km2pK2ev5H1vAJhUZkeY1NVxdw3xFrDiKspUMt
/B664Zr0wo7kH4xPB13TNikbDCYgfonLvJ2YM/DHfOMIFHDvcXgvP4dFXVdl6KhS
+YEPJXjRLPQ3aslbbSBdKR6ZH9HFkxDtv+Eh9/kbXV8X+HF0nKroV6HUMOmWTdi9
sAJ25yUDcjJpAi4Z3KGUK8LMsN3ECO+W19562x35wLT0IIS99bW/xR59r+t9lEqo
Hzf78hFzS6osM1bT3V6G3W9k/bgoV6SIrvPA3C9BZrTkgCi5Ntug8jU12m1uwkt3
KgkGIEcNdLE8S/lXvmIM9rEYNI2+MUUAmoSLDZBkiSPu
-----END CERTIFICATE-----
subject=CN = *.xxx.de
issuer=C = US, O = Let's Encrypt, CN = R3
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 5077 bytes and written 397 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: CBD444824B5E47E5BEFF0291977617FD6F46255FD0F360BEAEBCF905564BC711
    Session-ID-ctx: 
    Resumption PSK: B12ED38BF761F142783E44037548A0C5611DCD6927EE19D38841E570582B70FFD1239943C1283F1510DC65DC3EEA82C1
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 604800 (seconds)
    TLS session ticket:
    0000 - b0 35 6a c9 cf 53 22 bc-61 b2 a3 96 58 8b df fd   .5j..S".a...X...
    0010 - 90 55 9a 19 f6 8d d3 c0-c8 f3 d6 07 11 58 ad 3a   .U...........X.:
    0020 - 25 e7 ef 51 90 92 ef 4e-4e bf bd 90 27 67 48 9f   %..Q...NN...'gH.
    0030 - b6 39 22 de e4 64 e0 d8-49 db 9e 17 25 ad 97 b3   .9"..d..I...%...
    0040 - 64 2d f8 8b c1 59 49 e1-57 bc c5 ef 56 2e d3 2f   d-...YI.W...V../
    0050 - f2 d3 7a 7e 3c 72 2e f9-3d 4b 2e b2 ea f2 d8 e1   ..z~<r..=K......
    0060 - a2 8c eb 8f 97 22 53 62-d8 6f 74 61 f7 04 21 c7   ....."Sb.ota..!.
    0070 - af 0d d4 ad ae c8 47 95-8d 9e 76 38 11 de 68 93   ......G...v8..h.
    0080 - 45                                                E

    Start Time: 1676056966
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK


```

So TL;DR

> Sometimes a day we see in sentry 
>  `HTTPSConnectionPool(host='tempo.xxx.de', port=4318): Max retries exceeded with url: /v1/traces (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2633)')))`

And we see this on both, OTLP https and grpc tls.  
All in all, it is working, but the frequented errors are annoying.

**Comment by zalegrala** [comment]
Reviewing the above after the stalebot mention, I'm unsure the current setup.  If the client is connecting to nginx and receiving the error, then I would expect the issue to exist between the client and nginx.  In the openssl command above, the connection is made to :443, but I don't see in the config what is listening on :443.  Did I miss it?

**Comment by markuman** [comment]
@zalegrala

>  but I don't see in the config what is listening on :443. Did I miss it?

I think it was the nginx config, that talks to localhost 4318.  
And the errors picture was the same, so it doesn't  matter if nginx or tempo make the TLS...


however, after upgrading to tempo 2.0.1 using

```yml
distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: localhost:4320
        grpc:
          endpoint: tempo.xxx.de:4319
          tls:
            cert_file: /etc/ssl/tempo.xxx.de.crt
            key_file: /etc/ssl/tempo.xxx.de.key

```

using 

```
  OTEL_EXPORTER_OTLP_ENDPOINT: tempo.lekker.de:4319
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
```

in the python app, the errors are gone.
