### ISSUE TITLE
[Metrics generator] Constant chatter about duplicate samples for timestamps

### ISSUE THREAD

**Issue by AlexDHoffer** [grafana/tempo#2024]
**Describe the bug**

My metrics-generator instance reports constant duplicate samples when writing to a Prometheus remote write receiver. This is a common experience when self-hosting a remote write receiver and the user having misconfigured it. However, I think I've addressed the usual causes, so unless I'm missing something I still appear to be getting duplicate series in the generator. 

**To Reproduce**

1. Tempo is run in Kubernetes on version 1.5.0. Spans are written to the Distributor in OTel format.
2. A Prometheus statefulset is run on the same cluster. There are two instances. The remote write receiver is enabled on both. Both have a unique label to distinguish themselves: statefulset.kubernetes.io/pod-name=remotewrite-prometheus-internal-server-[n]
3. The Generator remote_writes to both using the following config (note the special label it uses unique to each instance):

````
config:
    registry:
      external_labels:
        job: "metrics-generator"
    storage:
      remote_write:
        - url: 'http://remotewrite-prometheus-internal-server-0.remotewrite-prometheus-internal-server-headless.monitoring.svc.cluster.local:9090/api/v1/write'
          name: remotewrite-internal-0
          write_relabel_configs:
            - source_labels: [__name__]
              regex: 'traces_spanmetrics_latency_bucket'
              action: drop
            - regex: 'span_kind'
              action: labeldrop
            - regex: 'status_code'
              action: labeldrop
            - target_label: 'prometheus_instance'
              replacement: 'remotewrite-prometheus-internal-server-0'
        - url: 'http://remotewrite-prometheus-internal-server-1.remotewrite-prometheus-internal-server-headless.monitoring.svc.cluster.local:9090/api/v1/write'
          name: remotewrite-internal-1
          write_relabel_configs:
            - source_labels: [__name__]
              regex: 'traces_spanmetrics_latency_bucket'
              action: drop
            - regex: 'span_kind'
              action: labeldrop
            - regex: 'status_code'
              action: labeldrop
            - target_label: 'prometheus_instance'
              replacement: 'remotewrite-prometheus-internal-server-1'
````

This generates constant logging:

````
ts=2023-01-27T19:16:17.467904722Z caller=dedupe.go:112 tenant=single-tenant component=remote level=error remote_name=remotewrite-internal-1 url=http://remotewrite-prometheus-internal-server-1.remotewrite-prometheus-internal-server-headless.monitoring.svc.cluster.local:9090/api/v1/write msg="non-recoverable error" count=465 exemplarCount=0 err="server returned HTTP status 400 Bad Request: duplicate sample for timestamp"

ts=2023-01-27T19:16:18.018627323Z caller=dedupe.go:112 tenant=single-tenant component=remote level=error remote_name=remotewrite-internal-0 url=http://remotewrite-prometheus-internal-server-0.remotewrite-prometheus-internal-server-headless.monitoring.svc.cluster.local:9090/api/v1/write msg="non-recoverable error" count=465 exemplarCount=0 err="server returned HTTP status 400 Bad Request: duplicate sample for timestamp"
level=info ts=2023-01-27T19:16:26.806019261Z caller=registry.go:214 tenant=single-tenant msg="collecting metrics" active_series=210605
````

**Expected behavior**

No duplicate samples based on timestamp. Or, some duplicate samples expected if there were a WAL replay occurring in the event of the service restarting.

**Environment:**
 - Infrastructure: Azure Kubernetes 1.22.11
 - Deployment tool: helm, tempo-distributed chart

**Additional Context**

I have 5 dimensions being added to the span_metrics

**Comment by joe-elliott** [comment]
I'm wondering if removing `span_kind` and `status_code` in your relabel configs is causing it to send duplicate metrics. The span_metrics processor can be configured to not send these dimensions. Let's try that and see if your issue goes away:

I believe it's:
```
metrics_generator:
  processor:
    span_metrics:
      intrinsic_dimensions:
        status_code: false
        span_kind: false
```
