### ISSUE TITLE
"Trace to metrics" missing from tempo data source in Grafana

### ISSUE THREAD

**Issue by kroksys** [grafana/tempo#2101]
I cant find configuration for "Trace to metrics" in Grafana Tempo data souce.
<img width="828" alt="Screenshot 2023-02-10 at 12 50 34" src="https://user-images.githubusercontent.com/15876796/218077182-5cff10e3-2da8-4dbd-8c90-aa28358bc415.png">

I'm using latest images for tempo and grafana using docker-compose. I see that this option is shown in this video: [https://www.youtube.com/watch?v=TkapvLeMMpc](https://www.youtube.com/watch?v=TkapvLeMMpc)

I even enabled **feature_toggles - traceToMetrics** in Grafana, but that didn't help either.

**Comment by joe-elliott** [comment]
Can you report your Grafana version? (Tempo version doesn't really matter for this).

**Comment by joe-elliott** [comment]
Also, can you check your `admin/settings` page? it will show all the feature flags it considers toggled. Let's make sure that `traceToMetrics` is on.

**Comment by kroksys** [comment]
I was using docker image `grafana/grafana:latest` but I specified it to `grafana/grafana:9.3.6` and have the same result.
Couldn't see the settings page until turned off anonymous user:
 ```
version: '3.8'
services:
 # ......
 grafana:
    image: grafana/grafana:9.3.6
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
```

What should I look for in that page?
