### ISSUE TITLE
Compactor OOM With Parquet

### ISSUE THREAD

**Issue by sherifkayad** [grafana/tempo#2162]
**Describe the bug**

After switching to Parquet (and using Tempo 2.0.0) the Compactor is consistently being killed due to out of memory no matter how much memory it gets as limit (currently I am using 2Gi as memory limit and tried increasing to even 10Gi).

The compactor produces logs as follows and then crashes with OOM Killed
```
level=info ts=2023-03-03T00:17:02.749349082Z caller=compactor.go:144 msg="beginning compaction" traceID=74ce1e9630c2d0cc
level=info ts=2023-03-03T00:17:02.749400303Z caller=compactor.go:156 msg="compacting block" block="&{Version:vParquet BlockID:b83777cc-aba5-4073-b7ef-d82f68ccc9df MinID:[0 0 0 0 0 0 0 0 0 0 61 166 55 147 30 61] MaxID:[0 0 0 0 0 0 0 0 255 255 172 88 192 116 109 247] TenantID:single-tenant StartTime:2023-03-03 00:02:32 +0000 UTC EndTime:2023-03-03 00:02:43 +0000 UTC TotalObjects:6093 Size:5435955 CompactionLevel:0 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:1 FooterSize:6259}"
level=info ts=2023-03-03T00:17:02.798054897Z caller=compactor.go:156 msg="compacting block" block="&{Version:vParquet BlockID:c837c052-23ce-4d9c-8bca-c028edbe0499 MinID:[0 0 0 0 0 0 0 0 0 0 24 173 105 96 32 196] MaxID:[0 0 0 0 0 0 0 0 255 246 222 233 162 21 160 8] TenantID:single-tenant StartTime:2023-03-03 00:02:42 +0000 UTC EndTime:2023-03-03 00:02:52 +0000 UTC TotalObjects:6148 Size:5412819 CompactionLevel:0 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:1 FooterSize:6259}"
level=info ts=2023-03-03T00:17:02.824263888Z caller=compactor.go:156 msg="compacting block" block="&{Version:vParquet BlockID:49de4ce3-082b-4cf0-ab3e-da313643b15d MinID:[0 0 0 0 0 0 0 0 0 17 129 211 38 47 17 72] MaxID:[0 0 0 0 0 0 0 0 255 251 153 153 244 226 179 174] TenantID:single-tenant StartTime:2023-03-03 00:10:22 +0000 UTC EndTime:2023-03-03 00:10:32 +0000 UTC TotalObjects:6189 Size:5341702 CompactionLevel:0 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:1 FooterSize:6259}"
level=info ts=2023-03-03T00:17:02.839158683Z caller=compactor.go:156 msg="compacting block" block="&{Version:vParquet BlockID:1995b431-4d61-4abe-be03-69849c5d9790 MinID:[0 0 0 0 0 0 0 0 0 18 44 7 229 216 178 239] MaxID:[0 0 0 0 0 0 0 0 255 237 158 124 140 178 130 156] TenantID:single-tenant StartTime:2023-03-03 00:00:32 +0000 UTC EndTime:2023-03-03 00:00:43 +0000 UTC TotalObjects:6279 Size:5629672 CompactionLevel:0 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:1 FooterSize:6259}"
level=info ts=2023-03-03T00:17:05.831410254Z caller=poller.go:191 msg="writing tenant index" tenant=single-tenant metas=2910 compactedMetas=0
```

**To Reproduce**
1. Start Tempo (2.0.0)
2. Add some traces
3. Watch the compactor

**Expected behavior**

The compactor shouldn't crash

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm (tempo-distributed)

**Additional Context**
Current Tempo Config:
```yaml
compactor:
  compaction:
    block_retention: 336h
    compacted_block_retention: 1h
    compaction_cycle: 300s
    compaction_window: 1h
    max_block_bytes: 107374182400
    max_compaction_objects: 6000000
    max_time_per_tenant: 5m
    retention_concurrency: 10
    v2_in_buffer_bytes: 5242880
    v2_out_buffer_bytes: 31457280
    v2_prefetch_traces_count: 1000
  ring:
    kvstore:
      store: memberlist
distributor:
  receivers:
    zipkin:
      endpoint: 0.0.0.0:9411
  ring:
    kvstore:
      store: memberlist
ingester:
  complete_block_timeout: 15m
  flush_check_period: 10s
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    tokens_file_path: /var/tempo/tokens.json
  max_block_bytes: 5242880
  max_block_duration: 30m
  trace_idle_period: 10s
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
  - tempo-gossip-ring
metrics_generator:
  processor:
    service_graphs:
      dimensions:
      - span.region
      - span.cluster
      - namespace
      - app
      - service
      histogram_buckets:
      - 0.1
      - 0.2
      - 0.4
      - 0.8
      - 1.6
      - 3.2
      - 6.4
      - 12.8
      max_items: 100000
      wait: 300s
      workers: 10
    span_metrics:
      dimensions:
      - span.region
      - span.cluster
      - namespace
      - app
      - service
      histogram_buckets:
      - 0.002
      - 0.004
      - 0.008
      - 0.016
      - 0.032
      - 0.064
      - 0.128
      - 0.256
      - 0.512
      - 1.02
      - 2.05
      - 4.1
  registry:
    collection_interval: 15s
    external_labels: {}
    stale_duration: 15m
  ring:
    kvstore:
      store: memberlist
  storage:
    path: /var/tempo/wal
    remote_write:
    - send_exemplars: true
      url: http://kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
    remote_write_flush_deadline: 1m
    wal: null
multitenancy_enabled: false
overrides:
  max_bytes_per_trace: 500000000
  max_search_bytes_per_trace: 500000
  max_traces_per_user: 1000000
  metrics_generator_processors:
  - service-graphs
  - span-metrics
  per_tenant_override_config: /conf/overrides.yaml
querier:
  frontend_worker:
    frontend_address: tempo-query-frontend-discovery:9095
  max_concurrent_queries: 100
  search:
    external_endpoints: []
    external_hedge_requests_at: 0
    external_hedge_requests_up_to: 2
    prefer_self: 10
    query_timeout: 60s
query_frontend:
  search:
    concurrent_jobs: 2000
    target_bytes_per_job: 400000000
server:
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 3100
  log_format: logfmt
  log_level: info
storage:
  trace:
    backend: s3
    blocklist_poll: 5m
    local:
      path: /var/tempo/traces
    s3:
      bucket: MY-TRACES-BUCKET
      endpoint: s3.eu-central-1.amazonaws.com
      hedge_requests_at: 1s
      hedge_requests_up_to: 2
    wal:
      path: /var/tempo/wal
```

**Additional Note**
Prior to switching to Parquet and with the exact same configs for the `v2` storage format everything was working fine .. so I am going crazy what's now the problem with the Parquet storage format.

Is it maybe related to me allowing a bigger value for `max_bytes_per_trace`? .. If so, then why was it fine with the `v2` format?
