### ISSUE TITLE
RATE_LIMITED error with per-tenant override

### ISSUE THREAD

**Issue by mecseid** [grafana/tempo#2194]
**Describe the bug**
When I install Tempo 2.0.1 with the provided Helm chart, and set a per-tenant (actually wildcard) override, then I get the following error:
```
level=error ts=2023-03-10T14:01:55.499662175Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="rpc error: code = ResourceExhausted desc = RATE_LIMITED: ingestion rate limit (0 bytes) exceeded while adding 397 bytes"
```

**To Reproduce**
1. Install Helm version 1.0.2 (that installs Tempo 2.0.1) with an overrides setting, like:
```yaml
tempo:
  metricsGenerator:
    enabled: true
  overrides:
    "*":
      metrics_generator_processor_service_graphs_dimensions:
        - 'environment.name'
      metrics_generator_processor_span_metrics_dimensions:
        - 'environment.name'
```
2. Send a trace to Tempo via Zipkin endpoint
3. Tempo write the error and do not save the trace

**Expected behavior**
Tempo should save the trace and respect the global settings for `ingestion_burst_size_bytes` and `ingestion_rate_limit_bytes` when those are not overwritten in the per-tenant section.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Workaround:**
Add these two lines under the wildcard per-tenant settings:
```yaml
# These are the default options
ingestion_burst_size_bytes: 20000000
ingestion_rate_limit_bytes: 15000000
```

**Comment by mecseid** [comment]
A quick update:
Looks like the per-tenant configuration does not respect global settings, because the metrics-generator-related settings didn't work either.

Am I doing something wrong (don't use the Helm chart as expected), is the Helm chart needs some improvement (the user can able to set metrics_generator related settings), or the overrides section does not work as expected?

My generated YAML files:
overrides.yaml:
```yaml
    overrides:
      '*':
        # If these 2 missing, then I get RATE_LIMITED errors
        ingestion_burst_size_bytes: 20000000
        ingestion_rate_limit_bytes: 15000000
        metrics_generator_processor_service_graphs_dimensions:
        - environment.name
        metrics_generator_processor_span_metrics_dimensions:
        - environment.name
        # If these missing, then the metrics generator doesn't do anything
        metrics_generator_processors:
        - service-graphs
        - span-metrics
```

tempo.yaml:
```yaml
    multitenancy_enabled: false
    usage_report:
      reporting_enabled: true
    compactor:
      compaction:
        block_retention: 744h
    distributor:
      receivers:
            zipkin:
              endpoint: 0.0.0.0:9411
    ingester:
          {}
    server:
          http_listen_port: 3100
    storage:
          trace:
            backend: local
            local:
              path: /var/tempo/traces
            wal:
              path: /var/tempo/wal
    querier:
          {}
    query_frontend:
          {}
    overrides:
          per_tenant_override_config: /conf/overrides.yaml
          metrics_generator_processors:
          - 'service-graphs'
          - 'span-metrics'
    metrics_generator:
          storage:
            path: "/tmp/tempo"
            remote_write:
              - url: http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090/api/v1/write
```
