### ISSUE TITLE
Recieving a 403 on GCS Bucket, with valid Service Account Key

### ISSUE THREAD

**Issue by Allure996** [grafana/tempo#2206]
**Describe the bug**
I'm using tempo-distributed Helm Chart, setting `storage.trace.backend` to `gcs` and providing an existing bucket name on GCP.
I set up the environment variable `GOOGLE_APPLICATION_CREDENTIALS` for each service of Tempo and mounted the service account as a json file, which is correctly recognized by the services.

On bootstrap, each service crashes with the error 

```
 level=error ts=<TIMESTAMP> caller=main.go:117 msg="error running Tempo" err="failed to init module services error initialising module: store: failed to create store getting bucket attrs: googleapi: Error 403: <SERVICEACCOUNT_MAIL> does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist)., forbidden"
```

Firstly, I thought that the SA has not the requested IAM Permissions, double checking it I saw it was Storage Object Admin on that bucket.
I also used the same SA with tools as `gsutil` or `gcloud` to make operations onto that bucket and everything works as expected.

**To Reproduce**
1. Configure the bucket in the config section
```
config: |
...
   storage:
        trace:
          backend: gcs
          gcs:
            bucket_name: <bucket_name>
```
2. Configure GOOGLE_APPLICATION_CREDENTIALS in every service of the Chart (substitute <service_name> with `ingester`, `distributor`, `compactor`...)
```
<service_name>:
    extraEnv: &extraEnv_credentials
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/secrets/key.json
    extraVolumes:
    - &extraVolumes_credentials
      name: tempo-access-gcs
      secret:
        secretName: tempo-access-gcs
    extraVolumeMounts:
      - &extraVolumeMounts_credentials
        name: tempo-access-gcs
        mountPath: /etc/secrets
```

**Expected behavior**
The Helm Chart is correctly installed and the services are up and running and connected to the bucket

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm Chart `grafana/tempo-distributed`
