### ISSUE TITLE
tempo compactor reading storage container error

### ISSUE THREAD

**Issue by suxiaoxiaomm** [grafana/tempo#2215]
Hi Experts,

We are using Azure blob as our tempo storage.

Currently we are experiencing tempo compactor keeps reporting error:
```
level=error ts=2023-03-16T04:20:51.990648343Z caller=tempodb.go:441 msg="failed to poll blocklist. using previously polled lists" err="reading storage container: Head \"https://xxxxxx.blob.core.windows.net/xxxxxxxxxxxxxxxxxxxx/meta.compacted.json?timeout=61\": read tcp xxxxx->xxxxxx: read: connection reset by peer"
level=error ts=2023-03-16T04:25:53.505014898Z caller=tempodb.go:441 msg="failed to poll blocklist. using previously polled lists" err="reading storage container: Head \"https://xxxxxx.blob.core.windows.net/xxxxxxxxxxxxxxxxxxxx//meta.json?timeout=61\": read tcp xxxxxx->xxxxxx: read: connection reset by peer"
...
```

This error message shows every 5mins, looks like not a random issue as 5min is exactly a default poll interval.

I am sure the connection string to Azure blob is correct as Tempo ingester and querier are using the exactly same connection string. They seems working fine.

And in the meanwhile, above issue seems will cause the issue that we cannot query traces from grafana frontend.

Your help and suggestion are highly appriciated!

Thanks a lot!

**Comment by suxiaoxiaomm** [comment]
I just noticed there are error logs from Tempo querier as below:


`level=error ts=2023-02-18T15:56:24.154102011Z caller=poller.go:179 msg="failed to pull bucket index for tenant. falling back to polling" tenant=single-tenant err="reading storage container: Head \"https://xxxx/index.json.gz?timeout=61\": net/http: TLS handshake timeout"`


Maybe this is the cause that we cannot use grafana frontend for query traces?

**Comment by joe-elliott** [comment]
We have also seen strange Azure blob storage behavior as well. Can you try the settings recommended here:

https://grafana.com/docs/tempo/latest/configuration/azure/#azure-blocklist-polling

There is also a very long discussion here about how to handle these issues:

https://github.com/grafana/tempo/issues/1462

@electron0zero and @zalegrala, I actually don't know the current recommended best practices for Azure DNS. Do we recommend an `ndots` change or something else? If either of you know can you PR an update to the linked Azure docs?

**Comment by suxiaoxiaomm** [comment]
@joe-elliott Thank you for the quick response.
Yes, I did try below settings, but no help.
```
  storage:
    trace:
      blocklist_poll_tenant_index_builders: 1
      blocklist_poll_jitter_ms: 500
```

**Comment by electron0zero** [comment]
@joe-elliott currently we are setting `ndots` to `3`, and NOT setting `blocklist_poll_jitter_ms` in our azure clusters, see https://github.com/grafana/tempo/issues/1462#issuecomment-1234064916 for details on how to configure it at pod level.

@suxiaoxiaomm can you try this in your compactor pods, and report back.


here is what our compactor's storage section looks like:

```yaml
storage:
        trace:
            azure:
                container_name: <bucket-name>
            backend: azure
            block:
                version: vParquet
            blocklist_poll: 5m
            blocklist_poll_tenant_index_builders: 1
            cache: memcached
            memcached:
                consistent_hash: true
                host: memcached
                service: memcached-client
                timeout: 200ms
            pool:
                queue_depth: 2000
            wal:
                path: /var/tempo/wal
```

and here is what our compactor dnsConfig looks like:

```yaml
      dnsConfig:
        options:
        - name: ndots
          value: "3"

```

with these settings I see 23 instances of this error in last 24 hours, across 3 azure clusters.
