### ISSUE TITLE
Metrics generator dimension not working for some trace attributes

### ISSUE THREAD

**Issue by gballigand** [grafana/tempo#2257]
The metrics generated from span metrics doesn't contains some of my configured dimensions. 

## To reproduce : 
In a .Net C# project:
1. Generate activities with .Net libraries and collect it with OpenTelemetry
2. Send metrics to tempo using an otlpExporter from OpenTelemetry 
3. Configure tempo metrics generator as following :
```YAML
metrics_generator:
  storage:
      path: /tmp/tempo/generator/wal
      remote_write: 
        - url: http://prometheus:9090/api/v1/write
          send_exemplars: true
overrides:
  metrics_generator_max_active_series: 10000
  metrics_generator_collection_interval: 60s
  metrics_generator_processors: ['span-metrics']
  metrics_generator_processor_span_metrics_dimensions: ['actor.type', 'otel.library.name']
```
5. Use Grafana with configured tempo and prometheus data sources to explore the results

### Tempo : 
In my tempo I can see my traces containing my actor.type and otel.library.name attributes.
![span](https://user-images.githubusercontent.com/34373406/227501793-f2706d21-9704-42b7-b079-e9e5bf7e8abb.png)

### Prometheus:
In my prometheus, the generated metrics have my actor_type label but not the otel_library_name
![generatedMetrics](https://user-images.githubusercontent.com/34373406/227501966-755b94a3-9540-40ce-aa63-1db4850b428a.png)

Maybe I'm missing something, I tried with all my labels and the problem is only with otel_library_name and otel_library_version

Feel free to ask for more information.
Thank you
