### ISSUE TITLE
"429 too many outstanding requests" occurred even when there're only few requests

### ISSUE THREAD

**Issue by suraciii** [grafana/tempo#2316]
**Describe the bug**

429 error when finding trace by id.

> failed to get trace with id: 0000000000000000fdc76854a6965840 Status: 500 Internal Server Error Body: 3 errors occurred: * rpc error: code = Code(429) desc = too many outstanding requests * rpc error: code = Code(429) desc = too many outstanding requests * rpc error: code = Code(429) desc = too many outstanding requests

**To Reproduce**
1. Start Tempo (2.0.0)
2. Perform Operations (Find Trace By Id)

**Expected behavior**
Request complete successfully

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [custom]

**Additional Context**

configs:
```yaml
query_frontend:
    max_outstanding_per_tenant: 8000
    querier_forget_delay: 0s
    max_retries: 2
    search:
        concurrent_jobs: 2000
        target_bytes_per_job: 10485760
        default_result_limit: 20
        max_result_limit: 0
        max_duration: 168h0m0s
        query_backend_after: 15m0s
        query_ingesters_until: 30m0s
    trace_by_id:
        query_shards: 80
        hedge_requests_at: 2s
        hedge_requests_up_to: 3
```

metrics:

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/13304483/230823854-0c8db483-e533-48c9-ac6d-a92143acc2db.png">

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/13304483/230823812-ac8ad904-19ff-4649-8a0d-59ad1133ee5a.png">

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/13304483/230824028-3a9bcd83-595e-4e73-a709-4bbd8cb62e4d.png">
