### ISSUE TITLE
Block storage lifecycle failure

### ISSUE THREAD

**Issue by barrettzjh** [grafana/tempo#2544]
When I deployed tempo using 'tempo distributed' and used the following configuration file, I encountered a problem. I set 'block_retention=240h'. I found that my storage was full, and after searching the container, I found that data from 17 days ago still exists. How should I solve this problem? Thank you
```yaml
compactor:
  compaction:
    block_retention: 240h
    compacted_block_retention: 1h
    compaction_cycle: 30s
    compaction_window: 1h
    max_compaction_objects: 6000000
    max_time_per_tenant: 5m
    retention_concurrency: 10
    v2_in_buffer_bytes: 5242880
    v2_out_buffer_bytes: 20971520
    v2_prefetch_traces_count: 1000
  ring:
    kvstore:
      store: memberlist
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  ring:
    kvstore:
      store: memberlist
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
    tokens_file_path: /var/tempo/tokens.json
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
  - tempo-gossip-ring
multitenancy_enabled: false
overrides:
  metrics_generator_processors:
  - service-graphs
  - span-metrics
  per_tenant_override_config: /conf/overrides.yaml
  max_bytes_per_trace: 10000000
querier:
  frontend_worker:
    frontend_address: tempo-query-frontend-discovery:9095
  max_concurrent_queries: 20
  search:
    external_endpoints: []
    external_hedge_requests_at: 8s
    external_hedge_requests_up_to: 2
    prefer_self: 10
    query_timeout: 30s
  trace_by_id:
    query_timeout: 10s
query_frontend:
  max_retries: 2
  search:
    concurrent_jobs: 1000
    target_bytes_per_job: 104857600
  tolerate_failed_blocks: 0
  trace_by_id:
    hedge_requests_at: 2s
    hedge_requests_up_to: 2
    query_shards: 50
server:
  grpc_server_max_recv_msg_size: 4194304
  grpc_server_max_send_msg_size: 4194304
  http_listen_port: 3100
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  log_format: logfmt
  log_level: info
storage:
  trace:
    backend: local
    block:
      version: vParquet
    blocklist_poll: 5m
    cache: memcached
    local:
      path: /var/tempo/traces
    memcached:
      consistent_hash: true
      host: tempo-memcached
      service: memcached-client
      timeout: 500ms
    wal:
      path: /var/tempo/wal
usage_report:
  reporting_enabled: true
```

```shell
/var/tempo/traces/single-tenant $ find . -atime +17 -type d
./18363683-af73-4068-87ec-0c423ae4db43
./1441bc08-a679-452e-8ee5-b4b63049faa3
./77a8d7f1-f6a2-4ae3-b24e-482bc50eabb6
./7d482dab-f744-4aed-8cc3-f2cbb1713861
./e5093e1c-74cb-4292-86e0-3660659b823e
./e83423b6-d561-47a8-9b5d-f278c0142815
./b6934fd1-3f97-44cc-b0e7-08736a672cf5
./b8e976da-0762-46ca-af9a-b12ed51586e8
./951b0c72-fae6-4548-9737-5739bb50a01e
./a70913ae-c505-4c4f-873b-8c192fece3cb
./1f192c5c-2d83-48e1-bed6-216af8b482a7
./7576dd1e-a165-488c-8da0-442081421bde
./96dbae5f-9c62-46a9-a85f-dd37894fefd9
./a07af894-1894-48d1-bb23-7bc724addfb5
```
