### ISSUE TITLE
status=500 err=too many failed block queries 1 (max 0)

### ISSUE THREAD

**Issue by barrettzjh** [grafana/tempo#2554]
Hi, it's my config, I tried to set MINIO access to public and successfully downloaded the file, but when I made a query, I still reported an error，I can only find data that hasn't been pushed yet, in about 5 minutes，Looking forward to your reply，Thanks
![image](https://github.com/grafana/tempo/assets/49559097/cb0713f8-b87a-4397-9959-2e665ba35aef)
![image](https://github.com/grafana/tempo/assets/49559097/a087e3e1-df97-4e31-91b5-c17fdeb8aeca)

```
grafana/tempo-distributed-1.2.11
bitnami/minio-12.1.10
```

```yaml
compactor:
  compaction:
    block_retention: 48h
    compacted_block_retention: 1h
    compaction_cycle: 30s
    compaction_window: 1h
    max_block_bytes: 107374182400
    max_compaction_objects: 6000000
    max_time_per_tenant: 5m
    retention_concurrency: 10
    v2_in_buffer_bytes: 5242880
    v2_out_buffer_bytes: 20971520
    v2_prefetch_traces_count: 1000
  ring:
    kvstore:
      store: memberlist
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  ring:
    kvstore:
      store: memberlist
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
    tokens_file_path: /var/tempo/tokens.json
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
  - tempo-gossip-ring
multitenancy_enabled: false
overrides:
  metrics_generator_processors:
  - service-graphs
  - span-metrics
  per_tenant_override_config: /conf/overrides.yaml
  max_bytes_per_trace: 10000000
  max_traces_per_user: 100000
querier:
  frontend_worker:
    frontend_address: tempo-query-frontend-discovery:9095
  max_concurrent_queries: 20
  search:
    external_endpoints: []
    external_hedge_requests_at: 8s
    external_hedge_requests_up_to: 2
    prefer_self: 10
    query_timeout: 30s
  trace_by_id:
    query_timeout: 10s
query_frontend:
  max_retries: 2
  search:
    concurrent_jobs: 1000
    target_bytes_per_job: 104857600
  tolerate_failed_blocks: 0
  trace_by_id:
    hedge_requests_at: 2s
    hedge_requests_up_to: 2
    query_shards: 50
server:
  grpc_server_max_recv_msg_size: 4194304
  grpc_server_max_send_msg_size: 4194304
  http_listen_port: 3100
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  log_format: logfmt
  log_level: info
storage:
  trace:
    backend: s3
    block:
      version: vParquet
    blocklist_poll: 5m
    cache: memcached
    local:
      path: /var/tempo/traces
    memcached:
      consistent_hash: true
      host: tempo-memcached
      service: memcached-client
      timeout: 500ms
    s3:
      #access_key: CU75xsRb0u4Nv4nK
      bucket: helian-tempo
      endpoint: minio.minio:9000
      insecure: true
      #secret_key: 2vi12l5fxI7V2B0icm7op8grLQHsf3f2
    wal:
      path: /var/tempo/wal
usage_report:
  reporting_enabled: true
```

```
# kubectl logs -f tempo-querier-66f6c486d6-klmhg -n tempo
level=info ts=2023-06-14T05:46:43.870333553Z caller=tempodb.go:343 org_id=single-tenant msg="searching for trace in block" findTraceID=b21b8d4c8f2265db0072d74847fc3fe5 block=bd7569c2-e445-45dd-a8ee-053b908d36de found=false
level=error ts=2023-06-14T05:46:43.871736841Z caller=frontend_processor.go:70 msg="error processing requests" address=172.20.0.249:9095 err="rpc error: code = Canceled desc = context canceled"
level=warn ts=2023-06-14T05:46:48.872048863Z caller=querier.go:262 msg="failed to query 1 blocks" blockErrs="error finding trace by id, blockID: 813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad: error retrieving bloom bloom-7 (single-tenant, 813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad): Get \"http://minio.minio:9000/helian-tempo/single-tenant/813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad/bloom-7\": context deadline exceeded"
level=error ts=2023-06-14T05:46:48.873023567Z caller=frontend_processor.go:70 msg="error processing requests" address=172.20.0.249:9095 err="rpc error: code = Canceled desc = context canceled"
level=warn ts=2023-06-14T05:47:01.900016096Z caller=querier.go:262 msg="failed to query 1 blocks" blockErrs="error finding trace by id, blockID: 813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad: error retrieving bloom bloom-7 (single-tenant, 813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad): Get \"http://minio.minio:9000/helian-tempo/single-tenant/813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad/bloom-7\": context canceled"
level=error ts=2023-06-14T05:47:01.900268652Z caller=frontend_processor.go:146 msg="error processing requests" err=EOF
level=warn ts=2023-06-14T05:47:06.910035965Z caller=querier.go:262 msg="failed to query 1 blocks" blockErrs="error finding trace by id, blockID: bd7569c2-e445-45dd-a8ee-053b908d36de: error retrieving bloom bloom-7 (single-tenant, bd7569c2-e445-45dd-a8ee-053b908d36de): Get \"http://minio.minio:9000/helian-tempo/single-tenant/bd7569c2-e445-45dd-a8ee-053b908d36de/bloom-7\": context canceled"
level=error ts=2023-06-14T05:47:06.910440208Z caller=frontend_processor.go:146 msg="error processing requests" err=EOF
level=info ts=2023-06-14T05:51:02.739863963Z caller=poller.go:167 msg="successfully pulled tenant index" tenant=single-tenant createdAt=2023-06-14T05:48:21.068259934Z metas=2 compactedMetas=5
level=info ts=2023-06-14T05:55:55.724729772Z caller=poller.go:167 msg="successfully pulled tenant index" tenant=single-tenant createdAt=2023-06-14T05:55:04.301600716Z metas=2 compactedMetas=5
level=info ts=2023-06-14T06:00:55.727695489Z caller=poller.go:167 msg="successfully pulled tenant index" tenant=single-tenant createdAt=2023-06-14T05:59:57.277448503Z metas=2 compactedMetas=5
level=info ts=2023-06-14T06:01:31.966287375Z caller=tempodb.go:343 org_id=single-tenant msg="searching for trace in block" findTraceID=81cc2caefb401930096b1603bdda4ac2 block=813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad found=false
level=error ts=2023-06-14T06:01:31.967428808Z caller=frontend_processor.go:70 msg="error processing requests" address=172.20.0.249:9095 err="rpc error: code = Canceled desc = context canceled"
level=warn ts=2023-06-14T06:01:37.958001184Z caller=querier.go:262 msg="failed to query 1 blocks" blockErrs="error finding trace by id, blockID: bd7569c2-e445-45dd-a8ee-053b908d36de: error retrieving bloom bloom-1 (single-tenant, bd7569c2-e445-45dd-a8ee-053b908d36de): Get \"http://minio.minio:9000/helian-tempo/single-tenant/bd7569c2-e445-45dd-a8ee-053b908d36de/bloom-1\": context deadline exceeded"
level=error ts=2023-06-14T06:01:37.96392271Z caller=frontend_processor.go:70 msg="error processing requests" address=172.20.0.249:9095 err="rpc error: code = Canceled desc = context canceled"
level=warn ts=2023-06-14T06:01:43.96419328Z caller=querier.go:262 msg="failed to query 1 blocks" blockErrs="error finding trace by id, blockID: 813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad: error retrieving bloom bloom-1 (single-tenant, 813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad): Get \"http://minio.minio:9000/helian-tempo/single-tenant/813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad/bloom-1\": context canceled"
level=error ts=2023-06-14T06:01:43.96444801Z caller=frontend_processor.go:146 msg="error processing requests" err=EOF
level=warn ts=2023-06-14T06:01:48.974015436Z caller=querier.go:262 msg="failed to query 1 blocks" blockErrs="error finding trace by id, blockID: bd7569c2-e445-45dd-a8ee-053b908d36de: error retrieving bloom bloom-1 (single-tenant, bd7569c2-e445-45dd-a8ee-053b908d36de): Get \"http://minio.minio:9000/helian-tempo/single-tenant/bd7569c2-e445-45dd-a8ee-053b908d36de/bloom-1\": context deadline exceeded"
level=error ts=2023-06-14T06:01:48.974285348Z caller=frontend_processor.go:146 msg="error processing requests" err=EOF
level=info ts=2023-06-14T06:05:55.401214536Z caller=poller.go:167 msg="successfully pulled tenant index" tenant=single-tenant createdAt=2023-06-14T06:05:08.295756673Z metas=2 compactedMetas=5
level=info ts=2023-06-14T06:10:55.725053741Z caller=poller.go:167 msg="successfully pulled tenant index" tenant=single-tenant createdAt=2023-06-14T06:09:31.863822398Z metas=2 compactedMetas=1
level=info ts=2023-06-14T06:14:11.628857506Z caller=tempodb.go:343 org_id=single-tenant msg="searching for trace in block" findTraceID=698d1731eef93a80d028e4d4d2687cc9 block=813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad found=false
level=error ts=2023-06-14T06:14:11.630138931Z caller=frontend_processor.go:70 msg="error processing requests" address=172.20.0.249:9095 err="rpc error: code = Canceled desc = context canceled"
level=warn ts=2023-06-14T06:14:17.636036315Z caller=querier.go:262 msg="failed to query 1 blocks" blockErrs="error finding trace by id, blockID: bd7569c2-e445-45dd-a8ee-053b908d36de: error retrieving bloom bloom-8 (single-tenant, bd7569c2-e445-45dd-a8ee-053b908d36de): Get \"http://minio.minio:9000/helian-tempo/single-tenant/bd7569c2-e445-45dd-a8ee-053b908d36de/bloom-8\": context deadline exceeded"
level=error ts=2023-06-14T06:14:17.637102828Z caller=frontend_processor.go:70 msg="error processing requests" address=172.20.0.249:9095 err="rpc error: code = Canceled desc = context canceled"
level=warn ts=2023-06-14T06:14:22.646014111Z caller=querier.go:262 msg="failed to query 1 blocks" blockErrs="error finding trace by id, blockID: 813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad: error retrieving bloom bloom-8 (single-tenant, 813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad): Get \"http://minio.minio:9000/helian-tempo/single-tenant/813bbe7b-08d4-4ebc-ab55-15fa6d9fa0ad/bloom-8\": context canceled"
level=error ts=2023-06-14T06:14:22.646247393Z caller=frontend_processor.go:146 msg="error processing requests" err=EOF
level=warn ts=2023-06-14T06:14:27.655987218Z caller=querier.go:262 msg="failed to query 1 blocks" blockErrs="error finding trace by id, blockID: bd7569c2-e445-45dd-a8ee-053b908d36de: error retrieving bloom bloom-8 (single-tenant, bd7569c2-e445-45dd-a8ee-053b908d36de): Get \"http://minio.minio:9000/helian-tempo/single-tenant/bd7569c2-e445-45dd-a8ee-053b908d36de/bloom-8\": context deadline exceeded"
level=error ts=2023-06-14T06:14:27.656208991Z caller=frontend_processor.go:146 msg="error processing requests" err=EOF
level=info ts=2023-06-14T06:15:55.725163677Z caller=poller.go:167 msg="successfully pulled tenant index" tenant=single-tenant createdAt=2023-06-14T06:13:50.137430442Z metas=2 compactedMetas=0

```
