### ISSUE TITLE
Add Helm tests

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#256]
The Helm charts are not tested.  The microservices Jsonnet and mixin are in use by Grafana so are likely to be functional, but the others are could drift over time.  

The tests do not need to be extensive.  Just apply the chart/jsonnet, push some spans and query them back.

**Comment by dgzlopes** [comment]
What approach do you have in mind? Spawning a k3s instance on CI?

**Comment by joe-elliott** [comment]
Yeah, I think that's the most straightforward approach.  I suppose I'd look around some to see if there any other good examples out there of people doing similar things.

If we did use a custom solution using k3s then we might also be able to use it to test the jsonnet as well.

**Comment by dgzlopes** [comment]
I found [this](https://odino.org/running-ci-tests-in-kubernetes-through-github-actions/) example online for running Kubernetes on Github Actions. 

Pretty easy, and it worked! But I thought that maybe it was interesting to use k3d instead of k3s. This way: 
- the commands explained in the tutorials can be re-used.
- the clusters can be configured easily (e.g. multi-node).

Here is a working example of my approach:
```YAML
name: Kubernetes
on: [push]
jobs:

  build:
    name: Run Kubernetes tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install k3d
      run: wget -q -O - https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash

    - name: Run cluster
      run: k3d cluster create tempo --api-port 6443 --port "16686:80@loadbalancer"

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'
      id: install

    - name: Deploy Tempo
      run: |
        helm install operations/helm/tempo-single-binary/ --wait --generate-name
        kubectl create -f example/helm/single-binary-extras.yaml

    - name: Wait for synthetic-load-generator
      run:  kubectl rollout status deployment synthetic-load-generator

    - name: Example tests
      run: |
        kubectl get nodes
        kubectl get deployments
        kubectl get pods
        kubectl get services

    - name: Example tests 2
      run: |
        kubectl logs --tail=1 deployment/synthetic-load-generator
```

And here is a [sample run](https://github.com/dgzlopes/tempo/runs/1546561506?check_suite_focus=true). I guess it could be easily adapted to support Jsonnet as well!

Probably the real "test" logic should be moved out of the YAML file.
