### ISSUE TITLE
Increasing RAM usage in ingester until OOM

### ISSUE THREAD

**Issue by rlex** [grafana/tempo#2602]
**Describe the bug**
Ingester RAM increases until it OOMs

**To Reproduce**
Not sure how. Might be exclusive to our setup. Deployed with tempo-distributed chart. Tempo 2.1.1.
vParquet 2 blocks

Custom values:
```
            server:
              grpc_server_max_recv_msg_size: 67108864
              grpc_server_max_send_msg_size: 67108864
              http_server_read_timeout: 60s
              http_server_write_timeout: 60s
            compactor:
              compaction:
                block_retention: 168h
#                max_block_bytes: 50147483648
            ingester:
              flush_check_period: 5s
              trace_idle_period: 5s
            querier:
              max_concurrent_queries: 100
              query_relevant_ingesters: true
              trace_by_id:
                query_timeout: 30s
              frontend_worker:
                grpc_client_config:
                  max_send_msg_size: 67108864
            query_frontend:
              max_outstanding_per_tenant: 5000
              tolerate_failed_blocks: 1
              max_retries: 3
              search:
                concurrent_jobs: 3000
              trace_by_id:
                query_shards: 256
            usage_report:
              reporting_enabled: false
```

**Expected behavior**
Stable RAM consumption

**Environment:**
 - Infrastructure: k8s
 - Deployment tool: helm

Source of traces: otel-collector with tail-based sampling enabled

**Additional Context**
Slack thread related to issue:
https://grafana.slack.com/archives/C01D981PEE5/p1687523038794849

So far we eliminated all long-running traces (>2000 spans in trace, usually background jobs)
Cleaned up some of very high-cardinality attributes (not sure if matters)
Tried flushing more often to disk (5s instead of 10s) 
Cut blocks more often (5m instead of 30m)
GOMEMLIMIT 

tempo_ingester_live_traces shows from 14m to 5m live traces load. 

It seems only 3 (of 9) ingesters are affected, that correlates with replication factor = 3?

Either way, no idea what to do next. Tempo mostly works, one of ingesters OOMs, it doesn't affect trace processing pipeline (it seems), but that's obviously not so optimal.
