### ISSUE TITLE
Tempo with docker-compose on Azure Container Instance terminates instantly

### ISSUE THREAD

**Issue by advdk** [grafana/tempo#2624]
**Describe the bug**
Using Docker Compose on an ACI context om trying to start Tempo. It will Terminate without logs immediately after start. 

**To Reproduce**
1. `docker login azure`
2. `docker context create aci myacicontext`
3. `docker context use aci-context`
4. `docker compose up -d`

**Expected behavior**
I would expect tempo and prometheus to start, or at least give me some error in the log. Prometheus starts, but Tempo terminates immediately.

**Environment:**
 - Infrastructure: Azure, Azure Container Instance. 
 - Deployment tool: docker compose

**Additional Context**
```yaml
version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/etc/prometheus
  tempo:
    image: grafana/tempo:2.0.0
    container_name: tempo
    command: -config.file /etc/tempo/tempo.yml
    ports:
      - "3200:3200"
      - "4317:4317"
      - "9411:9411"
    volumes:
      - tempo:/etc/tempo/
volumes:
  prometheus:
    driver: azure_file
    driver_opts:
      share_name: prometheus
      storage_account_name: <storage_account_name>
      storage_account_key: <storage_account_key>
  tempo:
    driver: azure_file
    driver_opts:
      share_name: tempo
      storage_account_name: <storage_account_name>
      storage_account_key: <storage_account_key>
```
