### ISSUE TITLE
Metrics Generator not working correctly

### ISSUE THREAD

**Issue by KKHYeon** [grafana/tempo#2675]
**Describe the bug**

**Expected behavior**

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Tempo version: 2.1.1

**Additional Context**
1. metrics generator fails to properly generate service_graph metrics.
In the first case shown in the picture, it cannot generate the metrics. However, in the third case, it successfully generates the metrics.
![image](https://github.com/grafana/tempo/assets/46926610/49995313-07a6-4511-b8f5-da7a70dba9fa)
I suspect that the version of the OpenTelemetry agent might be the cause.
In the case of Javaagent version 1.21.0, it seems that metrics are not being generated properly. However, in the case of version 1.27.0, metrics are likely being generated. (but i think it's not perfect....)
And I'm using Opentelemetry sdk  version 1.2.0 in Ruby  
I'm curious about which version of the metric generator you should use to ensure that it operates without any issues and can generate metrics properly
* OpenTelemetry version
2. metrics generator sends requests to the Jaeger port and encounters an error 
I am curious about why this error is occurring and what the possible solutions might be.
This is metrics generator pod log.
```
msg=OpenTelemetry.ErrorHandler err="Post \"http://localhost:14268/api/traces\": dial tcp [::1]:14268: connect: connection refused"
```

**Comment by mapno** [comment]
> I'm curious about which version of the metric generator you should use to ensure that it operates without any issues and can generate metrics properly

Any version should produce metrics for the first scenario if traces are produced correctly. Can you reliably reproduce the problem you describe? Can you share a trace that should generate a link between services that it's not doing so?

Also, checkout the [metrics-generator config](https://grafana.com/docs/tempo/latest/configuration/#metrics-generator). You may want to increase `wait`, `max_items` and `ingestion_time_range_slack`, depending on how spans are arriving to Tempo.

> metrics generator sends requests to the Jaeger port and encounters an error

The metrics-generator sends metrics to a Prometheus-compatible backend. Jaeger shouldn't be used for this, since it's a tracing backend. See https://grafana.com/docs/tempo/latest/metrics-generator/#overview

**Comment by KKHYeon** [comment]
Thank you for your response.

1.
Can I understand that the `wait` value is related to the latency of the trace?
Here are the settings related to the metric generator:
```
    processor:
      service_graphs:
        # -- Additional dimensions to add to the metrics. Dimensions are searched for in the
        # -- resource and span attributes and are added to the metrics if present.
        dimensions:
          - "cluster"
        # Buckets for the latency histogram in seconds.
        histogram_buckets: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
        max_items: 10000
        # Wait is the value to wait for an edge to be completed.
        wait: 30s
        # Workers is the amount of workers that will be used to process the edges
        workers: 20
    metrics_ingestion_time_range_slack: 30s
```
It difficult to share the trace.
And is there a possibility that incorrect settings in the distributor could also prevent metrics from being generated properly?

2.
```
msg=OpenTelemetry.ErrorHandler err="Post \"http://localhost:14268/api/traces\": dial tcp [::1]:14268: connect: connection refused"
```
This error is occurring not only in the metrics generator but also in the querier, distributor, and ingester. I haven't made any specific configurations related to Jaeger.

3.
Currently, there are 404 errors happening in some APIs related to the ring. 
Specifically, `/distributor/ring and /metrics-generator/ring` return a 404 status code, while `/ingester/ring and /compactor/ring` return 200. When checking `/memberlist` API, the status of all componets is "alive". Could the 404 errors be a problem?
