### ISSUE TITLE
Set GOMAXPROCS automatically for containerised environments

### ISSUE THREAD

**Issue by gebn** [grafana/tempo#2715]
**Is your feature request related to a problem? Please describe.**

Further to [this](https://community.grafana.com/t/is-it-necessary-to-set-gomaxprocs-in-a-containerised-environment/99815) forum thread, if Tempo runs on a large K8s node, Go will believe it has access to all cores on the node, even if the container has been limited to a small number of cores. This can cause throttling when the process uses more CPU time than it has access to, described [here](https://github.com/uber-go/automaxprocs#performance), due to the interval at which cgroup accounting happens.

**Describe the solution you'd like**
The easiest/most common way of doing this is including [`uber-go/autogomaxprocs`](https://github.com/uber-go/automaxprocs), which sets `GOMAXPROCS` on process startup to the correct value, based on the real resources available to the process.

**Describe alternatives you've considered**
The alternative is every user adding something like this to their K8s config:

```yaml
      containers:
      - name: compactor
        image: grafana/tempo
        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              containerName: compactor
              resource: limits.cpu
```

Happy to submit a PR if this is accepted.
