### ISSUE TITLE
enable_target_info: true does not generate traces_target_info metrics

### ISSUE THREAD

**Issue by t3hl34d3r** [grafana/tempo#2834]
**Describe the bug**
enable_target_info: true does not generate traces_target_info metrics

**To Reproduce**
1. Start Tempo (SHA or version)
2. Set enable_target_info: true within span_metrics
3. Gather traces
4. Check prometheus for metrics

**Expected behavior**
Tempo should generate traces_target_info metrics, and they should be visible within prometheus.

**Environment:**
 - Infrastructure: Kubernetes
 - Custom yamls:

ConfigMap:
```
apiVersion: v1
data:
  tempo.yaml: |-
    server:
      http_listen_port: 3200

    distributor:
      receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
        jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
          protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
            thrift_http:                   #
            grpc:                          # for a production deployment you should only enable the receivers you need!
            thrift_binary:
            thrift_compact:
        zipkin:
        otlp:
          protocols:
            http:
            grpc:
        opencensus:

    ingester:
      max_block_duration: 10m               # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

    compactor:
      compaction:
        block_retention: 720h                # overall Tempo trace retention. set for demo purposes

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: docker-compose
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: https://prometheus.company.com/api/v1/write
            send_exemplars: true
      processor:
        span_metrics:
          dimensions:
            - jenkins.pipeline.step.name
            - jenkins.pipeline.step.id
            - ci.pipeline.id
            - error
            - jenkins.computer.name
            - host.name
            - status.code
            - status.message
            - ci.pipeline.run.number
            - ci.pipeline.run.result
            - jenkins.url
            - service.instance.id
          enable_target_info: true

    storage:
      trace:
        backend: s3                     # backend configuration to use
        s3:
          endpoint: minio.company.com:9000
          bucket: tempo-prod
          forcepathstyle: true
          #set to true if endpoint is http
          insecure: false
          tls_insecure_skip_verify: true
        wal:
          path: /tmp/tempo/wal             # where to store the the wal locally
        local:
          path: /tmp/tempo/blocks

    overrides:
      metrics_generator_processors: [service-graphs, span-metrics] # enables metrics generator
kind: ConfigMap
metadata:
  name: tempo-configmap
  namespace: default
  namespace: monitoring

```
Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo-container
          image: grafana/tempo:2.2.0
          args: ["-config.file=/etc/tempo.yaml"]
          ports:
            - containerPort: 3200
            - containerPort: 14268
            - containerPort: 9095
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 9411
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access
                  key: minio-accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access
                  key: minio-secretkey
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-configmap
            items:
              - key: tempo.yaml
                path: tempo.yaml
```
Service:
```
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: tempo
  ports:
    - name: tempo-http
      port: 3200
      targetPort: 3200
      nodePort: 30320
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      nodePort: 30317
    - name: otlp-http
      port: 4318
      targetPort: 4318
      nodePort: 30318
```

Thanks in advance!
