### ISSUE TITLE
Use of x-amz-sdk-checksum-algorithm breaks B2 compatibility

### ISSUE THREAD

**Issue by AndreKR** [grafana/tempo#2910]
**Is your feature request related to a problem? Please describe.**
I'd like to use Backblaze B2 as the storage backend for Tempo. I'm already using it for Loki. They have a somewhat S3-compatible API. Unfortunately they don't support `x-amz-sdk-checksum-algorithm` but Tempo seems to rely on it.

**Describe the solution you'd like**
I'm not sure how Tempo uses `x-amz-sdk-checksum-algorithm`. Backblaze B2 also offers some options for server-generated checksums. Ideally it would "just work", but a config option to turn on B2 compatibility would also be great.

**Comment by joe-elliott** [comment]
I did a quick search of the codebase and did not find any references to `x-amz-sdk-checksum-algorithm`. I would not be surprised if our s3 client (minio) uses it in some way. Can you share a log message? Why do you think `x-amz-sdk-checksum-algorithm` is an issue?

**Comment by AndreKR** [comment]
Indeed I didn't look into the details. I didn't even see that is is in regards to the usage reporting. I just saw the error message and assumed it would be an issue.

My config:
```yaml
server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:

storage:
  trace:
    backend: s3
    wal:
      path: /tmp/tempo/wal
    s3:
      bucket: [REDACTED]
      endpoint: s3.us-west-000.backblazeb2.com
      access_key: [REDACTED]
      secret_key: [REDACTED]
#    backend: local
#    local:
#      path: /tmp/tempo/blocks
```

The error message:
```plain
level=warn ts=2023-09-12T00:42:51.087494838Z caller=reporter.go:112 msg="failed to CAS cluster seed key" err="error writing object to s3 backend, object tempo_cluster_seed.json: Unsupported header 'x-amz-checksum-algorithm' received for this API call."
```

Since I switched back to B2 a couple of minutes ago it hasn't written any files to B2, it's just amassing WAL files. I'm guessing it should flush them at some point?
