### ISSUE TITLE
Reporting errors for unknown tenant 

### ISSUE THREAD

**Issue by robert-nemet** [grafana/tempo#2912]
Upgraded tempo to version 2.2.2(from 2.1.1) with official helm-chart(tempo-distributed) version 1.6.3.

Since then I'm getting these errors:

```txt
level=info ts=2023-09-11T07:18:43.385600641Z caller=poller.go:193 msg="successfully pulled tenant index" tenant=dev-cookie createdAt=2023-09-11T07:14:23.489751556Z metas=48 compactedMetas=7
tempo-querier-84bff5895-fmd8v level=info ts=2023-09-11T07:18:43.449770612Z caller=poller.go:193 msg="successfully pulled tenant index" tenant=prod-cherry createdAt=2023-09-11T07:14:23.808670491Z metas=48 compactedMetas=7
tempo-querier-84bff5895-fmd8v level=error ts=2023-09-11T07:18:43.48576662Z caller=poller.go:205 msg="failed to pull bucket index for tenant. falling back to polling" tenant=single-tenant err="does not exist"
tempo-querier-84bff5895-fmd8v level=info ts=2023-09-11T07:18:43.574738632Z caller=poller.go:217 msg="writing tenant index" tenant=single-tenant metas=0 compactedMetas=0
tempo-querier-84bff5895-fmd8v level=info ts=2023-09-11T07:18:43.586400147Z caller=poller.go:130 msg="blocklist poll complete" seconds=0.360507541
```

I do have two collectors: dev and prod. But I do not have collector which should report metrics for `single-tenant`.  No where in my configuration this tenant is mentioned. What am I missing? 

My config:
```yaml
tempo-distributed:
  multitenancyEnabled: true

  tempo:
    structuredConfig:
      querier:
        max_concurrent_queries: 10

  serviceAccount:
    annotations:
      "iam.gke.io/gcp-service-account": "tempo-sa@team-platform.iam.gserviceaccount.com"

  distributor:
    replicas: 3
    resources:
      limits:
        memory: 500Mi
      requests:
        memory: 500Mi
        cpu: 50m
    service:
      type: LoadBalancer
      annotations:
        networking.gke.io/load-balancer-type: Internal
        external-dns.alpha.kubernetes.io/hostname: tempo.platform.team.engineering.
    tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    podAnnotations:
      prometheus.io/port: "3100"
      prometheus.io/scrape: "true"

  ingester:
    replicas: 2
    resources:
      limits:
        memory: 1500Mi
      requests:
        memory: 1500Mi
        cpu: 80m
    persistence:
      enabled: true
      size: 15Gi
      storageClass: regional-ssd
    podAnnotations:
      prometheus.io/port: "3100"
      prometheus.io/scrape: "true"
    config:
      replication_factor: 1

  compactor:
    resources:
      limits:
        memory: 1500Mi
      requests:
        memory: 1500Mi
        cpu: 50m
    tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    podAnnotations:
      prometheus.io/port: "3100"
      prometheus.io/scrape: "true"
    config:
      compaction:
        block_retention: 48h

  querier:
    replicas: 2
    resources:
      limits:
        memory: 1100Mi
      requests:
        memory: 1100Mi
        cpu: 20m
    tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    podAnnotations:
      prometheus.io/port: "3100"
      prometheus.io/scrape: "true"

  queryFrontend:
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    resources:
      limits:
        memory: 75Mi
      requests:
        memory: 75Mi
        cpu: 20m
    tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    podAnnotations:
      prometheus.io/port: "3100"
      prometheus.io/scrape: "true"

  storage:
    trace:
      backend: gcs
      gcs:
        bucket_name: tempo-store

  traces:
    otlp:
      http:
        enabled: true
      grpc:
        enabled: true

  minio:
    enabled: false

  metricsGenerator:
    enabled: true
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 800Mi
      limits:
        memory: 800Mi
    config:
      storage:
        remote_write:
        - url: http://some-url.com
          send_exemplars: true

  global_overrides:
    metrics_generator_processors:
      - service-graphs
      - span-metrics
```
