### ISSUE TITLE
metrics_generator: different header option for remote write

### ISSUE THREAD

**Issue by ToonTijtgat2** [grafana/tempo#2975]
**Describe the bug**
Remote write setting from metrics_generator is not writing to the correct mimir instance. instead of using the header I pass in the configuration, it takes the header configured for the tempo setup.

**To Reproduce**
```
metrics_generator:
  storage:
    remote_write:
    - headers:
       X-Scope-OrgID: tracing-metrics
     remote_timeout: 30s
     url: https://xxx/api/v1/push
```
**Expected behavior**
Metrics generated by the metrics_generator should be sent to the url including the header specified in the config above instead of the header we use for the tempo stack.
