### ISSUE TITLE
Authentication support in GRPC OTEL receiver

### ISSUE THREAD

**Issue by crypticmind** [grafana/tempo#2996]
**Is your feature request related to a problem? Please describe.**
Right now, the only way to secure the OTEL endpoints is through a reverse HTTP proxy, which means it can only be done for the HTTP endpoint, and by means of an additional component (the proxy server itself).

**Describe the solution you'd like**
It would be great if the GRPC endpoint could support authentication, basic auth as a starting point, then bearer and/or any other later, in the same way as in [opentelemmetry docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension) but without using any "extensions".

As an example:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        auth:
          basicauth:
              file: .htpasswd
              # or
              username: ${BASIC_AUTH_USERNAME}
              password: ${BASIC_AUTH_PASSWORD}
```

Although it would make sense to also support authentication for the HTTP endpoint, I understand that that is covered by the use of a reverse proxy not only in Tempo, but also in Loki and Mimir, which makes it consistent at least. Adding HTTP auth support here would set a precedent for Loki and Mimir.

Thank you for such an amazing work!

Carlos
