### ISSUE TITLE
Reduce 404s - NotFound in polling cycle

### ISSUE THREAD

**Issue by PatrikMuniak** [grafana/tempo#3000]
Hi, not sure it's a bug so created an issue as feature.

**Is your feature request related to a problem? Please describe.**
Feature related to a problem. I'm trying to set up tempo in single binary mode and I noticed plenty of 404s hitting the storage.
I tracked down the 404s to mostly the polling cycle that gets the list of blocks and then, by my 
uderstanding, it sends a read request for the meta.json file and if not found it looks for the 
meta.compacted.json file. 

https://github.com/grafana/tempo/blob/671d6293f026de4c79091dfa7b69e1e6c8d3414f/tempodb/blocklist/poller.go#L293C11-L293C11

This triggers plenty of 404s on the storage on every polling cycle, and it's getting worse the more compacted blocks there are in a tenant.
Not being familiar with Tempo's architecture, I was wondering if there are any possiblility in making tempo's 
polling job more efficient? as in the polling cycle as it could trigger 2 requests per block that in a context
with many blocks and many tenats adds up.

**Describe the solution you'd like**
Reduce the number of 404s improving efficiency if possible.

**Describe alternatives you've considered**
We can mitigate the increase in 404s with reducing the compaction on the config or even disabling 
it or disable it altogether.

**Additional context**
We are running tempo in scalable-single-binary mode. 
This is our polling config:
```
        blocklist_poll: 5m0s
        blocklist_poll_concurrency: 50
        blocklist_poll_fallback: true
        blocklist_poll_tenant_index_builders: 2
        blocklist_poll_stale_tenant_index: 0s
        blocklist_poll_jitter_ms: 0
        blocklist_poll_tolerate_consecutive_errors: 1
```

and this is the compactor config:
```
compaction:
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 1000
        compaction_window: 15m0s
        max_compaction_objects: 6000000
        max_block_bytes: 107374182400
        block_retention: 336h0m0s
        compacted_block_retention: 1h0m0s
        retention_concurrency: 10
        max_time_per_tenant: 5m0s
        compaction_cycle: 30s
```

P.S. if you'd like the steps to replicate the notFound requests I can provide them
