### ISSUE TITLE
[tempo helm chart] Metrics Generator remote_write is not sending traces to prometheus

### ISSUE THREAD

**Issue by 0xfabio** [grafana/tempo#3036]
Hi guys,

unfortunately, I have a problem with the Grafana Tempo metrics generator.

Situation:

As mentioned [here in the docs](https://grafana.com/docs/tempo/latest/metrics-generator/span_metrics/), it should be possible to use the metrics generator to automatically create exemplars with the trace_id in prometheus. 
For that I implemented the `remote_write` to the `/api/v1/write` of our prometheus.

We are using kubernetes and I configured the kube-prometheus-stack helm chart to have exemplar storage activated and also configured the grafana prometheus datasource to show exemplars.

The metrics are successfully created by the metrics generator and sent to prometheus, but the exemplars are not.

The config:

Tempo configmap:
```yaml
apiVersion: v1
data:
  overrides.yaml: |
    overrides:
      {}
  tempo.yaml: |2

    multitenancy_enabled: false
    usage_report:
      reporting_enabled: false
    compactor:
      compaction:
        block_retention: 24h
    distributor:
      receivers:
            jaeger:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:14250
                thrift_binary:
                  endpoint: 0.0.0.0:6832
                thrift_compact:
                  endpoint: 0.0.0.0:6831
                thrift_http:
                  endpoint: 0.0.0.0:14268
            opencensus: null
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
    ingester:
          max_block_bytes: 1000000
          max_block_duration: 5m
          trace_idle_period: 10s
    server:
          http_listen_port: 3100
    storage:
          trace:
            backend: s3
            local:
              path: /var/tempo/traces
            s3:
              bucket: tempo-traces-abcdef
              endpoint: s3.dualstack.eu-central-1.amazonaws.com
            wal:
              path: /var/tempo/wal
    querier:
          {}
    query_frontend:
          {}
    overrides:
          per_tenant_override_config: /conf/overrides.yaml
```

Prometheus Custom Resource:
```yaml
....
spec:
...
  enableFeatures:
  - exemplar-storage
```

Prometheus Log:
```
prometheus ts=2023-10-19T09:22:41.308Z caller=main.go:181 level=info msg="Experimental in-memory exemplar storage enabled" 
```

I hope this can help improve Tempo even more and am grateful for any pointers / help.

**Comment by mapno** [comment]
I see. Do you have `send_exemplars` set to true in the remote_write config of the generator?

```yaml
metrics_generator:
    storage:
        remote_write:
            send_exemplars: true
```

**Comment by 0xfabio** [comment]
Yes but following the [docs](https://grafana.com/docs/tempo/latest/configuration/#metrics-generator), mine is looking like this:

```yaml
metrics_generator:
      storage:
        remote_write:
          - url: {{ .Values.tempo.metricsGenerator.remoteWriteUrl }}
            send_exemplars: true
```
