### ISSUE TITLE
MetricSummary

### ISSUE THREAD

**Issue by hossko** [grafana/tempo#3064]
Hello,

Using MetricSummary experimental feature for Grafana Tempo results in the below error regardless of the query results:

Query error
Error (error querying generators in Querier.SpanMetricsSummary: failed to get response from generators: failed to execute f() for 10.49.58.88:9095: rpc error: code = Unknown desc = localblocks processor not found ). Please check the server logs for more details.

**Comment by mapno** [comment]
Hi. You need to enable the `local-blocks` processor in the metrics-generator for the API to work.

```yaml
overrides:
  defaults:
    metrics_generator:
      processors: ['local-blocks']
```
