### ISSUE TITLE
s3 via AWS EKS IRSA and grafana/tempo not being used?

### ISSUE THREAD

**Issue by dmitry-mightydevops** [grafana/tempo#3132]
**Describe the bug**

- Installed tempo using HELM `grafana/tempo` version: **1.7.0**
- Trying to use S3 with tempo via AWS IRSA IAM Role
- It writes only a single file in the bucket and the rest of traces are still kept in the local disk, so without the PVC the tempo restart cause the loss of all traces.
- Is there a use for S3 backend storage for the mentioned chart? Or is it supposed to be only in the `grafana/tempo-distributed` chart?
- There were some files in the s3 bucket, but restart of tempo-0 pod caused all traces to be gone

![image](https://github.com/grafana/tempo/assets/70822710/f35fa005-db74-40cd-aeb7-58e6a1e24377)

nothing in the tempo-0 logs:

```
level=info ts=2023-11-10T21:31:48.415301816Z caller=app.go:201 msg="Tempo started"
level=info ts=2023-11-10T21:32:06.757741038Z caller=searchsharding.go:225 msg="sharded search query request stats and SearchMetrics" tenant=single-tenant query="q={}&limit=20&start=1699630326&end=1699651926" duration_seconds=7.899357ms request_throughput=0 total_requests=1 started_requests=1 cancelled_requests=0 finished_requests=1 totalBlocks=0 inspectedBytes=0 inspectedTraces=0 totalBlockBytes=0
level=info ts=2023-11-10T21:32:06.757861828Z caller=handler.go:135 tenant=single-tenant method=GET traceID=2870edd4ed78fb05 url="/api/search?q=%7B%7D&limit=20&start=1699630326&end=1699651926" duration=8.620094ms response_size=57 status=200
level=info ts=2023-11-10T21:32:08.93554745Z caller=searchsharding.go:225 msg="sharded search query request stats and SearchMetrics" tenant=single-tenant query="q={}&limit=20&start=1699630328&end=1699651928" duration_seconds=5.859689ms request_throughput=1.6487223127370751e+06 total_requests=1 started_requests=1 cancelled_requests=0 finished_requests=1 totalBlocks=0 inspectedBytes=9661 inspectedTraces=0 totalBlockBytes=0
level=info ts=2023-11-10T21:32:08.936447737Z caller=handler.go:135 tenant=single-tenant method=GET traceID=51976d79d62ffda3 url="/api/search?q=%7B%7D&limit=20&start=1699630328&end=1699651928" duration=6.845181ms response_size=925 status=200
level=info ts=2023-11-10T21:32:11.382504375Z caller=handler.go:135 tenant=single-tenant method=GET traceID=662021331aacc514 url=/api/traces/307514758bf6388cc726fac6f1e1110 duration=11.81595ms response_size=527 status=200
```

**To Reproduce**

Configuration file:

```yaml
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111111:role/project-prod-eks-tempo-role

tempo:
  retention: 72h
  storage:
    trace:
      backend: s3
      s3:
        bucket: project-prod-eks-tempo
        region: us-east-1
        endpoint: s3.dualstack.us-east-1.amazonaws.com
        prefix: tempo
      wal:
        path: /tmp/tempo/wal
  global_overrides:
    per_tenant_override_config: /conf/overrides.yaml
    
  overrides:
    '*':
      ingestion:
        burst_size_bytes: 40000000 # ~40mb
        rate_limit_bytes: 30000000 # ~30 mb
        max_traces_per_user: 0     # unlimited
      global:
        max_bytes_per_trace: 5000000 # ~5mb

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
  reportingEnabled: false

serviceMonitor:
  enabled: true
  interval: 30s
  additionalLabels:
    release: prometheus

# we use s3 bucket
# although we may want to use /var/tempo persistent storage as it keeps WAL file in that folder
persistence:
  enabled: false

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
         - key: grafana
           operator: In
           values:
           - 'true'
```

#### pod tempo-0 /conf/tempo.yaml file

```sh
✗  k exec -ti tempo-0 -- cat /conf/tempo.yaml  

multitenancy_enabled: false
usage_report:
  reporting_enabled: false
compactor:
  compaction:
    block_retention: 72h
distributor:
  receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_binary:
              endpoint: 0.0.0.0:6832
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_http:
              endpoint: 0.0.0.0:14268
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
ingester:
      {}
server:
      http_listen_port: 3100
storage:
      trace:
        backend: s3
        local:
          path: /var/tempo/traces
        s3:
          bucket: project-prod-eks-tempo
          endpoint: s3.dualstack.us-east-1.amazonaws.com
          prefix: tempo
          region: us-east-1
        wal:
          path: /tmp/tempo/wal
querier:
      {}
query_frontend:
      {}
overrides:
      per_tenant_override_config: /conf/overrides.yaml
```

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: helm

```sh
➜ k ice image                                   
PODNAME                          CONTAINER                PULL          IMAGE                                 TAG
tempo-0                          tempo                    IfNotPresent  grafana/tempo                         2.3.0
tempo-opentelemetry-collector-0  opentelemetry-collector  IfNotPresent  otel/opentelemetry-collector-contrib  0.88.0
```

**Additional Context**
