### ISSUE TITLE
Why tempo trace queries are missing after 30min?

### ISSUE THREAD

**Issue by npuichigo** [grafana/tempo#3155]
I use docker-compose to run tempo with grafana, and it works well to show the trace span.
```yaml
  tempo:
    image: grafana/tempo:2.1.1
    command:
      - "-target=all"
      - "-storage.trace.backend=local"
      - "-storage.trace.local.path=/var/tempo"
      - "-ingester.complete-block-timeout=240h"
      - "-ingester.max-block-duration=240h"
      - "-auth.enabled=false"
    volumes:
      - tempo-data:/var/tempo
    ports:
      - "14250:14250"
    depends_on:
      - loki
    logging: *default-logging
    restart: on-failure

volumes:
  tempo-data:
    driver: local
```
However, after about 30mins, I cannot find previous trace spans before 30mins ago.
![image](https://github.com/grafana/tempo/assets/11533479/9a79799d-8b28-4502-8b74-e7adc2e159b9)

I tried to set ingester parameters but failed. Any idea about this?
