### ISSUE TITLE
Aggregate by feature

### ISSUE THREAD

**Issue by muratyarali** [grafana/tempo#3249]
Hello,

Try to set the "Aggregate by" feature for our Tempo and in the documentation says;

- Enable the metricsSummary feature toggle in Grafana to use this feature. Your Grafana Tempo data source must also point to a Tempo database with the Metrics Summary API enabled.

So I have 2 tasks here; Enable the metricsSummary in Grafana and Enable the MetricsSummaryAPI in Tempo.

1. The first task is done according to documentation. It says to add these lines to grafana.ini;
[feature_toggles]
enable
Keys of features to enable, separated by space.

So I added these lines to grafana.ini in Grafana values.yaml file as  (... represents other lines);

```
...
grafana:
  image:
    registry: docker.io
    repository: grafana/grafana
  grafana.ini:
    feature_toggles:
      enable: metricsSummary tempoServiceGraph traceToMetrics
...
```

and saw the result in /etc/grafana/grafana.ini file in the grafana pod.
```
...
[feature_toggles]
enable = metricsSummary tempoServiceGraph traceToMetrics
...
```

2. About the second task, the documentation says;

To enable the experimental metrics summary API, you must turn on the local blocks processor in the metrics generator.

```
  overrides:
    defaults:
       metrics_generator:
         processors: [..., 'local-blocks']
```

So I added these lines to tempo values.yaml as following and I applied with helm.
```
...
tempo:
  repository: docker.io/grafana/tempo
...
  metricsGenerator:
    # -- If true, enables Tempo's metrics generator (https://grafana.com/docs/tempo/next/metrics-generator/)
    enabled: true
    remoteWriteUrl: "http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
...
  global_overrides:
    per_tenant_override_config: /conf/overrides.yaml
    defaults:
      metrics_generator:
        processors: [ 'service-graphs', 'span-metrics', 'local-blocks' ]
  overrides: {}
...
config: |
    multitenancy_enabled: {{ .Values.tempo.multitenancyEnabled }}
...
    overrides:
      {{- toYaml .Values.tempo.global_overrides | nindent 6 }}
      {{- if .Values.tempo.metricsGenerator.enabled }}
    metrics_generator:
          storage:
            path: /tmp/tempo/generator/wal
            remote_write:
              - url: {{ .Values.tempo.metricsGenerator.remoteWriteUrl }}
          traces_storage:
            path: /tmp/tempo/generator/traces
      {{- end }}
```

and I saw the tempo.yaml file in /conf/ directory in the Tempo pod like;

```
...
overrides:
      defaults:
        metrics_generator:
          processors:
          - service-graphs
          - span-metrics
          - local-blocks
      per_tenant_override_config: /conf/overrides.yaml
metrics_generator:
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write
      traces_storage:
        path: /tmp/tempo/generator/traces
```
            
After these configurations, I restarted tempo and Grafana pods. I can see "processors: ['local-blocks']" is activated in the config file from inside of the pod. But still, I haven't seen the Aggregate by feature in my Tempo search tab.

and When I send a request to the endpoint on the query-frontend, I am taking this error

`curl http://<tempo>/api/metrics/summary`

error querying generators in Querier.SpanMetricsSummary: failed to get response from generators: failed to execute f() for 127.0.0.1:9095: rpc error: code = Unknown desc = parsing groupby attribute: tag name is not valid intrinsic or scoped attribute:

Do you have any idea which part is missing in my configuration?
