### ISSUE TITLE
Span metrics dimension mappings should include non-mapped dimension as well

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#3256]
**Describe the bug**

_Example situation: ingested traces have a mixture of old and new OTel conventions, e.g. some spans have `http.status_code` while others send the newer `http.response.status_code`. For consistency the span metrics combines both fields into a single label `http_response_status_code`._

So we want to use dimension mapping to map `http.status_code` to `http.response.status_code` such that:
- for spans that have `http.response.status_code`, use that value
- for spans that have `http.status_code`, map it to `http_response_status_code`

Example config:

```yaml
metrics_generator:
  processor:
    span_metrics:
        dimensions:
        dimension_mappings:
            - name: http_response_status_code
              source_labels:
                - http.status_code
              join: ""
```

This will make the processor search each span for the `http.status_code` attribute (source) and add it as `http_response_status_code` to the metrics.

Dimension mapping works well but the metrics will only have `http_response_status_code` when it is mapped from `http.status_code`. It does not pick up spans that already use `http.response.status_code` correctly.

---

_Potential_ workaround: add it as a dimension:

```yaml
# ...
metrics_generator:
  processor:
    span_metrics:
        dimensions:
          - http.response.status_code
        dimension_mappings:
            - name: http_response_status_code
              source_labels:
                - http.status_code
              join: ""
```

This might add the label twice to the samples, I'm not sure if this would break something down the line 🤔 

**To Reproduce**
1. Run Tempo with span metrics processor enabled
2. Send spans that have a mixture of `http.status_code` and `http.response.status_code` attributes
3. Analyse the metrics coming out

**Expected behavior**

When I add a dimension map from attribute `foo` to `bar`, I expect spans that only have the new attribute `bar` to also show up as metric label.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**
