### ISSUE TITLE
Allow for images to run as non-root

### ISSUE THREAD

**Issue by wiardvanrij** [grafana/tempo#334]
**Is your feature request related to a problem? Please describe.**
In the baseline: security. It could pose as a serious security concern.
Do we need to run as root? No.

Especially in enterprise environment, we are simply not even allowed to run images as root. Therefore I would like to see a fix.

**Describe the solution you'd like**
Add users to the docker images, perhaps change a few paths (i.e. placement of the executables).

**Describe alternatives you've considered**

The compactor can be used with the following workaround:

```
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
        - mountPath: /var/tempo
          name: tempo  
      volumes:
      - name: tempo
        emptyDir: {}

```
By adding an emptydir we override the /var/tempo folder as non-root. 

For the querier we can do the same "trick" for the /var/tempo folder BUT it also wants to write and use files in the `/tmp` folder. This is an issue because we cannot mount an empty dir on the `/tmp` folder. This is because the original `/tmp` folder contains the `tempo-query` executable.

The real dodgy workaround is to build an image with `tempo-query` in a different place. I.e.: 

```
FROM  tempo-query:latest
COPY tempo-query /tempo-query 
```

Then use an initcontainer:

```
      initContainers:
      - name: please-no
        image: busybox
        command: ['sh', '-c', 'ln -s /tempo-query /tmp/tempo-query']
        volumeMounts:
          - name: tmp
            mountPath: /tmp
```

while having the following emptydir mounts:

```
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /conf
          name: tempo-query-conf         
      volumes:
      - name: tempo
        emptyDir: {}
      - name: tmp
        emptyDir: {}
```

**Additional context**

The workaround is fine for a proof of concept, but not production usage :)
