### ISSUE TITLE
TLS not working in tempo 

### ISSUE THREAD

**Issue by samyak335** [grafana/tempo#3478]
**Describe the bug**
When TLS is enabled in tempo , observing below error continuously in pod logs and logs show grpc 3100 is started on http  

> level=info ts=2024-03-11T09:01:30.803116066Z caller=server.go:228 msg="server listening on addresses" http=[::]:3100 grpc=[::]:9095
> 
> error:
> level=info ts=2024-03-11T09:01:30.829038354Z caller=tempodb.go:399 msg="compaction and retention enabled."
> level=info ts=2024-03-11T09:01:30.829080668Z caller=worker.go:180 msg="adding connection" addr=127.0.0.1:9095
> level=error ts=2024-03-11T09:01:30.830097384Z caller=frontend_processor.go:63 msg="error contacting frontend" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: EOF\""

**To Reproduce**
1. Configure below tls configurations in tempo values.yaml

```
> server:
>     # -- HTTP server listen port
>        http_listen_port: 3100
>        tls_cipher_suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
>       tls_min_version: VersionTLS12
>       grpc_tls_config:
>            cert_file: /etc/tempo/cert/example.crt
>            key_file: /etc/tempo/key/example.key
>      http_tls_config:
>           cert_file: /etc/tempo/cert/example.crt
>           key_file: /etc/tempo/key/example.key

> receivers:
>      jaeger:
>        protocols:
>          grpc:
>             endpoint: 0.0.0.0:14250
>          thrift_binary:
>             endpoint: 0.0.0.0:6832
>          thrift_compact:
>             endpoint: 0.0.0.0:6831
>         thrift_http:
>           endpoint: 0.0.0.0:14268
>     opencensus:
>       otlp:
>         protocols:
>           grpc:
>             endpoint: "0.0.0.0:4317"
>              tls:
>                   cert_file: /etc/tempo/cert/example.crt
>                   key_file: /etc/tempo/key/example.key
>            http:
>               endpoint: "0.0.0.0:4318"
>               tls:
>                  cert_file: /etc/tempo/cert/example.crt
>                  key_file: /etc/tempo/key/example.key
> 

> grpc_client_config:
>         tls_enabled: true
>         tls_cert_path: /etc/tempo/cert/example.crt
>         tls_key_path: /etc/tempo/cert/example.key
>         tls_server_name: tempo.trace.svc.cluster.local
>         tls_insecure_skip_verify: true
>         tls_cipher_suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
>         tls_min_version: VersionTLS12
```

2. deploy tempo using values.yaml

**Expected behavior**
GRPC should be listening on https and when otel endpoint 0.0.0.0:4317 should receive traces on https.

**Environment:**
 - Infrastructure: Kubernetes 
 - Deployment tool: helm 

**Additional Context**
i have referred TLS config from https://grafana.com/docs/tempo/latest/configuration/network/tls/ , i want to receive traces using https://ip:4317

**Comment by joe-elliott** [comment]
Are you setting the grpc client config in all 3 places:

https://grafana.com/docs/tempo/latest/configuration/network/tls/#client-configuration

**Comment by samyak335** [comment]
I tried setting the grpc client config in all 3 places , but for `querier.query-frontend.grpc_client_config` i am observing below error  in tempo pod logs while starting.

> failed parsing config: failed to parse configFile /conf/tempo.yaml: yaml: unmarshal errors:
>   line 53: field grpc_client_config not found in type frontend.Config

setting in the values yaml file 

 


>   ingester: {}
> 
>   querier: {}
> 
> 

>   queryFrontend:
>          grpc_client_config:
>                     tls_enabled: true
>                     tls_cert_path: /etc/tempo/cert/example.crt
>                     tls_key_path: /etc/tempo/cert/example.key
>                     tls_server_name: tempo.trace.svc.cluster.local
>                     tls_insecure_skip_verify: true
>                     tls_cipher_suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
>                     tls_min_version: VersionTLS12

**Comment by joe-elliott** [comment]
I do not know much about how the values.yaml interacts with the tempo configuration. Can you share the actual, rendered tempo config? It would be easier for me to help you.

Also the `values.yaml` content you shared is not tabbed properly which also makes it tough to understand what is happening.

My guess, based on your error, is that the `grpc_client_config` is being rendered somewhere into the `query_frontend` config and not under the `querier`.

**Comment by samyak335** [comment]
i have formatted the config in previous comments properly. 
The values.yaml has querier: {} separate and queryFrontend: {}  separate , but in documentation it is said that  `querier.query-frontend.grpc_client_config` which meant like the below .

```
querier: 
     query-frontend:
              grpc_client_config:

```
If i follow same format in values.yaml  
```
ingester_client:
      grpc_client_config:
         tls_enabled: true
         tls_cert_path: /etc/tempo/cert/example.crt
         tls_key_path: /etc/tempo/cert/example.key
         tls_server_name: tempo.trace.svc.cluster.local
         tls_insecure_skip_verify: true
         tls_cipher_suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
         tls_min_version: VersionTLS12
  metrics_generator_client:
       grpc_client_config:
         tls_enabled: true
         tls_cert_path: /etc/tempo/cert/example.crt
         tls_key_path: /etc/tempo/cert/example.key
         tls_server_name: tempo.trace.svc.cluster.local
         tls_insecure_skip_verify: true
         tls_cipher_suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
         tls_min_version: VersionTLS12

querier:
   queryFrontend:
         grpc_client_config:
                    tls_enabled: true
                    tls_cert_path: /etc/tempo/cert/example.crt
                    tls_key_path: /etc/tempo/cert/example.key
                    tls_server_name: tempo.trace.svc.cluster.local
                    tls_insecure_skip_verify: true
                    tls_cipher_suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
                    tls_min_version: VersionTLS12


```
I get this error `failed parsing config: failed to parse configFile /conf/tempo.yaml: yaml: unmarshal errors:
  line 51: field query-frontend not found in type querier.Config` when the tempo pod is starting, and cannot get the rendered config file from the pod as pod is not running state.
`
