### ISSUE TITLE
[DOCS] Outdated documentation setting up a test app

### ISSUE THREAD

**Issue by ausias-armesto** [grafana/tempo#3481]
The documentation located in `/docs/sources/tempo/setup/set-up-test-app.md` is outdated and does not work as it's described in the docs.
I would suggest to fix the `use-opentelemetry-telemetrygen-to-generate-tracing-data` section and in the first step reference the `telemetrygen` repository but include a template of a Pod for generating traces

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-traces
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
          - name: traces
            image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.96.0
            args:
              - traces
              - --otlp-insecure
              - --rate
              - "10"
              - --duration
              - 300s
              - --otlp-endpoint
              - grafana-agent.grafana-agent.svc.cluster.local:4317
          restartPolicy: Never
```

The documentation is not updated as the parameter `--otlp-endpoint` is not set and the user would appreciate the example to be run within Kubernetes, like for instance a Pod, Job or CronJob template.
