### ISSUE TITLE
s3 metrics always increasing

### ISSUE THREAD

**Issue by keyolk** [grafana/tempo#3529]
**Describe the bug**

Its objects and bucket size keep growing and never goes down.

![image](https://github.com/grafana/tempo/assets/96432437/1689b570-a9c4-4ada-8d39-dd11cc24646c)
![image](https://github.com/grafana/tempo/assets/96432437/90589deb-459e-4973-8f4e-ca57e2f018bf)

Also I can see about 5GB parquet datas in each block dir.
![image](https://github.com/grafana/tempo/assets/96432437/abb8f5ed-b1da-45f3-a936-f5d6a1fefb9d)

When I see its log, many lines like the belows from the compactor pods
```
level=warn ts=2024-03-28T01:49:49.036459838Z caller=compactor.go:248 msg="max size of trace exceeded" tenant=mesg traceId=eddc0f76f1d19e6e898d1f2b60b9c431 discarded_span_count=19697
```

and some metrics
![image](https://github.com/grafana/tempo/assets/5329850/4d6c2522-6602-4ca5-875d-c2c6e624f39a)

**To Reproduce**
1. Start Tempo (SHA or version)

```bash
 /tempo -version
tempo, version 2.2.0 (branch: HEAD, revision: cce8df1b6)
  build user:
  build date:
  go version:       go1.20.4
  platform:         linux/arm64
  tags:             unknown
```

```yaml
compactor:
  compaction:
    block_retention: 168h
    compacted_block_retention: 1h
    compaction_cycle: 30s
    compaction_window: 1h
    max_block_bytes: 1073741824
    max_compaction_objects: 600000
    max_time_per_tenant: 5m
    retention_concurrency: 10
    v2_in_buffer_bytes: 5242880
    v2_out_buffer_bytes: 20971520
    v2_prefetch_traces_count: 1000
  ring:
    kvstore:
      store: memberlist
...
storage:
  trace:
    backend: s3
    blocklist_poll: 5m
    cache: memcached
    local:
      path: /var/tempo/traces
    memcached:
      consistent_hash: true
      host: o11y-tempo-memcached
      service: memcached-client
      timeout: 500ms
    s3:
      bucket: tempo-apne2
      endpoint: s3.amazonaws.com
      region: ap-northeast-2
    wal:
      path: /var/tempo/wal
```

**Expected behavior**

s3 obejcts size should be reduced

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: helm `tempo-distributed` v1.6.1

**Additional Context**
