### ISSUE TITLE
Traces are not available after 30 minutes on Windows

### ISSUE THREAD

**Issue by teyyubismayil** [grafana/tempo#3552]
**Describe the bug**
I have simple grafana-agent and tempo setup running on windows as executables. My  application pushes traces through grafana-agent and only traces of last 30 minutes are found when querying. After 30 minutes trace is not available. `404 Not Found Body: trace not found` is returned when searching for trace that is older than 30 minutes.

**To Reproduce**
1. Start Tempo on windows as executable
2. Push traces to tempo
3. Query for trace that is older than 30 minutes

**Expected behavior**
Trace should be found but  `404 Not Found Body: trace not found` is returned.

**Environment:**
 - OS - Windows
 - Tempo version - 2.4.1 amd 64

**Additional Context**
Configuration:
```yml
stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: info
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
compactor:
  compaction:
    block_retention: 24h
storage:
  trace:
    backend: local
    wal:
      path: D:/somefolder/tempo/wal
    local:
      path: D:/somefolder/tempo/blocks
```
