### ISSUE TITLE
Trace data is being generated even though there are no request from service A to service B

### ISSUE THREAD

**Issue by finda-yeongjo** [grafana/tempo#3689]
**Describe the bug**
When monitoring Java applications using OpenTelemetry Java Auto-Instrumentation, the trace data incorrectly shows service A calling service B (A -> B), even though there is no actual call between A to B. 
Based on the concept of microservices, A and B are producing and consuming data through a Kafka topic, maintaining "loose coupling" between each other. This issue is evident in the `traces_service_graph_request_total` metric and the Zipkin trace data, which suggests a relationship that does not exist.
<img width="1699" alt="스크린샷 2024-05-20 오전 10 44 48" src="https://github.com/grafana/tempo/assets/136681927/b5c54961-6681-4e26-b74c-915b45aad73e">

If I enable the following two options in the OpenTelemetry instrumentation, Service A changes to "user," but the data is still identified.
```
      - name: OTEL_INSTRUMENTATION_MESSAGING_RECEIVE_TELEMETRY_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_MESSAGING_SEND_TELEMETRY_ENABLED
        value: "true"
```
<img width="353" alt="스크린샷 2024-05-20 오전 10 41 45" src="https://github.com/grafana/tempo/assets/136681927/5f050dfc-fa87-4569-ba7a-3f8574e7ff47">

I initially raised this issue with the OpenTelemetry team, but their response suggested raising the issue with Grafana and Tempo instead. 
Ref. https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11348

**To Reproduce**

1. Deploy two Java Spring services, A and B, in Kubernetes using the OpenTelemetry Java auto-instrumentation agent with the following configuration:
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: sample-instrumentation
  namespace: test
spec:
  propagators:
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.1"
  java:
    image: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.29.0"
    env:
      - name: OTEL_METRICS_EXPORTER
        value: "prometheus"
      - name: OTEL_METRICS_EXEMPLAR_FILTER
        value: "trace_based"
      - name: OTEL_TRACES_EXPORTER
        value: "zipkin"
      - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
        value: "http://SOME_TEST_OTELCOLLECTOR_ENDPOINT:9411/api/v2/spans"
      - name: OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_REQUEST_HEADERS
        value: "content-type"
      - name: OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_RESPONSE_HEADERS
        value: "content-type"
```
2. Observe the trace data in Tempo (with Grafana)
3. Notice that the trace data incorrectly indicate service A is making requests to service B.
4. Check A->B in Grafana using the service graph or the traces_service_graph_request_total data.
5. Creating and testing a topic that they consume from each other would be more accurate.

**Expected behavior**
The trace data and metrics should accurately reflect the interactions between services. Specifically, no traces or metrics should suggest a direct interaction between service A and service B when there is none.

**Environment:**
 - Infrastructure: AWS EKS, AWS MSK
 - Deployment tool: Using Kubernetes manifests with gitops repo & ArgoCD

**Additional Context**
All services are deployed as pods in EKS.
The issue persists even after verifying that there are no overlapping or contaminated headers and that Trace IDs are unique and correctly configured.
The environment configuration for OpenTelemetry instrumentation includes settings for exporting to Prometheus and Zipkin, capturing content-type headers for HTTP requests and responses.

Service A
JDK: Amazon Corretto 17
Spring: 2.7.1
OS: Amazon Linux (EKS)

Service B
JDK: Amazon Corretto 17
Spring: 3.0.5
OS: Amazon Linux (EKS)
