### ISSUE TITLE
Timeout & cache on metrics generator local-blocks processor

### ISSUE THREAD

**Issue by icemanDD** [grafana/tempo#3768]
**Describe the bug**
When onboard metrics generator local-blocks processor(Aggregate by), it always timeout for for the first query but would load the results for the second query or third query, and we did not set any cache layer.
Is there any local cache for this feature?
How should we optimize query-frontend, querier and metrics generator to get local-blocks working on millions of spans?

**To Reproduce**
tempo config:
```
query_frontend:
  max_outstanding_per_tenant: 300000
  max_retries: 2
  max_batch_size: 5
  metrics:
    concurrent_jobs: 300000 # also tried: 2000, 200
    target_bytes_per_job: 2.25e+07 # also tried: 2.25e+08, 1.25e+09
```
```
querier:
  max_concurrent_queries: 1500
  query_relevant_ingesters: true
...
  metrics:
    concurrent_blocks: 1500
    time_overlap_cutoff: 0.0
```
```
metrics_generator:
  ...
  processor:
    local_blocks:
      search:
        prefetch_trace_count: 10000
      block:
        search_page_size_bytes: 5000000
        parquet_row_group_size_bytes: 500000000
        bloom_filter_shard_size_bytes: 1000000
      filter_server_spans: false
      complete_block_timeout: 1h
      concurrent_blocks: 200

```
use async iterator is not helpful:
VPARQUET_ASYNC_ITERATOR="1"

**Environment**
Tempo 2.4.2

**Expected behavior**
local-blocks could return results in less 10-15 secs with the proper configuration, or only return the queried data in 10-15 secs instead of trigger the timeout
