### ISSUE TITLE
[DOC] Update overrides content  in Helm chart to clarify configuration for new, legacy

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/tempo#3820]
Update the overrides configuration documentation to address changes to the Overrides module. The configuration examples need to be checked to make sure they are for the updated overrdies and which ones are not. 

Update these pages: 
* https://grafana.com/docs/tempo/latest/release-notes/v2-3/#changes-to-the-overrides-module-configuration

The configuratio file in this doc works, but it's a YAML file: 
"A snippet of a config.yaml file showing how the overrides section is [here](https://github.com/grafana/tempo/blob/a000a0d461221f439f585e7ed55575e7f51a0acd/integration/bench/config.yaml#L39-L40). 

Reference: https://github.com/grafana/tempo/issues/3795, https://github.com/grafana/helm-charts/issues/2802#issuecomment-2461246589
* You need per-tenant overrides. Same format in both overrides configs
* How does Tempo tell which configuration is new and which one is legacy? 

### Notes
Same issue happens in the tempo-distributed Helm chart:
```
global_overrides:
  defaults:
    metrics_generator:
      processors:
        - span-metrics
      processor:
        span_metrics:
          histogram_buckets: [null]
          dimensions:
            - kubernetes_cluster
            - kubernetes.cluster
            - http.status_code
``` 

As a rule of thumb: long, unindented params are legacy (eg. `metrics_generator_forwarder_queue_size`), indented params are new (eg. `metrics_generator.forwarder.queue_size`).

With the new config, a new key defaults was also added after the overrides key, to be more explicit of the contents of the config block.

Finally, there is a [command in the tempo-cli](https://grafana.com/docs/tempo/latest/operations/tempo_cli/#migrate-overrides-config-command) that allows you to convert legacy config to new overrides config.
