### ISSUE TITLE
Guidance on traceql metrics timeout issue

### ISSUE THREAD

**Issue by icemanDD** [grafana/tempo#3896]
**Describe the bug**
As the follow up of https://github.com/grafana/tempo/issues/3768 we want to understand how to configure traceql metrics related components to get results for 15min-30min window during last week or two weeks without timeout.

We notice the querier CPU and MEM spike when query traceql metrics for 4 days ago 5mins window, is there a guidance on updating querier + frontend(maybe also metrics generator) to get it work?

**To Reproduce**
tempo config:
```
query_frontend:
  max_outstanding_per_tenant: 300000
  max_retries: 2
  max_batch_size: 5
  metrics:
    concurrent_jobs: 300000 # also tried: 2000, 200
    target_bytes_per_job: 2.25e+07 # also tried: 2.25e+08, 1.25e+09

  search:
    concurrent_jobs: 30000 #also tried 300000 
    target_bytes_per_job: 20971520 # also tried 2097152
    max_duration: 720h
```
```
querier:
  max_concurrent_queries: 1500
  query_relevant_ingesters: true
...
  metrics:
    concurrent_blocks: 1500
    time_overlap_cutoff: 0.0
```
```
metrics_generator:
  ...
  processor:
    local_blocks:
      search:
        prefetch_trace_count: 10000
      block:
        search_page_size_bytes: 5000000
        parquet_row_group_size_bytes: 500000000
        bloom_filter_shard_size_bytes: 1000000
      filter_server_spans: false
      complete_block_timeout: 1h
      concurrent_blocks: 200

```

**Expected behavior**
When query traceql metrics for any <30mins window for last week or 2 weeks, Tempo could return results in 30s without timeout issue.

**Additional Context**
example on data.parquet:
```
  File: data.parquet
  Size: 184291173       Blocks: 359952     IO Block: 4096   regular file
  Inode: 1308506     Links: 1
```
