### ISSUE TITLE
generator push to prometheus pushgateway always fails "HTTP status 400 Bad Request: snappy: corrupt input"

### ISSUE THREAD

**Issue by andrewbulin** [grafana/tempo#3921]
**Describe the bug**

Tempo metrics-generator always failed to push to Prometheus push gateway with a snappy error:

`ts=2024-07-30T08:40:27.386622385Z caller=dedupe.go:112 tenant=single-tenant component=remote level=error remote_name=f56174 url=http://prometheus-for-amp-prometheus-pushgateway.prometheus.svc.cluster.local:9091/metrics/job/tempo-metrics-generator msg="non-recoverable error" count=1099 exemplarCount=0 err="server returned HTTP status 400 Bad Request: snappy: corrupt input"`

Any tips or recommendations to help debug this would be appreciated.

**To Reproduce**

* Tempo installed via Helm `grafana/tempo-distributed`, version 2.5.0
* Prometheus PushGateway installed via Helm `prometheus-community/prometheus`, version v2.53.1
* Also can be reproduced locally using this repo's `example/docker-compose/distributed/` with small tweaks, see [this comment below](https://github.com/grafana/tempo/issues/3921#issuecomment-2259421096) for details and a diff.

Helm tempo values for `metrics-generator`:

```
metricsGenerator:
  enabled: true
  kind: Deployment
  replicas: 1
  terminationGracePeriodSeconds: 300
  persistence:
    enabled: false
  walEmptyDir: {}
  ports:
    - name: grpc
      port: 9095
      service: true
    - name: http-memberlist
      port: 7946
      service: false
    - name: http-metrics
      port: 3100
      service: true
  config:
    registry:
      collection_interval: 15s
      stale_duration: 15m
    storage:
      path: /var/tempo/wal
      wal:
        wal_compression: "snappy"
      remote_write_flush_deadline: 1m
      remote_write:
        - url: "http://prometheus-for-amp-prometheus-pushgateway.prometheus.svc.cluster.local:9091/metrics/job/tempo-metrics-generator"
    traces_storage:
      path: /var/tempo/traces
    metrics_ingestion_time_range_slack: 30s
```

**Expected behavior**

Metrics should just push.

I can confirm from inside the cluster that push completes from the `tempo` namespace, via cURL:

`echo "some_metric 3.14" | curl --data-binary @- http://prometheus-for-amp-prometheus-pushgateway.prometheus.svc.cluster.local:9091/metrics/job/tempo-metrics-generator`

```
~ $ curl -s http://prometheus-for-amp-prometheus-pushgateway.prometheus.svc.cluster.local:9091/metrics | grep tempo-metrics-generator
push_failure_time_seconds{instance="",job="tempo-metrics-generator"} 0
push_time_seconds{instance="",job="tempo-metrics-generator"} 1.7223294456839218e+09
some_metric{instance="",job="tempo-metrics-generator"} 3.14
```

**Environment:**
 - Infrastructure: Kubernetes 1.25 via AWS EKS
 - Deployment tool: Helm
