### ISSUE TITLE
AWS S3 HTTP 4xx client errors

### ISSUE THREAD

**Issue by icemanDD** [grafana/tempo#3924]
**Describe the bug**
Constantly see 4xx errors (~20% total requests) in AWS S3 buckets for tempo storage. 
Example error:
`REST.GET.OBJECT tempo_cluster_seed.json "GET /tempo_cluster_seed.json HTTP/1.1" 400 InvalidArgument 432 - 17 - "-" "MinIO (linux; amd64) minio-go/v7.0.70"`

<img width="542" alt="Screenshot 2024-07-30 at 2 50 46 PM" src="https://github.com/user-attachments/assets/ebe4632a-bca3-43a0-8910-44191202a05f">

**To Reproduce**
1. Start Tempo micro service mode with latest docker image
2. Send traffic to AWS S3 storage and configure compactor for compaction

**Expected behavior**
No or minimal 4xx error rates for S3 requests.

**Additional Context**
```
compactor:
  ring:
    kvstore:
      store: memberlist
    instance_id: 'tempo-compactor-{RANDOM_ID}'
    instance_interface_names:
      - ...
  compaction:
    block_retention: 720h
```
