### ISSUE TITLE
Document the overrides configuration (global and per-tenant) with examples

### ISSUE THREAD

**Issue by herrbpl** [grafana/tempo#395]
**Describe the bug**

Suddenly, distributor failed to accept traces with error messages:
"max live traces per tenant exceeded: per-user traces limit (local: 10000 global: 0 actual local: 10000) exceeded"

There seem to be no documentation about anything on it (and Tempo documentation is severly lacking, certainly not production-level documentation!). 

**To Reproduce**
1. Start Tempo (SHA ):

Used docker image grafana/tempo:latest

> ./tempo -version
> tempo, version  (branch: , revision: )
>   build user:       
>   build date:       
>   go version:       go1.15.3

2. Perform Operations (Read/Write/Others)
Just ingest certain amount of traces and it starts to happen.

**Expected behavior**
traces are being processed

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm, improved version of available chart (which also does not really work)

**Additional Context**
Using jaeger http trift for this particular ingest, with default config. 

/ # cat /conf/tempo.yaml 
```yaml
auth_enabled: false
compactor: null
distributor:
  receivers:  
    jaeger:
      protocols:        
        thrift_http: 
        grpc: 
    opencensus:  
    zipkin: 
    otlp: 
      protocols: 
        http: 
        grpc: 
          endpoint: 0.0.0.0:55689
#          keepalive:
#            server_parameters:
#              max_connection_idle: 11s
#              max_connection_age: 12s
#              max_connection_age_grace: 13s
#              time: 30s
#              timeout: 5s
#            enforcement_policy:
#              min_time: 10s
#              permit_without_stream: true
ingester:
  lifecycler:
    ring:
      replication_factor: 2
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - gossip-ring.tempo.svc.cluster.local:7946
overrides:
  per_tenant_override_config: /conf/overrides.yaml
server:
  http_listen_port: 3100
storage:
  trace:
    backend: s3
    s3:
      access_key: xxxxxxxxxxxxxxxxxxxxxx
      bucket: xxxxxxxxxxxxxxxxxxxxxx
      endpoint: xxxxxxxxxxxxxxxxxx
      insecure: false
      region: eu-central-1
      secret_key: xxxxxxxxxxxx
    blocklist_poll: 5m
    memcached:
      consistent_hash: true
      host: memcached
      service: memcached-client
      timeout: 500ms
    pool:
      queue_depth: 2000
    wal:
      path: /var/tempo/wal/
```

**Comment by herrbpl** [comment]
Needless to say, we really bought Tempo on its ability to ingest "almost unlimited" amount of traces. But it is not production ready product, not with this level of documentation and deployment chart bugs.

**Comment by herrbpl** [comment]
Full reference config file with comments would be a good start. Elasticsearch does stellar work for example to provide reference config file with all options described, including function and defaults..

**Comment by annanay25** [comment]
Hi @herrbpl; sorry about the issues you faced. We definitely have some work to do on the documentation front; I'm just writing up an operation guide together with @achatterjee-grafana that can help debug these issues. 

For now, adding the following configuration parameter should do the trick - https://github.com/grafana/tempo/blob/a000a0d461221f439f585e7ed55575e7f51a0acd/integration/bench/config.yaml#L39-L40

We also have a commented example config in the `example/docker-compose/etc/tempo-local.yaml` location, but I agree it needs a lot more work. Thank you for reporting this.

**Comment by herrbpl** [comment]
Thanks for quick feedback. 
I am not familiar with Go, so my hunt to search for fix in configuration file was unsuccessful until you gave that example
Thanks again.

**Comment by annanay25** [comment]
No problem, all the best and I hope this works for your use case!

**Comment by annanay25** [comment]
Leaving this issue open to track the documentation task.

**Comment by joe-elliott** [comment]
You are currently hitting the [maximum number of live traces](https://github.com/grafana/tempo/blob/3710d944cfe2a51836c3e4ef4a97316ed0526a58/modules/overrides/limits.go#L25) allowed per tenant in the ingester here:

https://github.com/grafana/tempo/blob/3710d944cfe2a51836c3e4ef4a97316ed0526a58/modules/ingester/instance.go#L291-L294

This maximum is just a failsafe to prevent one tenant from negatively impacting others.  Traces are flushed from live traces into a block once the [max traces idle duration](https://github.com/grafana/tempo/blob/3710d944cfe2a51836c3e4ef4a97316ed0526a58/modules/ingester/config.go#L19) passes with no new spans received for this trace.  

The default live traces is 10000 and the default max trace idle is 30 seconds.  Out of curiosity did you increase the max trace idle?  Are your traces particularly long lived?  I'm wondering if we should increase the default.

**Comment by herrbpl** [comment]
Hi,

I indeed increased number for  user, it is currently unclear how to set up different tenants so i guess it is used for all connections.

Our case was sudden increase in requests volume to our service which probably caused this to happen. Traces usually don't have long life for us but some requests have async interactions with other services in same cluster or outside of it, this may indeed exceed 30s

**Comment by joe-elliott** [comment]
The active traces timeout is useful for a number of different things.  It's ok if your request exceeds 30s it should still all be stored and returned on query.

Active trace timeout is more for:
- batch writes to wal
- best effort combination of all spans into one block to improve query performance

I'm glad to hear your issue is resolved.  For future readers you could also could have scaled up ingesters.  That 10k limit is per ingester.

Also, to configure per tenant overrides you first need to add a reference to an overrides file.  This file is reloaded dynamically on change and so ingesters/distributors do not need to be restarted to apply it:

```
overrides:
    per_tenant_override_config: /conf/overrides.yaml
```

And then the overrides yaml would look something like:

```
overrides:
    "<tenant id>":
        ingestion_max_batch_size: 5000
        ingestion_rate_limit: 400000
        max_spans_per_trace: 250000
        max_traces_per_user: 100000
```

Let's make sure to document this when closing this ticket.
