### ISSUE TITLE
Add `tolerations` to memcached service on Helm Chart values

### ISSUE THREAD

**Issue by ecurbelo** [grafana/tempo#4030]
**Is your feature request related to a problem? Please describe.**
I installed Tempo (microservices mode) in a Kubernetes cluster via Helm Chart.

I want to deploy all Tempo pods on the EKS node group that I have exclusively for monitoring purposes. I added the following configuration on the rest of the components (distributor, ingester, etc), but only on the memcached tool there is not `tolerations` settings on the [helm chart values file](https://github.com/grafana/helm-charts/blob/tempo-distributed-1.17.0/charts/tempo-distributed/values.yaml#L1493).

Configuration:
```
    affinity: |
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-type
                  operator: In
                  values:
                    - monitoring
    tolerations:
      - key: monitoring
        value: dedicated
        operator: Equal
        effect: NoSchedule
```

**Describe the solution you'd like**
Have the possibility to configure `tolerations` in the memcached service using Helm Chart values.

**Describe alternatives you've considered**
None.

**Additional context**
None.
