### ISSUE TITLE
Trace can not be fetched after flush to storage

### ISSUE THREAD

**Issue by zhaoyao** [grafana/tempo#408]
**Describe the bug**
The trace can be correctly queried in the first few minutes after it is generated. After about 5 minutes, tempo-query will display 404 Not Found.

After checking the trace of the tempo read path, we can also find that when the trace can be queried from the ingestor, the query can be successful. When entering the storage read path, query trace will return 404.

The trace valid duration is the same as `ingester.complete_block_timeout`.

Can you give some follow-up troubleshooting suggestions?

**To Reproduce**
1. Start Tempo (tempo, version e9892bd7 (branch: master, revision: e9892bd7))
2. Perform Operations (Read/Write/Others)

**Expected behavior**
Trace can be fetched after ingestor flush blocks to storage.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: manually

**Additional Context**
I use ceph as s3 storage backend.

I deployed tempo using microservice mode:
- tempo-distributor: unstateful deployment
- tempo-ingestor: statefulset
- tempo-querier: statefulset
- tempo-query: unstateful deployment

Full tempo.yml shared between all components.
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  log_level: debug

distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
      protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver
        thrift_http:                   #
        grpc:                          # for a production deployment you should only enable the receivers you need!
        thrift_binary:
        thrift_compact:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:

ingester:
  trace_idle_period: 10s               # the length of time after a trace has not received spans to consider it complete and flush it
  traces_per_block: 100                # cut the head block when it his this number of traces or ...
  max_block_duration: 5m               #   this much time passes
  lifecycler:
    ring:
      kvstore:
        store: etcd
        etcd:
          endpoints: 
            - http://****:2379


compactor:
  compaction:
    compaction_window: 1h              # blocks in this time window will be compacted together
    max_compaction_objects: 1000000    # maximum size of compacted blocks
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: s3                     # backend configuration to use
    wal:
      path: /data/tempo/wal             # where to store the the wal locally
      bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
      index_downsample: 10             # number of traces per index record
    s3:
      bucket: ***
      endpoint: ***
      access_key: ****
      secret_key: ****
      insecure: true
    pool:
      max_workers: 100                 # the worker pool mainly drives querying, but is also used for polling the blocklist
      queue_depth: 10000

```
