### ISSUE TITLE
Tempo not working with AWS S3 (Unknown Backend)

### ISSUE THREAD

**Issue by mateusamorim96** [grafana/tempo#4125]
I'm trying to use GLTM + OpenTelemetry + Prometheus using EKS but I'm getting issues to have Tempo working.
Tempo logs:

level=info ts=2024-09-24T12:51:56.34860946Z caller=main.go:226 msg="initialising OpenTracing tracer"
level=info ts=2024-09-24T12:51:56.351658518Z caller=main.go:119 msg="Starting Tempo" version="(version=2.6.0, branch=HEAD, revision=e85bbc57d)"
level=error ts=2024-09-24T12:51:56.352240713Z caller=main.go:122 msg="error running Tempo" err="failed to init module services: error initialising module: store: failed to create store: unknown backend "

Template used:
```YAML
{{- if.Values.tempo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 8080
      http_grpc_port: 9095
    storage:
      trace:
        backend: s3
        s3:
        {{- if eq .Values.environment "prod"}}
          bucket: {{ .Values.prod.bucket }}
          endpoint: s3.{{ .Values.prod.region }}.amazonaws.com
          region: {{ .Values.prod.region }}
        {{- else }}
          bucket: {{ .Values.np.bucket_no_arn }}
          endpoint: s3.{{ .Values.np.region }}.amazonaws.com
          region: {{ .Values.np.region }}
        {{- end }}
        wal:
          path: /storage/tempo/wal
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
    ingester:
      trace_idle_period: 10s  
      max_block_bytes: 1_000_000  
      max_block_duration: 1m  
    compactor:
      compaction:
        compaction_window: 1h             
        max_compaction_objects: 1000000   
        block_retention: 1h
        compacted_block_retention: 10m
        flush_size_bytes: 5242880
{{- end }}
```

I created a role in AWS with s3:* permissions and assigned to the pod via service-account and tested if it was working by deploying a pod with AWS-CLI.

Tempo image used: 2.6.0

I don't know what I'm missing here since I found basically the same structure in the documentation and in another examples.
