### ISSUE TITLE
[DOC] Add doc for filter_server_spans and update TraceQL metrics config doc

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/tempo#4139]
Ats Uiboupin reported an issue getting TraceQL metrics to work correctly. We should up the docs to clarify TraceQL metrics configuration. 

Ats installed using tempo-distributed Helm chart. 

To fix: 

* Update [Local-blocks processor config](https://grafana.com/docs/tempo/latest/operations/traceql-metrics/#activate-and-configure-the-local-blocks-processor) - uses outdated configuration format (changed in 2.6.-- see comment below)
* If using the tempo-distributed, need to make sure that it's deploying metrics-generators (might not by default)
* Add `flush_to_storage` (not `filter_server_spans`) documentation to [configuration/#metrics-generator](https://grafana.com/docs/tempo/latest/configuration/#metrics-generator)

**Comment by knylander-grafana** [comment]
Original context from the community Tempo Slack channel:

[TraceQL metrics queries feature (introduced in 2.4)](https://grafana.com/docs/tempo/latest/release-notes/v2-4/#traceql-metrics-experimental) working even with the simplest possible query like {} | rate() as mentioned by 
[@Joe Elliott](https://grafana.slack.com/team/UMYCXETNY)
 in the video at [0:22](https://youtu.be/EYUx2DkNRas?t=22).
For me it results in
```
Query error
Error (error finding generators in Querier.queryRangeRecent: empty ring ). Please check the server logs for more details.
```
There was no reference to additional configuration needed for this feature neither in 2.4 [release notes](https://grafana.com/docs/tempo/latest/release-notes/v2-4) nor [upgrade instructions](https://grafana.com/docs/tempo/latest/setup/upgrade/#upgrade-to-tempo-24), but i found [Configure TraceQL metrics](https://grafana.com/docs/tempo/latest/operations/traceql-metrics/) page, and i activated loacl-blocks processor based on [this documentation](https://grafana.com/docs/tempo/latest/operations/traceql-metrics/#activate-and-configure-the-local-blocks-processor) and configured the processor exactly like [documented here](https://grafana.com/docs/tempo/latest/operations/traceql-metrics/#configure-the-processor), but I still see the same error (as seen in the screenshot).

First part of the error (error finding generators in Querier.queryRangeRecent:) comes from [these lines](https://github.com/grafana/tempo/blob/807435d38ac5b78c5626d05d74eb0715081f1066/modules/querier/querier_query_range.go#L30-L32), and empty ring part of the error from [these lines](https://github.com/grafana/tempo/blob/v2.6.0/vendor/github.com/grafana/dskit/ring/ring.go#L505-L506).

Server logs don't contain any additional information that could help me in this case (found 2 lines from querier and 2 lines from query-frontend).

**Comment by knylander-grafana** [comment]
**Update the local-blocks processor config** 

Update this page - https://grafana.com/docs/tempo/latest/operations/traceql-metrics/#activate-and-configure-the-local-blocks-processor

That doc uses deprecated override configuration format (that would fail Tempo startup if rest of the conf is using new format), but i changed it according to [2.6 release notes (Operational change for TraceQL metrics)](https://grafana.com/docs/tempo/latest/release-notes/v2-6/#operational-change-for-traceql-metrics):

**Comment by knylander-grafana** [comment]
Also from Ats: 

thanks for [that link](https://grafana.com/docs/tempo/latest/release-notes/v2-6/#operational-change-for-traceql-metrics). I had seen it and I had previously applied everything except "For historical data" conf part, that i missed somehow, as i followed quite similar instructions on [Configure TraceQL metrics](https://grafana.com/docs/tempo/latest/operations/traceql-metrics/#activate-and-configure-the-local-blocks-processor) page, that has additional conf block:
```
  storage:
    path: /var/tempo/generator/wal
  traces_storage:
    path: /var/tempo/generator/traces
but that page didn't mention
flush_to_storage: true
```
from the page you linked to. I added it now as well, but i have to say that it seems to me that `filter_server_spans` isn't documented - i'd expect it to be documented in [configuration/#metrics-generator](https://grafana.com/docs/tempo/latest/configuration/#metrics-generator). I guess that was accidentally left undocumented?

**Comment by atsu85** [comment]
thanks @knylander-grafana for converting this into an issue!

> it seems to me that filter_server_spans isn't documented - i'd expect it to be documented in [configuration/#metrics-generator](https://grafana.com/docs/tempo/latest/configuration/#metrics-generator)
Uups, i meant `flush_to_storage`. Perhaps you can update [this comment](https://github.com/grafana/tempo/issues/4139#issuecomment-2380363276) to avoid confusion?

**Comment by gpcmol** [comment]
This is how it works for us:

```
tempo-distributed:
  gateway:
    enabled: true
  global:
    image:
      registry: docker.example.com
  minio:
    enabled: true
  traces:
    otlp:
      http:
        enabled: true
      grpc:
        enabled: true
  distributor:
    config:
      log_received_spans:
        enabled: true
  global_overrides:
    metrics_generator_processors:
      - service-graphs
      - span-metrics
      - local-blocks
  metricsGenerator:
    enabled: true
    config:
      processor:
        local_blocks:
          flush_to_storage: true
```
