### ISSUE TITLE
Ownership of file not changed after the upgrade from 2.4.1 to 2.6.0

### ISSUE THREAD

**Issue by snyaik** [grafana/tempo#4290]
Hi All, 

I have recently tried upgrading the tempo distributed from 2.4.1 to 2.6. 
One of the breaking change is the change in the ownership of the directory in var/tempo to user and group _**tempo**_.

After the upgrade I can see the ownership is only for the group. 
I in the helm values file, I have added the securityContext and podSecurityContext. 
Snippet of the config is mentioned below. 
Also, just adding the securityContext did not update the ownership. 
Please advise if there is anything else I have missed for the update. 
I have followed the discussion on PR: https://github.com/grafana/tempo/pull/2265 

```
tempo:
    image:
      # -- The Docker registry
      registry: docker.io
      # -- Optional list of imagePullSecrets. Overrides `global.image.pullSecrets`
      pullSecrets: []
      # -- Docker image repository
      repository: grafana/tempo
      # -- Overrides the image tag whose default is the chart's appVersion
      tag: null
      pullPolicy: IfNotPresent
    readinessProbe:
      httpGet:
        path: /ready
        port: http-metrics
      initialDelaySeconds: 30
      timeoutSeconds: 1
    # -- Global labels for all tempo pods
    podLabels: {}
    # -- Common annotations for all pods
    podAnnotations: {}
    # -- SecurityContext holds container-level security attributes and common container settings
    securityContext:
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    # -- podSecurityContext holds pod-level security attributes and common container settings
    podSecurityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsUser: 10001
```
