### ISSUE TITLE
S3-compatible storage: support S3ForcePathStyle and expanded configs

### ISSUE THREAD

**Issue by tonychoe** [grafana/tempo#431]
**Is your feature request related to a problem? Please describe.**

S3-compatible storages require [s3ForcePathStyle](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#s3ForcePathStyle-property). Additionally [Oracle Object Storage](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm#Supported_Amazon_S3_Clients) requires a region identifier to use other than a home region.

Currently, Tempo doesn't allow these configurations, therefore we cannot use some S3-compatible storages as Tempo's storage.

**Describe the solution you'd like**

Allow passing `s3forcepathstyle` and `region` to the S3 SDK used in Tempo, as the following example config:
```
    s3:
      s3forcepathstyle: true
      bucket: tempo 
      region: us-phoenix-1
      endpoint: endpoint1234.compat.objectstorage.us-phoenix-1.oraclecloud.com      access_key: tempo
      secret_key: supersecret
      insecure: false
```

As you may know, Loki has been [supporting the S3-compatible storage, a region identifier and more](https://github.com/grafana/loki/blob/master/docs/sources/configuration/examples.md#s3-compatible-apis). Perhaps Loki's code could be re-used to implement this feature.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
