### ISSUE TITLE
Compactor set new retention period doesn't work

### ISSUE THREAD

**Issue by petkovp** [grafana/tempo#4336]
I installed grafana tempo with helm and then I set the new retention period of the compactor 360h (15 days).
The all setting were applied correctly (configMap, deployment), the tempo.conf file has new set 360h, the pod loaded the retention period.

Traces store in S3 bucket, but compactor delete traces older than 48 hours.

Could you please some help for this issue, because I am going to implement this product and I need for longer retention period that 48 hours.

` compactor:
      config:
        compaction:
          block_retention: 360h`

**Comment by joe-elliott** [comment]
> Traces store in S3 bucket, but compactor delete traces older than 48 hours.

I would check the following:

- confirm it is the compactor deleting the block by checking for a log message that shows the block deleted:

![Image](https://github.com/user-attachments/assets/5b1aa8dd-78aa-46cc-8d84-d242fa1fc286)

- confirm the retention value is set as expected by curling the config endpoint on any compactors that are deleting blocks. `/status/config`

- confirm that you have no overrides for the tenant whose blocks are being deleted. `/status/overrides`. also needs to be curled against 

- are you using s3? or an s3 "compliant" backend?

- confirm that the system time of the compactor pods that are deleting blocks is correct.

**Comment by petkovp** [comment]
I confirm that endpoint result is correct value
`
    compaction:
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 1000
        compaction_window: 1h0m0s
        max_compaction_objects: 6000000
        max_block_bytes: 107374182400
        **block_retention: 360h0m0s**
        compacted_block_retention: 1h0m0s
        retention_concurrency: 10
        max_time_per_tenant: 5m0s
        compaction_cycle: 30s
    override_ring_key: compactor
`

**Comment by LauraFrontastic** [comment]
Hi,

Sorry for hijacking the issue but we have the same behavior. We are using Tempo 2.6.0 installed through the tempo-distributed-1.23.2 with a storage located on a GCP bucket. Blocks are being removed after 4 days from the bucket although we want to keep them for 336h.

block_retention is configured in the helm chart to 336h and it looks correctly applied when I curl our only compator pod:

![Image](https://github.com/user-attachments/assets/1258a858-6584-48c1-af4f-1057ffbf0576)


The time is correctly set on the pod and we don't have any deletion policy at the bucket level. The issue is only affecting our staging environment, it works fine with the same version/almost same helm chart (only different bucket) in prod.

Thanks,

**Comment by joe-elliott** [comment]
Can you confirm there are no tenant overrides configured in your system?

We honestly always use per tenant overrides for retention so I suppose it's possible there's an issue with compaction -> block_retention we just have never stumbled on.

**Comment by LauraFrontastic** [comment]
@joe-elliott indeed, we don't use any tenant override with Tempo

**Comment by joe-elliott** [comment]
@LauraFrontastic can you share you full helm values.yaml file (minus obvious things?). I'd like to take a closer look.

Are you using the tempo-distributed or tempo helm chart?

**Comment by LauraFrontastic** [comment]
@joe-elliott We are using tempo-distributed.

```yaml
---

serviceAccount:
  create: false
  name: xxxx


storage:
  trace:
    backend: gcs
    gcs:
      bucket_name: xxxx
    pool:
      max_workers: 100
      queue_depth: 8000
    wal:
      path: /var/tempo/wal

ingester:
  replicas: 15
  config:
    max_block_duration: 5m
    max_block_bytes: 104857600 #100MB
  resources:
    requests:
      cpu: 2
      memory: "4Gi"
    limits:
      cpu: 3
      memory: "6Gi"

compactor:
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 12
    hpa:
      enabled: true
      behavior: {}
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
  resources:
    requests:
      cpu: 3
      memory: "4Gi"
    limits:
      cpu: 3
      memory: "4Gi"
  config:
    compaction:
      block_retention: 336h

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true

distributor:
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 15
    behavior: {}
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  resources:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      memory: 6Gi
  service:
    annotations:
      cloud.google.com/neg: '{"ingress": true}'

querier:
  replicas: 4
  autoscaling:
    enabled: true
    minReplicas: 4
    maxReplicas: 30
    behavior: {}
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  resources:
    requests:
      cpu: 2
      memory: 6Gi
    limits:
      cpu: 2
      memory: 6Gi
  max_concurrent_queries: 100 

metricsGenerator:
  enabled: true
  replicas: 6
  autoscaling:
    enabled: true
    minReplicas: 6
    maxReplicas: 10
    behavior: {}
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  resources:
    limits:
      cpu: 2
      memory: 6Gi
    requests:
      cpu: 2
      memory: 4Gi
  config:
    registry:
      external_labels:
        source: tempo
    processor:
      span_metrics:
        dimensions: [xxx, xxx, xxx, xxx]
      service_graphs:
        max_items: 100000 #Default 10000
    storage:
      remote_write:
        - url: http://xxxx:9090/api/v1/write

queryFrontend:
  service:
    annotations:
      cloud.google.com/neg: '{"ingress": true}'
      cloud.google.com/app-protocols: '{"https":"HTTPS"}'
  search:
    concurrent_jobs: 1000

metaMonitoring:
  serviceMonitor:
    enabled: true
    interval: 10s
  grafanaAgent:
    enabled: true
    installOperator: true
    metrics:
      remote:
        url: 'http://xxxx:9090/api/v1/write'


global_overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
    ingestion:
      max_traces_per_user: 300000
      rate_limit_bytes: 200000000
```
