### ISSUE TITLE
how to use air for autoreload

### ISSUE THREAD

**Issue by andreanidouglas** [grafana/tempo#4347]
How do I setup air to work with templ?

i have all my templates folder

and this is my .air.toml configuration, but air keeps refreshing when it generates the template .go files

```toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/server"
cmd = "make"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "view/node_modules"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "templ", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true

```
