### ISSUE TITLE
traces_service_graph_request_messaging_system_seconds metrics is not produced, while enabled.

### ISSUE THREAD

**Issue by cbos** [grafana/tempo#4492]
I am running Tempo 2.6.1.
My full Tempo config can be found here: https://github.com/cbos/observability-toolkit/blob/main/config/tempo/tempo-config.yaml

For the service graph processor I have I this config:

```yaml
  processor:
    service_graphs:
      wait: 30s
      max_items: 10000
      workers: 10
      dimensions: []
      #enable_client_server_prefix: false
      peer_attributes:
        - peer.service
        - db.name
        - db.system
        - messaging.destination.name
      # Enables additional labels for services and virtual nodes. Default false
      enable_virtual_node_label: true
      # If enabled another histogram will be produced for interactions over messaging systems middlewares
      # If this feature is relevant over long time ranges (high latencies) - consider increasing
      # `wait` value for this processor. Default false
      # enable_messaging_system_latency_histogram: false
      enable_messaging_system_latency_histogram: true
```

All metrics are generated:
<img width="757" alt="Image" src="https://github.com/user-attachments/assets/2a74b519-38e1-4a62-ae0a-854c0a72e0c7" />

But `traces_service_graph_request_messaging_system_seconds` is missing. That is introduced with #3453 

My test setup is a modified setup of OpenTelemetry demo:
https://github.com/cbos/opentelemetry-demo/tree/jms-support

Producer
https://github.com/cbos/opentelemetry-demo/tree/jms-support/src/adservice
JMS system is ActiveMQ (messagequeue in the setup)
Consumer
https://github.com/cbos/opentelemetry-demo/tree/jms-support/src/analytics

<img width="1594" alt="Image" src="https://github.com/user-attachments/assets/a31fd5b3-6a51-45e1-a9fe-565bc27819c5" />
So the client-server matching is done correctly and the connection_type is 'messaging_system'.

https://github.com/grafana/tempo/blob/deece3c9084a56988361be9d0c44b73911a2210e/modules/generator/processor/servicegraphs/servicegraphs.go#L380

I checked the logging of Tempo, but I don't see the warning "producerSpanEndTime must be smaller than consumerSpanStartTime. maybe the peers clocks are not synced"

Based on what I can see all conditions are met to create the metrics, but these are not produced.
What can I do to find the problem to get it fixed?

**Comment by joe-elliott** [comment]
When we create a processor we overlay per tenant overrides on the default config and pass it in.

https://github.com/grafana/tempo/blob/b6bd53773e792b193f70f235ada6e6edcda4b3f1/modules/generator/config.go#L67

I'm wondering if we're overwriting the "true" in your config with false here. Most config options seem to have some kind of guard code to not override if its an empty value, but we just take whatever is in the overrides for this particular value.

https://github.com/grafana/tempo/blob/b6bd53773e792b193f70f235ada6e6edcda4b3f1/modules/generator/config.go#L132

Perhaps try something like:

```
overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]
      processor:
        service_graphs:
          enable_messaging_system_latency_histogram: true
```

This is confusing. Even if this is not your issue, we need to optionally overwrite this field and not blindly do it.
