### ISSUE TITLE
Make virtual_node label value configurable?

### ISSUE THREAD

**Issue by ShyunnY** [grafana/tempo#4506]
When using service_graph, we usually find that the entry nodes are all virtual_node type (of course, this is expected), and their values ​​are always `user/peer` values.

Is it possible for us to add a new feature that allows users to step in and configure its value?

**Describe the solution you'd like**

We always use the user-configured value first, if the user selects empty, we can fall back to the default value.

Can we organize it with the following structure? (Of course, this is just an example, not the final form):
```yaml
service_graphs:
  virtual_node:
    defaultClientValue: foo
    defaultServerValue: bar
```

**Describe alternatives you've considered**

None

**Additional context**

Related code:

https://github.com/grafana/tempo/blob/c34cf3ae3beba38411becb484c8197929aa3e538/modules/generator/processor/servicegraphs/servicegraphs.go#L390-L421
