### ISSUE TITLE
GRPC IP address strange behavior.  Changed in configuration file to 10.... lead to 127.0.0.1

### ISSUE THREAD

**Issue by rmalenko** [grafana/tempo#4566]
GRPC IP address strange behavior.  Changed in configuration file to 10.... lead to 127.0.0.1

If I set `grpc_listen_address: 10.33.3.184` I can't connect by GRPC from Grafana. 

And I have got the error:
```
Query error
rpc error: code = Internal desc = error querying ingesters in Querier.Search: failed to execute f() for 127.0.0.1:9095: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:9095: connect: connection refused"
```

```yaml
server:
  log_level: info

  http_listen_address: 10.33.3.184
  http_listen_port: 3200

  grpc_listen_address: 10.33.3.184
  grpc_listen_port: 9095

  http_server_write_timeout: 30s
  http_server_idle_timeout: 120s
```

P.S.  I can connect by HTTP. IP and ports are already checked.

**Comment by joe-elliott** [comment]
In single binary mode Tempo assumes it can connect to itself at 127.0.0.1:

https://github.com/grafana/tempo/blob/main/cmd/tempo/app/modules.go#L363-L366

If you would like to use the above configuration you need to configure the frontend worker address as well.

```
querier:
    frontend_worker:
        frontend_address: <here>
```

**Comment by rmalenko** [comment]
Thank you for your answer. Unfortunately, the error is still present
I have added this

```yaml
querier:
  frontend_worker:
    frontend_address: 10.33.3.184:9095
```

if I use without port number `frontend_address: 10.33.3.184` I have got this error
`10.133.3.184:443` i.e. `443` was substituted
