### ISSUE TITLE
Span Id with all zeros cause index out of range

### ISSUE THREAD

**Issue by YakirOren** [grafana/tempo#4573]
**Describe the bug**

When Tempo queries for a traces that contains a span_id `0000000000000000`
cause 
` panic serving 172.23.0.3:47754: runtime error: index out of range [7] with length 0`

**To Reproduce**
1. Start Tempo 2.7.0
2. Push a trace to the `/v1/traces` endpoint a that contains a span with a span_id `0000000000000000`
3. Query the trace 

**Expected behavior**
Tempo should return an error if this against the OTEL spec

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: Docker

**Additional Context**

[panic_output.log](https://github.com/user-attachments/files/18452877/panic_output.log)

tempo config 
```yaml
server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "tempo:4317"
        http:
          endpoint: "tempo:4318"

storage:
  trace:
    backend: local 
    wal:
      path: /var/tempo/wal 
    local:
      path: /var/tempo/blocks

```
