### ISSUE TITLE
Tempo throws 404 Unimplemented error on `/otlp/v1/traces` route

### ISSUE THREAD

**Issue by musq** [grafana/tempo#4590]
# Describe the bug

When I send traces via Alloy to locally running Tempo v2.7.0, Alloy logs this following error and I don't see traces in local Grafana. However if I point Alloy to Grafana Cloud endpoint for Tempo, then I am able to see traces in Grafana Cloud.

```
ts=2025-01-20T11:47:40.383247718Z level=error msg="Exporting failed. Dropping data." component_path=/ component_id=otelcol.exporter.otlphttp.tempo error="not retryable error: Permanent error: rpc error: code = Unimplemented desc = error exporting items, request to http://common_tempo:3200/otlp/v1/traces responded with HTTP Status Code 404" dropped_items=1
```

I have tried to use different tags for tempo, e.g. `grafana/tempo:2.4.1`, `grafana/tempo:2.7.0`, `grafana/tempo:latest`, but all give the same error. So I suspect maybe there is something wrong with my setup?

# To Reproduce

A very simple test to reproduce this would be to bring the `common_tempo` container up and running from below Compose file. Then running: `curl -X POST "localhost:11220/otlp/v1/traces"` also returns `404 page not found`.

Docker Compose

```yaml
services:
  common_loki:
    image: grafana/loki:3.3.2
    command: -config.file=/etc/loki/config.yaml
    healthcheck:
      # https://community.grafana.com/t/loki-healthcheck-in-docker-compose/117767/4
      test: wget --quiet --tries=1 --output-document=- http://localhost:3100/ready | grep -q -w ready || exit 1
      start_period: 20s
      interval: 3s
      timeout: 1s
      retries: 20
    ports:
      - "11215:3100"
    volumes:
      - ./common_loki/config.yaml:/etc/loki/config.yaml
      - ~/src/docker-volumes/common_loki/data:/loki

  # The Tempo service stores traces sent to it by Grafana Alloy, and takes
  # queries from Grafana to visualise those traces.
  common_tempo:
    image: grafana/tempo:2.7.0
    command: -config.file=/etc/tempo/config.yaml
    healthcheck:
      # https://community.grafana.com/t/loki-healthcheck-in-docker-compose/117767/4
      test: wget --quiet --tries=1 --output-document=- http://localhost:3200/ready | grep -q -w ready || exit 1
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
    ports:
      - "11220:3200"
    volumes:
      - "./common_tempo/config.yaml:/etc/tempo/config.yaml"

  common_alloy:
    image: grafana/alloy:latest
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      common_loki:
        condition: service_healthy
      common_tempo:
        condition: service_healthy
    healthcheck:
      # https://github.com/grafana/alloy/issues/477#issuecomment-2050541417
      test: "/bin/bash -c 'echo -e \"GET /-/ready HTTP/1.1\\nHost: localhost\\nConnection: close\\n\\n\" > /dev/tcp/localhost/12345'"
      interval: 1s
      timeout: 1s
      retries: 10
    ports:
      - "11210:12345" # Alloy server and UI
      - "11211:4317" # gRPC
      - "11212:4318" # HTTP
    volumes:
      - ./common_alloy/config.alloy:/etc/alloy/config.alloy
      - ./common_alloy/endpoints.json:/etc/alloy/endpoints.json
      - ~/src/docker-volumes/common_alloy/data:/var/lib/alloy/data

  common_grafana:
    image: grafana/grafana:11.4.0
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    healthcheck:
      # https://github.com/grafana/grafana/pull/27536
      test: wget --quiet --tries=1 --output-document=- http://localhost:3000/healthz | grep -q -w Ok || exit 1
      interval: 1s
      timeout: 1s
      retries: 10
    ports:
      - "11200:3000"
    volumes:
      - ./common_grafana:/etc/grafana/provisioning
      - ~/src/docker-volumes/common_grafana/data:/var/lib/grafana
```

Alloy Config (`common_alloy/config.alloy`)

```alloy
logging {
    level  = "info"
    format = "logfmt"
}

///////////////////////////////////////////////////////////////////////////////

// The OpenTelemetry receiver is used to ingest all incoming logs, metrics, and trace spans.
// Note that both the instrumented applications and Beyla use the same receiver to send traces.
otelcol.receiver.otlp "default" {
    // We don't technically need this, but it shows how to change listen address and incoming port.
    // In this case, the Alloy is listening on all available bindable addresses on port 4317 (which is the
    // default OTLP gRPC port) for the OTLP protocol.
    grpc {
        endpoint = "0.0.0.0:4317"
    }

    output {
        logs    = [otelcol.processor.batch.default.input]

        // We define where to send the output of all ingested traces. In this case, to the OpenTelemetry batch processor
        // named 'default'.
        traces = [
            // Uncomment the next line to generate service graph metrics from the Alloy. By default this is generated
            // by the Tempo component, so be sure to remove the relevant configuration in the `tempo/tempo.yaml` file.
            //otelcol.connector.servicegraph.tracemetrics.input,

            // Uncomment the next line to generate span metrics from the Alloy. By default this is generated
            // by the Tempo component, so be sure to remove the relevant configuration in the `tempo/tempo.yaml` file.
            //otelcol.connector.spanmetrics.tracemetrics.input,

            // The following would be used for tail sampling only traces containing errors.
            // Uncomment the following line, then comment out the line below it (the batch processor) to use
            // tail sampling.
            //otelcol.processor.tail_sampling.errors.input,

            otelcol.processor.batch.default.input,

            //otelcol.connector.spanlogs.autologging.input,
        ]
    }
}

// The OpenTelemetry batch processor collects trace spans until a batch size or timeout is met, before sending those
// spans onto another target. This processor is labeled 'default'.
otelcol.processor.batch "default" {
    // Wait until we've received 1000 samples, up to a maximum of 2000.
    send_batch_size = 1000
    send_batch_max_size = 2000
    // Or until 2 seconds have elapsed.
    timeout = "2s"

    // When the Alloy has enough batched data:
    output {
        // Send logs to the OpenTelemetry exporter named 'loki'.
        logs   = [otelcol.exporter.otlphttp.loki.input]

        // Send traces to the OpenTelemetry exporter named 'tempo'.
        traces = [otelcol.exporter.otlphttp.tempo.input]
    }
}

otelcol.exporter.otlphttp "loki" {
    client {
        // client.endpoint is used to construct the logs endpoint as follows: client.endpoint + "/v1/logs"
        // So, logs_endpoint here would be "http://common_loki:3100/otlp/v1/logs"
        // https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.exporter.otlphttp/#arguments
        endpoint = "http://common_loki:3100/otlp"
    }
}

otelcol.exporter.otlphttp "tempo" {
    client {
        // client.endpoint is used to construct the traces endpoint as follows: client.endpoint + "/v1/traces"
        // So, traces_endpoint here would be "http://common_tempo:3200/otlp/v1/traces"
        // https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.exporter.otlphttp/#arguments
        endpoint = "http://common_tempo:3200/otlp"
        //endpoint = "https://otlp-gateway-prod-ap-south-1.grafana.net/otlp"
        //auth     = otelcol.auth.basic.grafana_cloud.handler
    }
}

otelcol.auth.basic "grafana_cloud" {
	username = "<my-production-id-goes-here>"
	password = "<my-production-token-goes-here>"
}  
```

Tempo Config (`common_tempo/config.yaml`)

```yaml
# For more information on this configuration, see the complete reference guide at
# https://grafana.com/docs/tempo/latest/configuration/

# Enables result streaming from Tempo (to Grafana) via HTTP.
stream_over_http_enabled: true

# Configure the server block.
server:
  # Listen for all incoming requests on port 3200.
  http_listen_port: 3200
  log_level: info         # Set the log level to info.

# The distributor receives incoming trace span data for the system.
distributor:
  receivers:             # This configuration will listen on all ports and protocols that tempo is capable of.
    jaeger:              # The receivers all come from the OpenTelemetry collector.  More configuration information can
      protocols:         # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
        thrift_http:     #
        grpc:            # For a production deployment you should only enable the receivers you need!
        thrift_binary:   #
        thrift_compact:
    otlp:
      protocols:
        http:
        grpc:            # This example repository only utilises the OTLP gRPC receiver on port 4317.
    zipkin:              # Receive trace data in any supported Zipkin format.

# The ingester receives data from the distributor and processes it into indices and blocks.
ingester:
  trace_idle_period: 10s       # The length of time after a trace has not received spans to consider it complete and flush it.
  max_block_bytes: 1_000_000   # Cut the head block when it hits this size or
  max_block_duration: 5m       # this much time passes

# The compactor block configures the compactor responsible for compacting TSDB blocks.
compactor:
  compaction:
    compaction_window: 1h              # Blocks in this time window will be compacted together.
    max_block_bytes: 100_000_000       # Maximum size of a compacted block.
    block_retention: 1h                # How long to keep blocks. Default is 14 days, this demo system is short-lived.
    compacted_block_retention: 10m     # How long to keep compacted blocks stored elsewhere.

# Configuration block to determine where to store TSDB blocks.
storage:
  trace:
    backend: local                     # Use the local filesystem for block storage. Not recommended for production systems.
    block:
      bloom_filter_false_positive: .05 # Bloom filter false positive rate.  lower values create larger filters but fewer false positives.
    # Write Ahead Log (WAL) configuration.
    wal:
      path: /tmp/tempo/wal             # Directory to store the the WAL locally.
    # Local configuration for filesystem storage.
    local:
      path: /tmp/tempo/blocks          # Directory to store the TSDB blocks.
    # Pool used for finding trace IDs.
    pool:
      max_workers: 100                 # Worker pool determines the number of parallel requests to the object store backend.
      queue_depth: 10000               # Maximum depth for the querier queue jobs. A job is required for each block searched.

# Configures the metrics generator component of Tempo.
metrics_generator:
  # Specifies which processors to use.
  processor:
    # Span metrics create metrics based on span type, duration, name and service.
    span_metrics:
        # Configure extra dimensions to add as metric labels.
        dimensions:
          - http.method
          - http.target
          - http.status_code
          - service.version
    # Service graph metrics create node and edge metrics for determinng service interactions.
    service_graphs:
        # Configure extra dimensions to add as metric labels.
        dimensions:
          - http.method
          - http.target
          - http.status_code
          - service.version
    # Configure the local blocks processor.
    local_blocks:
        # Ensure that metrics blocks are flushed to storage so TraceQL metrics queries against historical data.
        flush_to_storage: true
  # The registry configuration determines how to process metrics.
  registry:
    collection_interval: 5s                 # Create new metrics every 5s.
    # Configure extra labels to be added to metrics.
    external_labels:
      source: tempo                         # Add a `{source="tempo"}` label.
      group: 'mythical'                     # Add a `{group="mythical"}` label.
  # Configures where the store for metrics is located.
  storage:
    # WAL for metrics generation.
    path: /tmp/tempo/generator/wal
    # Where to remote write metrics to.
    remote_write:
      - url: http://mimir:9009/api/v1/push  # URL of locally running Mimir instance.
        send_exemplars: true # Send exemplars along with their metrics.
  traces_storage:
    path: /tmp/tempo/generator/traces

# Global override configuration.
overrides:
  metrics_generator_processors: ['service-graphs', 'span-metrics','local-blocks'] # The types of metrics generation to enable for each tenant.
```

**Comment by joe-elliott** [comment]
There are two things I think you need to address. First is that the `otlp/v1/traces` endpoint is not on port 3200. It's on whatever port you configure in your receiver block. Port 3200 is where will be able to find the Tempo http api.

```
distributor:
  receivers: 
    otlp:
      protocols:
        http:
```

Since you've provided no config it will default to OTel's defaults.

Second you likely need to provide configuration in this block. By default the receivers bind to the `localhost` interface only.

https://grafana.com/docs/tempo/latest/release-notes/v2-7/#opentelemetry-collector-receiver-listens-on-localhost-by-default

**Comment by musq** [comment]
Thanks @joe-elliott, that was helpful.

🔴 ⚠ **However tempo actually exposes the otlp route on `/v1/traces` instead of `/otlp/v1/traces`, so I had to make the following changes to make it work.**

I figured it out by following this example: https://grafana.com/docs/tempo/latest/api_docs/pushing-spans-with-http/


### `common_alloy/config.alloy`

```diff
otelcol.processor.batch "default" {
-        traces = [otelcol.exporter.otlp.tempo.input]
+        traces = [otelcol.exporter.otlphttp.tempo.input]
}

+otelcol.exporter.otlphttp "tempo" {
+    client {
+       // client.endpoint is used to construct the traces endpoint as follows: client.endpoint + "/v1/traces"
+        // So, traces_endpoint here would be "http://common_tempo:3200/otlp/v1/traces"
+        // https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.exporter.otlphttp/#arguments
+        endpoint = "http://common_tempo:4318/otlp"
+    }
+    // WARN: Actually tempo exposes the otlp route on "/v1/traces" instead of
+    // "/otlp/v1/traces", so we are essentially overriding the "client.endpoint"
+    // config above with "traces_endpoint" here
+    traces_endpoint = "http://common_tempo:4318/v1/traces"
+}
```


### `common_tempo/config.yaml`

```diff
    otlp:
      protocols:
+        # Use <container_name>:<port> instead of "0.0.0.0:<port>"
+        # https://grafana.com/docs/tempo/latest/release-notes/v2-7/#opentelemetry-collector-receiver-listens-on-localhost-by-default
+        grpc:   # on port 4317
+          endpoint: "common_tempo:4317"
+        http:   # on port 4318
+          endpoint: "common_tempo:4318"
```

## Questions
- Note that Grafana Cloud still accepts traces on `/otlp/v1/traces` route, so still not sure why the difference between Local and Cloud? 🤔 
- Is there a way to add prefix `/otlp` to the HTTP route on local Tempo, so it accepts traces on `/otlp/v1/traces` route?

**Comment by joe-elliott** [comment]
> Note that Grafana Cloud still accepts traces on /otlp/v1/traces route, so still not sure why the difference between Local and Cloud? 🤔

We prefix a lot of our paths in cloud with the application. I did not set this up so I can't say for sure, but I imagine they were doing something like we do when we prefix Cloud Traces paths with `/tempo`.

> Is there a way to add prefix /otlp to the HTTP route on local Tempo, so it accepts traces on /otlp/v1/traces route, so that the endpoints are consistent with Loki?

Tempo defaults to OTEL which is `/v1/traces`. Reading the config like below it seems like you can pass the receiver a `traces_url_path` setting to change it to whatever you want?

https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md#writing-with-httpjson

The [receiver blocks](https://grafana.com/docs/tempo/latest/configuration/#distributor) are passed directly to OTel so you should be able to add `traces_url_path` there.

**Comment by musq** [comment]
Thanks @joe-elliott, that worked! These are my changes.

`common_tempo/config.yaml`
```yaml
distributor:
  # The receivers all come from the OpenTelemetry collector. More configuration
  # information can be found there:
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
  receivers:         
    # For a production deployment you should only enable the receivers you need!
    otlp:
      protocols:
        # Use <container_name>:<port> instead of "0.0.0.0:<port>"
        # https://grafana.com/docs/tempo/latest/release-notes/v2-7/#opentelemetry-collector-receiver-listens-on-localhost-by-default
        grpc:   # on port 4317
          endpoint: "common_tempo:4317"
        http:   # on port 4318
          endpoint: "common_tempo:4318"
          # WARN: Actually tempo exposes the otlp route on "/v1/traces" instead
          # of "/otlp/v1/traces". As a result it becomes inconsistent with Loki
          # and Mimir, and we have to omit "/otlp" suffix from the
          # otelcol.exporter.otlphttp.tempo.client.endpoint in config.alloy for
          # it to work. So, here we prefix "/otlp" to the traces route, so we
          # are able to keep "/otlp" suffix in
          # otelcol.exporter.otlphttp.tempo.client.endpoint and keep things
          # consistent
          # https://github.com/grafana/tempo/issues/4590#issuecomment-2609985910
          # https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.exporter.otlphttp/#arguments
          traces_url_path: "/otlp/v1/traces"
```

`common_alloy/config.alloy`
```hcl
otelcol.exporter.otlphttp "tempo" {
    client {
        // client.endpoint is used to construct the traces endpoint as follows: client.endpoint + "/v1/traces"
        // So, traces_endpoint here would be "http://common_tempo:4318/otlp/v1/traces"
        // https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.exporter.otlphttp/#arguments
        endpoint = "http://common_tempo:4318/otlp"
    }
}
```

For people encountering this issue in the future, I'm preparing a repo to handle bootstrapping of Grafana LGTM stack locally, to kickstart observability in any new project easily.
https://github.com/musq/common-containers
