### ISSUE TITLE
gRPC Health Check must be implemented in the distributor

### ISSUE THREAD

**Issue by kworkbee** [grafana/tempo#4657]
**Is your feature request related to a problem? Please describe.**
I want to pass traces (coming in from outside K8s cluster) to the distributor through AWS ALB with gRPC as backend protocol. In this case, ALB Health Check related annotations should be specified in Ingress but if the backend protocol is gRPC, health check method should also return the status code based on gRPC.
However, the status code currently returned by the /ready HTTP endpoint is an HTTP status code, so there is a problem that the gRPC-based ALB cannot be configured at the front-end of the distributor.

<img width="521" alt="Image" src="https://github.com/user-attachments/assets/6fec82cf-7f3f-4008-ba41-e41588fad2a5" />

<img width="585" alt="Image" src="https://github.com/user-attachments/assets/f028b286-a424-49db-a1c8-ee55147b2656" />

**Describe the solution you'd like**
A standard gRPC Health Endpoint (which conforms to [standard proto](https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto)) should be added into distributor.

**Comment by luvpreetsingh** [comment]
I was looking for the same and landed at this issue.

**Comment by luvpreetsingh** [comment]
So, is there no way of doing it as of now?

I am facing the same issue but on GCP.

<img width="108" alt="Image" src="https://github.com/user-attachments/assets/d4b4082f-8984-4546-9b17-e6e1cb3b55d5" />

**Comment by joe-elliott** [comment]
The gRPC service running on port 4317 is here: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver

I'm not sure we can add a healthcheck endpoint to it. I have been wanting to write our own otel receiver native into tempo for awhile now which would allow us to do this, but that's on the backburner.

**Comment by joe-elliott** [comment]
We do register gRPC health checks to the standard gRPC server in the distributor. Unsure if you can point the ALB to that:

https://github.com/grafana/tempo/blob/3d50193c062cf2e38ee9fd3e270abf08ef172e03/cmd/tempo/app/app.go#L197-L201

**Comment by luvpreetsingh** [comment]
> We do register gRPC health checks to the standard gRPC server in the distributor

@joe-elliott Would you be kind enough to share grpcurl for the distributor health check call?

**Comment by luvpreetsingh** [comment]
Looks like GCP doesn't support GRPC health checks

https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#direct_health

**Comment by luvpreetsingh** [comment]
This is confusing to me. We can't use GRPC ingestion on Grafana Tempo with the current implementation. Am I missing something really basic or is tempo missing something?

**Comment by luvpreetsingh** [comment]
For the OTLP HTTP endpoint, is there any health check endpoint available there?

**Comment by kworkbee** [comment]
> We do register gRPC health checks to the standard gRPC server in the distributor. Unsure if you can point the ALB to that:
> 
> [tempo/cmd/tempo/app/app.go](https://github.com/grafana/tempo/blob/3d50193c062cf2e38ee9fd3e270abf08ef172e03/cmd/tempo/app/app.go#L197-L201)
> 
> Lines 197 to 201 in [3d50193](/grafana/tempo/commit/3d50193c062cf2e38ee9fd3e270abf08ef172e03)
> 
>  grpc_health_v1.RegisterHealthServer(t.Server.GRPC(), 
>  	grpcutil.NewHealthCheckFrom( 
>  		grpcutil.WithShutdownRequested(shutdownRequested), 
>  		grpcutil.WithManager(sm), 
>  	))

Hi, @joe-elliott Thanks for your response. I missed the implementation of `app.go`, so I tried to port-forward traffic port and call `grpcurl` as below.

```shell
grpcurl -v -plaintext -import-path ./ -d '{"service":""}' -proto health.proto localhost:4317 grpc.health.v1.Health/Check                                                         
```

I saw that it's coming out as 'UNIMPLEMENTED', but I don't know if I called it correctly. (Sorry but I'm not used to gRPC and golang enough yet)

```
Resolved method descriptor:
// If the requested service is unknown, the call will fail with status
// NOT_FOUND.
rpc Check ( .grpc.health.v1.HealthCheckRequest ) returns ( .grpc.health.v1.HealthCheckResponse );

Request metadata to send:
(empty)

Response headers received:
(empty)

Response trailers received:
content-type: application/grpc
Sent 1 request and received 0 responses
ERROR:
  Code: Unimplemented
  Message: unknown service grpc.health.v1.Health
```

**Comment by joe-elliott** [comment]
Port 4317 is the OTel gRPC receiver. This service is not managed by us and I don't believe we can add a health check here.

By default port 9950 is the native Tempo gRPC receiver. That should have a health check server registered.

**Comment by kworkbee** [comment]
Hi, @joe-elliott 
I think [this configuration](https://github.com/grafana/tempo/blob/main/modules/distributor/config.go#L37) is seen as an area that reflects the configuration of the OpenTelemetry Receiver, will the `extension` also be changed to receive it? It seems that there is [one of the OTel extensions that can activate gRPC Health Check](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckv2extension).

**Comment by joe-elliott** [comment]
The distributor does not currently have the ability to load otel collector extensions and will likely not for the foreseeable future. Reading [the config](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckv2extension#configuration) it looks like you set the healthcheck up on a different port than the receiver anyway. If this is possible why don't you use the healthcheck on port 9950 of the distributor?

**Comment by kworkbee** [comment]
Hello @joe-elliott!
I port forwarded the distributor pod and made a request using `grpcurl`.
Health Check with 9095 port has been confirmed as below image.

<img width="1159" alt="Image" src="https://github.com/user-attachments/assets/b1a79914-bd8b-4894-9572-340df075f6d7" />

<img width="1294" alt="Image" src="https://github.com/user-attachments/assets/90aa9c77-5572-4f42-bf64-9602f391910f" />

However, in ALB, the header customization is not possible in health check. So I will configure `alb.ingress.kubernetes.io/success-codes` annotation to `2` (UNKNOWN).

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  // ...
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /grpc.health.v1.Health/Check
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: '2'
    // ...
// ...
```

**Comment by kworkbee** [comment]
I will operate it in the above configuration. Closing.

**Comment by SujayAmbekarDevops** [comment]
Hey @kworkbee @joe-elliott is the above config for AWS load balancer controller working for you?
I have used the same annotations and my ingress is pointing to tempo-distributor service but still I am observing my targets are not in healthy state and I am not able to send traces via GRPC using an ALB

This is my ingress config used
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-tempo-distributor-ingress-grpc
  namespace: observability
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/healthcheck-path: /grpc.health.v1.Health/Check
    alb.ingress.kubernetes.io/success-codes: '2'
    alb.ingress.kubernetes.io/healthcheck-port: '9095'
  labels:
    app.kubernetes.io/name: grafana-tempo-distributor-ingress-grpc
spec:
  ingressClassName: alb
  rules:
  - host: <>
    http:
      paths:
      - backend:
          service:
            name: tempo-distributor
            port:
              number: 4317
        path: /
        pathType: Prefix

```
