### ISSUE TITLE
yaml: unmarshal error with official configuration

### ISSUE THREAD

**Issue by nWidart** [grafana/tempo#4687]
Hello,

I've used one of the tempo configuration files of the tempo examples:

```yaml
stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: info

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
    metadata_slo:
      duration_slo: 5s
      throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 100ms
  metrics:
    max_duration: 120h                # maximum duration of a metrics query, increase for local setups
    query_backend_after: 5m
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09

distributor:
  receivers:
    zipkin:
      endpoint: "tempo:9411"

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces
  processor:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /var/tempo/wal             # where to store the wal locally
    local:
      path: /var/tempo/blocks

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks] # enables metrics generator
      generate_native_histograms: both
```

However when starting tempo with this I'm getting:

```
tempo  | failed parsing config: failed to parse configFile /etc/tempo.yml: yaml: unmarshal errors:
tempo  |   line 17: field metrics_generator not found in type app.Config
tempo  |   line 35: field defaults not found in type overrides.Limits
tempo exited with code 1
```

Am I missing something obvious? 

Thank you,

Using latest tempo: `grafana/tempo:latest-arm64`
