### ISSUE TITLE
The distributor's queue is full when pushing metrics, but the metrics generator reports zero active series.

### ISSUE THREAD

**Issue by edgarkz** [grafana/tempo#4715]
**Describe the bug**
The distributor's queue is full when pushing metrics, but the metrics generator reports zero active series.

**To Reproduce**
Deploying 2 distributors and 3 metrics generators in a single-tenant setup—after some time, the metrics generator stops functioning.

**Environment:**
 - Infrastructure: eks 1.29
 - Deployment tool: helm tempo distributed
 - version 2.7.0 with zstd enabled compression 
 
Metrics generator config:
```
    metrics_generator:
      metrics_ingestion_time_range_slack: 30s
      processor:
        service_graphs:
          dimensions: []
          histogram_buckets:
          - 0.1
          - 0.2
          - 0.4
          - 0.8
          - 1.6
          - 3.2
          - 6.4
          - 12.8
          max_items: 15000
          wait: 10s
          workers: 10
        span_metrics:
          dimensions: []
          histogram_buckets:
          - 0.002
          - 0.004
          - 0.008
          - 0.016
          - 0.032
          - 0.064
          - 0.128
          - 0.256
          - 0.512
          - 1.02
          - 2.05
          - 4.1
      registry:
        collection_interval: 15s
        external_labels: {}
        stale_duration: 15m
      ring:
        kvstore:
          store: memberlist
      storage:
        path: /var/tempo/wal
        remote_write:
        - url: http://xxxxxxxx.prometheus.svc.cluster.local/api/v1/write
        remote_write_add_org_id_header: true
        remote_write_flush_deadline: 1m
        wal: null
      traces_storage:
        path: /var/tempo/traces
    metrics_generator_client:
      grpc_client_config:
        grpc_compression: zstd
    multitenancy_enabled: false
    overrides:
      defaults:
        global:
          max_bytes_per_trace: 50000000
        ingestion:
          burst_size_bytes: 90000000
          max_traces_per_user: 450000
          rate_limit_bytes: 150000000
        metrics_generator:
          processors:
          - span-metrics
          - local-blocks
        read:
          max_bytes_per_tag_values_query: 5000000
```
**Additional Context**

Trace app shows many gaps in dashboard:

![Image](https://github.com/user-attachments/assets/4aae305b-7c59-4b01-8e62-043ef266d685)

**Logs from distributor:**
```
level=error ts=2025-02-17T07:54:55.864615022Z caller=forwarder.go:89 msg="failed to push traces to queue" tenant=single-tenant err="failed to push data to queue for tenant=single-tenant and queue_name=metrics-generator: queue is full"
level=error ts=2025-02-17T07:54:55.950835933Z caller=forwarder.go:89 msg="failed to push traces to queue" tenant=single-tenant err="failed to push data to queue for tenant=single-tenant and queue_name=metrics-generator: queue is full"
level=error ts=2025-02-17T07:54:55.950897798Z caller=forwarder.go:89 msg="failed to push traces to queue" tenant=single-tenant err="failed to push data to queue for tenant=single-tenant and queue_name=metrics-generator: queue is full"
level=error ts=2025-02-17T07:54:55.950897568Z caller=forwarder.go:89 msg="failed to push traces to queue" tenant=single-tenant err="failed to push data to queue for tenant=single-tenant and queue_name=metrics-generator: queue is full"
level=error ts=2025-02-17T07:54:55.950914003Z caller=forwarder.go:89 msg="failed to push traces to queue" tenant=single-tenant err="failed to push data to queue for tenant=single-tenant and queue_name=metrics-generator: queue is full"
level=error ts=2025-02-17T07:54:55.950913872Z caller=forwarder.go:89 msg="failed to push traces to queue" tenant=single-tenant err="failed to push data to queue for tenant=single-tenant and queue_name=metrics-generator: queue is full"

```

**Logs from all metrics generators:**
```
level=info ts=2025-02-17T07:54:10.358648135Z caller=registry.go:255 tenant=single-tenant msg="collecting metrics" active_series=0
level=info ts=2025-02-17T07:54:10.358667359Z caller=registry.go:276 tenant=single-tenant msg="deleted stale series" active_series=0
level=info ts=2025-02-17T07:54:25.358793593Z caller=registry.go:255 tenant=single-tenant msg="collecting metrics" active_series=0
level=info ts=2025-02-17T07:54:40.358949027Z caller=registry.go:255 tenant=single-tenant msg="collecting metrics" active_series=0
level=info ts=2025-02-17T07:54:55.358590657Z caller=registry.go:255 tenant=single-tenant msg="collecting metrics" active_series=0
level=info ts=2025-02-17T07:55:10.358378765Z caller=registry.go:255 tenant=single-tenant msg="collecting metrics" active_series=0
level=info ts=2025-02-17T07:55:25.35865314Z caller=registry.go:255 tenant=single-tenant msg="collecting metrics" active_series=0
```
