### ISSUE TITLE
Keep getting "Ingester not ready" when running Tempo on docker

### ISSUE THREAD

**Issue by luhyxi** [grafana/tempo#4752]
**Describe the bug**
I am trying to run a docker image of tempo on port 3200, but everytime I enter the /ready endpoint on my local host I keep getting the following message: _"Ingester not ready: ingester check ready failed: waiting for 15s after being ready"_

**To Reproduce**
These are my `tempo.yaml` and `docker-compose.yml`

__tempo.yaml__
```yaml

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc: {} 

ingester:
  max_block_duration: 5m              

compactor:
  compaction:
    block_retention: 1h                

storage:
  trace:
    backend: local                     
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

```

__docker-compose.yml__
``` yaml
services:
  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana-frontend
    ports:
      - "8080:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    ports:
      - "3200:3200"  # HTTP endpoint
      - "9095:9095"  # gRPC (OTLP) endpoint
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml
      - ./tempo-data:/var/tempo
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
```

**Expected behavior**
I suspect it is because of the "Ingester not ready" message that I can't connect to Tempo to my though the Grafana frontend and be able to post requests in the grpc port, thanks for your time.
