### ISSUE TITLE
Tempo 2.6.1 stuck on compactor Starting and returns 503 on /ready

### ISSUE THREAD

**Issue by arnoldyahad** [grafana/tempo#4782]
**Describe the bug**

Although there is no error/warn logs while we are deploying tempo (we also enable debug logs)- our tempo returns 503 when querying the /ready endpoint. 

here is how the /status endpoint looks like for more details:
```
GET /status/version
tempo, version 2.6.1 (branch: HEAD, revision: 24c5b553d)
  build user:       
  build date:       
  go version:       go1.22.8
  platform:         linux/amd64
  tags:             unknown
GET /status/services
+------------------------+----------+--------------+
| SERVICE NAME           |   STATUS | FAILURE CASE |
+------------------------+----------+--------------+
| cache-provider         |  Running |              |
| compactor              | Starting |              |
| distributor            |  Running |              |
| ingester               |  Running |              |
| internal-server        |  Running |              |
| memberlist-kv          |  Running |              |
| metrics-generator      |  Running |              |
| metrics-generator-ring |  Running |              |
| optional-store         |  Running |              |
| overrides              |  Running |              |
| overrides-api          |  Running |              |
| querier                |  Running |              |
| query-frontend         |  Running |              |
| ring                   |  Running |              |
| secondary-ring         |  Running |              |
| server                 |  Running |              |
| store                  |  Running |              |
| usage-report           |  Running |              |
```

so we have suspicion on the compactor, but the compactor ring looks ok and there is no compactor logs at all

![Image](https://github.com/user-attachments/assets/cc87c503-a9ce-4fde-b69a-a483251265c7)

/memberlist also looks good:

![Image](https://github.com/user-attachments/assets/05eca1e1-c013-4da9-8f9d-97ef3b6ee0c2)

so is it a bug? why can't the /ready endpoint return 200? 

**To Reproduce**
1. Use Tempo 2.6.1/2.6.0 
2. Use this configuration:

```
multitenancy_enabled: false

compactor:
  ring:
    kvstore:
      store: memberlist
  compaction:
    block_retention: 168h
    compacted_block_retention: 1h
    compaction_cycle: 5s
    compaction_window: 5m
    v2_prefetch_traces_count: 10000

distributor:
  ring:
    heartbeat_period: 0
    kvstore:
      store: memberlist
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester_client:
  remote_timeout: 500ms

ingester:
  trace_idle_period: 1s
  flush_check_period: 1s
  lifecycler:
    readiness_check_ring_health: false
    ring:
      kvstore:
        store: memberlist
    heartbeat_period: 100ms
  complete_block_timeout: 200ms
  max_block_duration: 1s

server:
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_recv_msg_size: 104857600
  http_listen_port: 3100
  log_level: debug

metrics_generator:
  registry:
    collection_interval: 1s
  storage:
    path: /var/tempo
    remote_write_flush_deadline: 5s
    remote_write:
    - url: http://prometheus-server.kube-system.svc.cluster.local:9090/api/v1/write
      send_exemplars: true
  processor:
    service_graphs:
      max_items: 100000

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - tempo-headless.kube-system.svc.cluster.local:7946

storage:
  trace:
    backend: s3
    s3:
      bucket: our-bucket-tempo
      endpoint: s3.our-region.amazonaws.com
      region: our-region
      hedge_requests_at: 500ms
      hedge_requests_up_to: 2
    search:
      chunk_size_bytes: 500000
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 2000
      queue_depth: 100000
    block:
      version: vParquet2
      parquet_row_group_size_bytes: 5242880

querier:
  frontend_worker:
    frontend_address: tempo-headless.kube-system.svc.cluster.local:9095
  trace_by_id:
    query_timeout: 30s
  search:
    query_timeout: 2m
    external_hedge_requests_at: 500ms
    external_hedge_requests_up_to: 4

query_frontend:
  api_timeout: 40s
  trace_by_id:
    query_shards: 100
  max_retries: 10
  search:
    max_duration: 0
    query_backend_after: 20ms
    query_ingesters_until: 20ms
    target_bytes_per_job: 419430400

overrides:
  max_traces_per_user: 0
  max_bytes_per_trace: 50000000
  ingestion_burst_size_bytes: 200000000
  ingestion_rate_limit_bytes: 150000000
  metrics_generator_processors:
  - service-graphs
  - span-metrics
```

**Expected behavior**
tempo to be ready.
tempo is stuck on not being ready and getting 503 from the endpoint.
```
level=debug ts=2025-03-03T09:34:00.15038477Z caller=server.go:1187 method=/tempopb.MetricsGenerator/PushSpans duration=142.79µs msg="gRPC (success)"
level=debug ts=2025-03-03T09:34:03.110977422Z caller=server.go:2171 trace_id_unsampled=5a63daa2656f3098 msg="GET /ready (503) 44.453µs"
level=debug ts=2025-03-03T09:34:03.111043879Z caller=server.go:2171 trace_id_unsampled=49b843e7972f9060 msg="GET /ready (503) 107.373µs"
level=debug ts=2025-03-03T09:34:08.11127799Z caller=server.go:2171 trace_id_unsampled=6bec253ac52f61f9 msg="GET /ready (503) 36.6µs"
level=debug ts=2025-03-03T09:34:08.111293568Z caller=server.go:2171 trace_id_unsampled=36d8a87a865c5386 msg="GET /ready (503) 35.168µs"
```

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Additional Context**
This only happens when we do a deploy on tempo, after some restarts (sometimes 10 sometimes 100) it finally works. we have no way to troubleshoot it - no errors or warning in the logs after enabling debug logs.
debug logs also doesnt provide any info on why its 503 on `/ready`

**Comment by javiermolinar** [comment]
Hi, could you share the logs with `caller=compactor.go`?

**Comment by javiermolinar** [comment]
I have tried to reproduce it with no luck. I have tried deploying `helm install tempo grafana/tempo` and also using this example:

https://github.com/grafana/tempo/tree/main/example/docker-compose/scalable-single-binary

Hitting the `http://localhost:3200/ready` eventually returns true

The memberlist and the ring are indeed showing all the services up and running while the` /ready` endpoint is still reporting non-ready ones, ingester in my case:

`Ingester not ready: ingester check ready failed: waiting for 15s after being ready`

But this is normal, after a minute it returns 200

**Comment by arnoldyahad** [comment]
thanks for checking @javiermolinar 

currently it still happens to me, my solution is just keep deleting the tempo pods until eventually they get ready, they can either wait for 1 minute or 1 hour or 1 day.... this is very unstable and i dont know what blocks compactor for being ready.

this is also happens to us in another tempo cluster with same configs.

updating to version 2.7.0/2.7.1 didnt help or improve this issue.

i want to understand what makes the `/ready` point ready, and what makes `comapctor` ready and not starting, and why isnt being in `Starting` mode for several hours is not a bug/issue 

if the `/ready` endpoint is purely cosmetic and random and doesnt actually imply if its ready or not, i can just remove our readiness/liveness probes so our deployment won't crush anymore.

**Comment by javiermolinar** [comment]
The ready endpoint is not cosmetic or random. I'm skeptical that the problem is in the compactors since the readiness handler does not check that:

https://github.com/grafana/tempo/blob/ffe17b68d8d22a30b12d733160569448a3dcacc3/cmd/tempo/app/app.go#L312-L362

What you see in the `/status` endpoint is driven by a different logic implemented in our[ common service librar](https://github.com/grafana/dskit/blob/main/services/service.go)y. Every service needs to implement certain methods `startingFn`, `runningFn`, and `terminatingFn`. The state transition from `new` to  `starting` to `running` to `terminating`. It can end in a `failed` state from any of the. Being stuck in `starting` state makes me think that it's never leaving starting method.

What message do you get when hitting the ` /ready` endpoint?

**Comment by arnoldyahad** [comment]
thanks again for the quick response @javiermolinar 

to reproduce the situation i just killed 1 tempo pod and did port-forwarding to the 3100 port-  hitting the /ready endpoint i get:
```
Some services are not Running:
Starting: 1
Running: 17
```

status services shows this:
```
GET /status/services
+------------------------+----------+--------------+
| SERVICE NAME           |   STATUS | FAILURE CASE |
+------------------------+----------+--------------+
| cache-provider         |  Running |              |
| compactor              | Starting |              |
| distributor            |  Running |              |
| ingester               |  Running |              |
| internal-server        |  Running |              |
| memberlist-kv          |  Running |              |
| metrics-generator      |  Running |              |
| metrics-generator-ring |  Running |              |
| optional-store         |  Running |              |
| overrides              |  Running |              |
| overrides-api          |  Running |              |
| querier                |  Running |              |
| query-frontend         |  Running |              |
| ring                   |  Running |              |
| secondary-ring         |  Running |              |
| server                 |  Running |              |
| store                  |  Running |              |
| usage-report           |  Running |              |
+------------------------+----------+--------------+
```

currently my logs set on info so i dont see any message regarding the comapctor.

during my experimentes i gotta say that sometimes killing some tempo pods together helps this issue - for example we have 6 pods - when one is unhealthy for 3 hours, its better to kill 2 more pods and then there is a 99% that the pod that was unhealthy for 3 hours will be ready (/ready == 200) but usually another pod will be not ready (from those who were killed)

this is why i suspect this is purely some edge case in which compactor can't get all his members right or something like that.

attaching also the full config of the compactor (from hitting the /status endpoint):
```
compactor:
    ring:
        kvstore:
            store: memberlist
            prefix: collectors/
            consul:
                host: localhost:8500
                acl_token: ""
                http_client_timeout: 20s
                consistent_reads: false
                watch_rate_limit: 1
                watch_burst_size: 1
                cas_retry_delay: 1s
            etcd:
                endpoints: []
                dial_timeout: 10s
                max_retries: 10
                tls_enabled: false
                tls_cert_path: ""
                tls_key_path: ""
                tls_ca_path: ""
                tls_server_name: ""
                tls_insecure_skip_verify: false
                tls_cipher_suites: ""
                tls_min_version: ""
                username: ""
                password: ""
            multi:
                primary: ""
                secondary: ""
                mirror_enabled: false
                mirror_timeout: 2s
        heartbeat_period: 5s
        heartbeat_timeout: 1m0s
        wait_stability_min_duration: 5s
        wait_stability_max_duration: 15s
        instance_id: tempo-3
        instance_interface_names:
            - eth0
            - en0
        instance_port: 0
        instance_addr: ""
        enable_inet6: false
        wait_active_instance_timeout: 30s
    compaction:
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 10000
        compaction_window: 5m0s
        max_compaction_objects: 6000000
        max_block_bytes: 107374182400
        block_retention: 168h0m0s
        compacted_block_retention: 1h0m0s
        retention_concurrency: 10
        max_time_per_tenant: 5m0s
        compaction_cycle: 5s
    override_ring_key: compactor
```
