### ISSUE TITLE
Periodic Memory spikes in Ingester usage (from 2gb jumping to 8gb every 10-15 minutes)

### ISSUE THREAD

**Issue by darkwind-noveo** [grafana/tempo#4792]
Normally ingesters run around 2gb RAM of usage, but each 10 minutes they spike all the time to around 8gb RAM usage
![Image](https://github.com/user-attachments/assets/d2afc739-17fd-4301-aa1b-fb293edb5a86)
always recurring
![Image](https://github.com/user-attachments/assets/8fc35856-a328-4139-a7d0-bae7dbd98d38)

What i tried? helm for tempo distributed 1.32.1

```yml

tempo:
  podAnnotations:
    prometheus_crds_id: "${prometheus_crds_id}"

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false
gateway:
  enabled: true
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 0.1
      memory: 0.01Gi
  basicAuth:
    enabled: true
    username: "tempo"
server:
   logLevel: debug

# there should be existing new way to define it
global_overrides:
  ingestion_rate_limit_bytes: 30_000_000
  max_bytes_per_trace: 5_000_000
  max_traces_per_user: 0
  metrics_generator_processors:
    - service-graphs
    - span-metrics
    - local-blocks

metricsGenerator:
  enabled: true
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 0.1
      memory: 1.5Gi
  config:
    storage:
      remote_write:
        - url: "${mimir_url}"
          basic_auth:
            username: "mimir"

metaMonitoring:
  # ServiceMonitor configuration
  serviceMonitor:
    # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
    enabled: true

# Rules for the Prometheus Operator
prometheusRule:
  # -- If enabled, a PrometheusRule resource for Prometheus Operator is created
  enabled: true

ingester:
  # may be less reliability. But 3 times less RAM consumption.
  # We have some sort of RAM spike problem, where ingesters jump frequently from 2 gb to 8gb RAM usage frequently.
  # having 1 ingester seemed to mitigated it more or less but hasn't fixed root issue
  # issue that looks exactly like our problem https://github.com/grafana/tempo/discussions/2859
  replicas: 1
  config:
    # -- Number of copies of spans to store in the ingester ring
    replication_factor: 1
  resources:
    limits:
      # spike periodic activity up to 2.5Gb
      # antiafinity to other ingesters is already present
      memory: 14Gi
    requests:
      cpu: 0.15
      memory: 8Gi

distributor:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 0.1
      memory: 1Gi

compactor:
  # Can we scale it horizontally? high RAM consumption too much a bit.
  resources:
    limits:
      memory: 16Gi
    requests:
      cpu: 0.1
      memory: 8Gi
  # Since RAM activity is spiking. Having anti affinity is very nice thing to have.
  # for more reliable distribution of a workload
  affinity: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "tempo.selectorLabels" (dict "ctx" . "component" "compactor") | nindent 12 }}
            topologyKey: kubernetes.io/hostname
        - weight: 75
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "tempo.selectorLabels" (dict "ctx" . "component" "compactor") | nindent 12 }}
            topologyKey: topology.kubernetes.io/zone

querier:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 0.1
      memory: 0.25Gi

queryFrontend:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 0.1
      memory: 0.1Gi

memcached:
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 0.1
      memory: 0.1Gi
```

I tried configuring limits as found in other issues like ( https://github.com/grafana/tempo/issues/2908 )
```yml
global_overrides:
  ingestion_rate_limit_bytes: 30_000_000
  max_bytes_per_trace: 5_000_000
  max_traces_per_user: 0
```

I collect metrics with grafana alloy
```hcl

// For regular otlp
logging {
  level  = "info"
  format = "logfmt"
}

// OTLP Receivers
otelcol.receiver.otlp "receiver" {
  debug_metrics {
    disable_high_cardinality_metrics = true
  }

//   grpc {
//     endpoint = "0.0.0.0:4317"
//   }
  http {
    endpoint = "0.0.0.0:4318"
  }
  output {
    metrics = [otelcol.processor.transform.default.input]
    logs    = [otelcol.processor.transform.default.input]
    traces  = [otelcol.processor.transform.default.input]
  }
}

otelcol.processor.transform "default" {
  error_mode = "ignore"

  trace_statements {
    context = "resource"
    statements = [
      `limit(attributes, 50, [])`,
      `truncate_all(attributes, 512)`,
    ]
  }

  trace_statements {
    context = "span"
    statements = [
      `limit(attributes, 50, [])`,
      `truncate_all(attributes, 512)`,
    ]
  }
  output {
    metrics = [otelcol.processor.batch.default.input]
    logs    = [otelcol.processor.batch.default.input]
    traces  = [otelcol.processor.batch.default.input]
  }
}

otelcol.processor.batch "default" {
  output {
    metrics = [otelcol.exporter.otlphttp.default.input]
    logs    = [otelcol.exporter.otlphttp.default.input]
    traces  = [otelcol.exporter.otlphttp.default.input]
  }
}

otelcol.exporter.otlphttp "default" {
  client {
    endpoint = coalesce(sys.env("TEMPO_URL"),"https://tempo.ingress.local/")
    tls {
        insecure_skip_verify = true
    }
    auth = otelcol.auth.basic.auth.handler
  }
}

tracing {
    // Sample all traces. This value should be lower for production configs!
    sampling_fraction = encoding.from_json(coalesce(sys.env("SAMPING_FRACTION"),"0.1"))
    write_to = [otelcol.exporter.otlphttp.default.input]
}

otelcol.auth.basic "auth" {
    username = coalesce(sys.env("TEMPO_USERNAME"),"tempo")
    password = coalesce(sys.env("TEMPO_PASSWORD"),"password")
}
```

As seen in some github issues (like https://github.com/grafana/tempo/issues/2769#issuecomment-1702557124 )  giving some advices i configured transform trancutator
```hcl
otelcol.processor.transform "default" {
  error_mode = "ignore"

  trace_statements {
    context = "resource"
    statements = [
      `limit(attributes, 50, [])`,
      `truncate_all(attributes, 512)`,
    ]
  }

  trace_statements {
    context = "span"
    statements = [
      `limit(attributes, 50, [])`,
      `truncate_all(attributes, 512)`,
    ]
  }
  output {
    metrics = [otelcol.processor.batch.default.input]
    logs    = [otelcol.processor.batch.default.input]
    traces  = [otelcol.processor.batch.default.input]
  }
}
```

That all still did not help
The only thing that helped me so far is actually just decreasing amount of ingesters. At least help to mitigate issue by eating 3 times less RAM
```yml
ingester:
  replicas: 1
  config:
    # -- Number of copies of spans to store in the ingester ring
    replication_factor: 1
```

I ran Golang pprof to see what can be seen
IN USE MEM: When ingester IS NOT having spike, we can see this stuff:
![Image](https://github.com/user-attachments/assets/8f83a3ec-c068-40b9-b235-c430932c1d08)

IN USE MEM: When ingester IS having spike, we can see this spike for inuse memory: (executed `go tool pprof -inuse_space -http=":8001" http://localhost:3100/debug/pprof/heap` at the moment of a Spike)
![Image](https://github.com/user-attachments/assets/74346c36-b967-42fe-9c80-669d4346a176)

Just in case photoed total allocations too:
TOTAL ALLOCATIONS: When not having spike:
![Image](https://github.com/user-attachments/assets/b05e04f0-5ca1-4b22-84ef-1f053c17bca2)
TOTAL ALLOCATIONS: When having spike:
![Image](https://github.com/user-attachments/assets/b68916f5-731f-487e-afd3-3517b0a0525d)

Symtom of issue i believe a lot of allocations that remained even in use? 4GB i guess.
And it is logical to see Go heap raising to 8GB in such situation

![Image](https://github.com/user-attachments/assets/c7be061e-0f7f-4e66-a4a5-364af9455d87)
vparquet4.Encoding.CreateBlock is a heavy offender and main candidate i think for the issue?
though total allocations picture show possible one more candidate (writeTraceToHeadBlock / vpartquet4.(*walBlock).Append )

# Expected desires

Is it possible having ram usage more predicable around 2 GB without those memory spikes? 😄 
Anything else i can toggle to mitigate the issue?

**Comment by darkwind-noveo** [comment]
If u will helpful, also picture of tempo operational dashboard in same period (1 hour)

![Image](https://github.com/user-attachments/assets/84291b68-4207-407e-894a-aa5a7be5fa27)

**Comment by darkwind-noveo** [comment]
![Image](https://github.com/user-attachments/assets/e76fe7ad-6637-47f2-8622-1a082a5cba1c)

![Image](https://github.com/user-attachments/assets/0e142f86-689a-4b1b-9035-be35a7118478)

I tracked a clue. Compactor has a lot of writing in same periods
And Profiler shows a lot of BlockCreate stuff. I believe the spike happens when ingester periodically dumps stuff to compactor :)

**Comment by darkwind-noveo** [comment]
I think it helped 😄 

![Image](https://github.com/user-attachments/assets/eb8a300d-1e4b-4782-8ff0-21d9acd0cd69)
Now i have large memory issues with compactor
In use mem:
![Image](https://github.com/user-attachments/assets/24240cc0-be21-4605-9d33-d3e51fbf6ac0)
total alloc mem:
![Image](https://github.com/user-attachments/assets/01e19c31-85cf-4198-8ac8-3f512d345c35)

**Comment by darkwind-noveo** [comment]
Anyway, i believe usage of  `max_block_bytes` and/or `complete_block_timeout` in ingester config solved my original problem with ingester memory spikes
https://github.com/grafana/tempo/issues/4792#issuecomment-2699566897

**Comment by darkwind-noveo** [comment]
![Image](https://github.com/user-attachments/assets/2b0cd429-0534-43b6-8446-c7cb005c8ea8)
24 GB memory spikes for Compactor aren't great at all though.

**Comment by darkwind-noveo** [comment]
![Image](https://github.com/user-attachments/assets/37af033a-68b3-467e-8c35-7305e899386c)
Okay i have compactor operating... reasonably well
```yml
global_overrides:
  # comment away `max_bytes_per_trace` stuff if u wish rejecting super large traces and to save Compactor at least from RAM overusage (may be other impacts)
  # `max_bytes_per_trace` default value 5_000_000
  max_bytes_per_trace: 50_000_000
  max_traces_per_user: 0
```
With limiting bytes per trace i think it stabilized? Still sus though, but i guess okay for now
