### ISSUE TITLE
How to disable metrics_generator to generate metrics

### ISSUE THREAD

**Issue by ixiaoyi93** [grafana/tempo#4835]
I have generated serviceGraph and spanmetics metrics through opentelemetry collector. Grafana needs to open metrics_generator to use traces-drilldown, so I don't need to generate serviceGraph and spanmetics metrics again. The current configuration is as follows:
```
metrics_generator:
  metrics_ingestion_time_range_slack: 30s
  registry:
    collection_interval: 15s
    external_labels: {}
    stale_duration: 15m
  ring:
    kvstore:
      store: memberlist
  storage:
    path: /var/tempo/wal
    remote_write: []
    remote_write_add_org_id_header: true
    remote_write_flush_deadline: 1m
  traces_storage:
    path: /var/tempo/traces
  processor:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true
overrides:
  per_tenant_override_config: /runtime-config/overrides.yaml
  metrics_generator_processors: ['local-blocks']
```

How can I optimize the configuration of metrics_generator to reduce the generation of duplicate data?

**Comment by javiermolinar** [comment]
Hi, metrics generator processors are disabled by default. Unless you configure them in your per-tenant overrides, you should not see the sservice graph or span metrics generated by Tempo.

You can double-check by looking for these metrics:

`tempo_metrics_generator_processor_service_graphs_edges`
`tempo_metrics_generator_registry_active_series`

**Comment by IamGroot19** [comment]
Hello, in my case, I haven't configured the `span-metrics`  processor and yet, metrics are getting generator. 

Tempo Config
```
apiVersion: v1
data:
  tempo-query.yaml: |
    backend: 127.0.0.1:3100
  tempo.yaml: |2

    cache:
      caches:
      - memcached:
          consistent_hash: true
          host: 'tempo-memcached'
          service: memcached-client
          timeout: 500ms
        roles:
        - parquet-footer
        - bloom
        - frontend-search
    compactor:
      compaction:
        block_retention: 2160h
        compacted_block_retention: 1h
        compaction_cycle: 1m
        compaction_window: 30m
        max_block_bytes: 2147483648
        max_compaction_objects: 6000000
        max_time_per_tenant: 60m
        retention_concurrency: 10
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 1000
      ring:
        kvstore:
          store: memberlist
    distributor:
      extend_writes: true
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
              max_recv_msg_size_mib: 100000000
      ring:
        kvstore:
          store: memberlist
    ingester:
      complete_block_timeout: 1m
      flush_all_on_shutdown: true
      flush_check_period: 5s
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 3
        tokens_file_path: /var/tempo/tokens.json
        unregister_on_shutdown: true
      max_block_bytes: 104857600
      max_block_duration: 30m
      trace_idle_period: 5s
    memberlist:
      abort_if_cluster_join_fails: false
      bind_addr: []
      bind_port: 7946
      gossip_interval: 1s
      gossip_nodes: 2
      gossip_to_dead_nodes_time: 30s
      join_members:
      - dns+tempo-gossip-ring:7946
      leave_timeout: 5s
      left_ingesters_timeout: 5m
      max_join_backoff: 1m
      max_join_retries: 10
      min_join_backoff: 1s
      node_name: ""
      packet_dial_timeout: 5s
      packet_write_timeout: 5s
      pull_push_interval: 30s
      randomize_node_name: true
      rejoin_interval: 0s
      retransmit_factor: 2
      stream_timeout: 10s
    metrics_generator:
      metrics_ingestion_time_range_slack: 30s
      processor:
        service_graphs:
          dimensions: []
          histogram_buckets:
          - 0.1
          - 0.2
          - 0.4
          - 0.8
          - 1.6
          - 3.2
          - 6.4
          - 12.8
          max_items: 10000
          wait: 10s
          workers: 10
        span_metrics:
          dimensions: []
          histogram_buckets:
          - 0.002
          - 0.004
          - 0.008
          - 0.016
          - 0.032
          - 0.064
          - 0.128
          - 0.256
          - 0.512
          - 1.02
          - 2.05
          - 4.1
      registry:
        collection_interval: 15s
        external_labels: {}
        stale_duration: 15m
      ring:
        kvstore:
          store: memberlist
      storage:
        path: /var/tempo/wal
        remote_write:
        - url: <REDACTED>
        remote_write_add_org_id_header: true
        remote_write_flush_deadline: 1m
      traces_storage:
        path: /var/tempo/traces
    multitenancy_enabled: true
    overrides:
      per_tenant_override_config: /runtime-config/overrides.yaml
    querier:
      frontend_worker:
        frontend_address: tempo-query-frontend-discovery:9095
      max_concurrent_queries: 20
      search:
        external_backend: null
        external_endpoints: []
        external_hedge_requests_at: 8s
        external_hedge_requests_up_to: 2
        prefer_self: 10
        query_timeout: 30s
      trace_by_id:
        query_timeout: 10s
    query_frontend:
      max_outstanding_per_tenant: 2000
      max_retries: 2
      search:
        concurrent_jobs: 1000
        target_bytes_per_job: 104857600
      trace_by_id:
        query_shards: 50
    server:
      grpc_server_max_recv_msg_size: 100000000
      grpc_server_max_send_msg_size: 100000000
      http_listen_port: 3100
      http_server_read_timeout: 30s
      http_server_write_timeout: 30s
      log_format: logfmt
      log_level: info
    storage:
      trace:
        backend: gcs
        blocklist_poll: 30s
        gcs:
          bucket_name: <REDACTED> 
        local:
          path: /var/tempo/traces
        pool:
          max_workers: 400
          queue_depth: 20000
        wal:
          path: /var/tempo/wal
    usage_report:
      reporting_enabled: false
kind: ConfigMap
metadata:
  name: tempo-config
```

Tempo Runtime Config
```
apiVersion: v1
data:
  overrides.yaml: |
    overrides:
      "my_tenant":
        ingestion:
          burst_size_bytes: 629145600 # 600 MiB
          rate_limit_bytes: 524288000 # 500 MiB
          max_traces_per_user: 5000000 # 5 Million
        metrics_generator:
          processors:
            - service-graphs
            - local-blocks

      "*":
        ingestion:
          # 50 MB
          burst_size_bytes: 50000000
          # 500 MB
          rate_limit_bytes: 500000000
          # 100 MB
          max_traces_per_user: 100000
        metrics_generator:
          processors:
            - service-graphs
            - local-blocks
kind: ConfigMap
metadata:
  name: tempo-runtime
```

How am I identifying that metrics are incoming: The query `sum(traces_spanmetrics_calls_total)` is non-zero.

Not sure what mistake I am doing here, will appreciate some help. Thanks!
