### ISSUE TITLE
Some service graph metrics no generated

### ISSUE THREAD

**Issue by yangyulely** [grafana/tempo#4907]
**Describe the bug**

Hi, tempo team, We collect traces to tempo by opentelemetry collector, and enable metrices `metrics-generator`.
Traces are normal, but some service graph not. The `app_demo` is missing.
Could you have some suggestion about that? 
![Image](https://github.com/user-attachments/assets/a724b763-f249-4ea6-8996-21c2f36960fc)
And traces which service graph missing is:
```yml
{
    "batches": [
        {
            "resource": {
                "attributes": [
                    {
                        "key": "host.arch",
                        "value": {
                            "stringValue": "amd64"
                        }
                    },
                    {
                        "key": "host.name",
                        "value": {
                            "stringValue": "hostname"
                        }
                    },
                    {
                        "key": "os.description",
                        "value": {
                            "stringValue": "Linux 6.8.0-1021-aws"
                        }
                    },
                    {
                        "key": "os.type",
                        "value": {
                            "stringValue": "linux"
                        }
                    },
                    {
                        "key": "process.command_args",
                        "value": {
                            "stringValue": "[\"/home/otel/jdk/jdk-21.0.1/bin/java\",\"-javaagent:/home/otel/app_demo/agent/opentelemetry-javaagent.jar\",\"-Dotel.javaagent.configuration-file=/home/otel/app_demo/agent/app_demo.properties\",\"-jar\",\"lab-39-demo-2.2.2.RELEASE.jar\"]"
                        }
                    },
                    {
                        "key": "process.executable.path",
                        "value": {
                            "stringValue": "/home/otel/jdk/jdk-21.0.1/bin/java"
                        }
                    },
                    {
                        "key": "process.pid",
                        "value": {
                            "intValue": 259643
                        }
                    },
                    {
                        "key": "process.runtime.description",
                        "value": {
                            "stringValue": "Oracle Corporation OpenJDK 64-Bit Server VM 21.0.1+12-29"
                        }
                    },
                    {
                        "key": "process.runtime.name",
                        "value": {
                            "stringValue": "OpenJDK Runtime Environment"
                        }
                    },
                    {
                        "key": "process.runtime.version",
                        "value": {
                            "stringValue": "21.0.1+12-29"
                        }
                    },
                    {
                        "key": "telemetry.auto.version",
                        "value": {
                            "stringValue": "1.32.0"
                        }
                    },
                    {
                        "key": "telemetry.sdk.language",
                        "value": {
                            "stringValue": "java"
                        }
                    },
                    {
                        "key": "telemetry.sdk.name",
                        "value": {
                            "stringValue": "opentelemetry"
                        }
                    },
                    {
                        "key": "telemetry.sdk.version",
                        "value": {
                            "stringValue": "1.32.0"
                        }
                    },
                    {
                        "key": "service.name",
                        "value": {
                            "stringValue": "app_demo"
                        }
                    }
                ],
                "droppedAttributesCount": 0
            },
            "instrumentationLibrarySpans": [
                {
                    "spans": [
                        {
                            "traceId": "dad471dc545adc4f9bca27e1ff4f265c",
                            "spanId": "f2bee8f06ab4728c",
                            "parentSpanId": "c16ee228d871a378",
                            "traceState": "",
                            "name": "GET /demo/echo",
                            "kind": "SPAN_KIND_SERVER",
                            "startTimeUnixNano": 1742958333551513900,
                            "endTimeUnixNano": 1742958333552776000,
                            "attributes": [
                                {
                                    "key": "net.host.name",
                                    "value": {
                                        "stringValue": "127.0.0.1"
                                    }
                                },
                                {
                                    "key": "http.target",
                                    "value": {
                                        "stringValue": "/demo/echo"
                                    }
                                },
                                {
                                    "key": "http.request_content_length",
                                    "value": {
                                        "intValue": 14
                                    }
                                },
                                {
                                    "key": "net.sock.peer.addr",
                                    "value": {
                                        "stringValue": "127.0.0.1"
                                    }
                                },
                                {
                                    "key": "thread.name",
                                    "value": {
                                        "stringValue": "http-nio-8079-exec-9"
                                    }
                                },
                                {
                                    "key": "thread.id",
                                    "value": {
                                        "intValue": 46
                                    }
                                },
                                {
                                    "key": "net.sock.host.addr",
                                    "value": {
                                        "stringValue": "127.0.0.1"
                                    }
                                },
                                {
                                    "key": "net.sock.host.port",
                                    "value": {
                                        "intValue": 8079
                                    }
                                },
                                {
                                    "key": "net.sock.peer.port",
                                    "value": {
                                        "intValue": 46016
                                    }
                                },
                                {
                                    "key": "http.route",
                                    "value": {
                                        "stringValue": "/demo/echo"
                                    }
                                },
                                {
                                    "key": "net.protocol.name",
                                    "value": {
                                        "stringValue": "http"
                                    }
                                },
                                {
                                    "key": "net.host.port",
                                    "value": {
                                        "intValue": 8079
                                    }
                                },
                                {
                                    "key": "http.response_content_length",
                                    "value": {
                                        "intValue": 4
                                    }
                                },
                                {
                                    "key": "net.protocol.version",
                                    "value": {
                                        "stringValue": "1.1"
                                    }
                                },
                                {
                                    "key": "http.scheme",
                                    "value": {
                                        "stringValue": "http"
                                    }
                                },
                                {
                                    "key": "http.method",
                                    "value": {
                                        "stringValue": "GET"
                                    }
                                },
                                {
                                    "key": "http.status_code",
                                    "value": {
                                        "intValue": 200
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        }
                    ],
                    "instrumentationLibrary": {
                        "name": "io.opentelemetry.tomcat-7.0",
                        "version": "1.32.0-alpha"
                    }
                }
            ]
        },
        {
            "resource": {
                "attributes": [
                    {
                        "key": "host.arch",
                        "value": {
                            "stringValue": "amd64"
                        }
                    },
                    {
                        "key": "host.name",
                        "value": {
                            "stringValue": "host1"
                        }
                    },
                    {
                        "key": "os.description",
                        "value": {
                            "stringValue": "Linux 6.8.0-1021-aws"
                        }
                    },
                    {
                        "key": "os.type",
                        "value": {
                            "stringValue": "linux"
                        }
                    },
                    {
                        "key": "process.command_args",
                        "value": {
                            "stringValue": "[\"/home/otel/jdk/jdk-21.0.1/bin/java\",\"-javaagent:/home/otel/app_demo/agent/opentelemetry-javaagent.jar\",\"-Dotel.javaagent.configuration-file=/home/otel/app_demo/agent/app_demo.properties\",\"-jar\",\"lab-39-demo-2.2.2.RELEASE.jar\"]"
                        }
                    },
                    {
                        "key": "process.executable.path",
                        "value": {
                            "stringValue": "/home/otel/jdk/jdk-21.0.1/bin/java"
                        }
                    },
                    {
                        "key": "process.pid",
                        "value": {
                            "intValue": 259643
                        }
                    },
                    {
                        "key": "process.runtime.description",
                        "value": {
                            "stringValue": "Oracle Corporation OpenJDK 64-Bit Server VM 21.0.1+12-29"
                        }
                    },
                    {
                        "key": "process.runtime.name",
                        "value": {
                            "stringValue": "OpenJDK Runtime Environment"
                        }
                    },
                    {
                        "key": "process.runtime.version",
                        "value": {
                            "stringValue": "21.0.1+12-29"
                        }
                    },
                    {
                        "key": "telemetry.auto.version",
                        "value": {
                            "stringValue": "1.32.0"
                        }
                    },
                    {
                        "key": "telemetry.sdk.language",
                        "value": {
                            "stringValue": "java"
                        }
                    },
                    {
                        "key": "telemetry.sdk.name",
                        "value": {
                            "stringValue": "opentelemetry"
                        }
                    },
                    {
                        "key": "telemetry.sdk.version",
                        "value": {
                            "stringValue": "1.32.0"
                        }
                    },
                    {
                        "key": "service.name",
                        "value": {
                            "stringValue": "app_demo"
                        }
                    }
                ],
                "droppedAttributesCount": 0
            },
            "instrumentationLibrarySpans": [
                {
                    "spans": [
                        {
                            "traceId": "dad471dc545adc4f9bca27e1ff4f265c",
                            "spanId": "b79dd6cd86f0be06",
                            "parentSpanId": "f2bee8f06ab4728c",
                            "traceState": "",
                            "name": "DemoController.echo",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1742958333551931000,
                            "endTimeUnixNano": 1742958333552601000,
                            "attributes": [
                                {
                                    "key": "thread.id",
                                    "value": {
                                        "intValue": 46
                                    }
                                },
                                {
                                    "key": "thread.name",
                                    "value": {
                                        "stringValue": "http-nio-8079-exec-9"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        }
                    ],
                    "instrumentationLibrary": {
                        "name": "io.opentelemetry.spring-webmvc-3.1",
                        "version": "1.32.0-alpha"
                    }
                }
            ]
        },
        {
            "resource": {
                "attributes": [
                    {
                        "key": "host.arch",
                        "value": {
                            "stringValue": "amd64"
                        }
                    },
                    {
                        "key": "host.name",
                        "value": {
                            "stringValue": "host1"
                        }
                    },
                    {
                        "key": "os.description",
                        "value": {
                            "stringValue": "Linux 6.8.0-1021-aws"
                        }
                    },
                    {
                        "key": "os.type",
                        "value": {
                            "stringValue": "linux"
                        }
                    },
                    {
                        "key": "process.executable.path",
                        "value": {
                            "stringValue": "/home/otel/jdk/openjdk-8u402/jre/bin/java"
                        }
                    },
                    {
                        "key": "process.pid",
                        "value": {
                            "intValue": 738319
                        }
                    },
                    {
                        "key": "process.runtime.description",
                        "value": {
                            "stringValue": "OpenLogic-OpenJDK OpenJDK 64-Bit Server VM 25.402-b06"
                        }
                    },
                    {
                        "key": "process.runtime.name",
                        "value": {
                            "stringValue": "OpenJDK Runtime Environment"
                        }
                    },
                    {
                        "key": "process.runtime.version",
                        "value": {
                            "stringValue": "1.8.0_402-402-b06"
                        }
                    },
                    {
                        "key": "telemetry.auto.version",
                        "value": {
                            "stringValue": "1.32.0"
                        }
                    },
                    {
                        "key": "telemetry.sdk.language",
                        "value": {
                            "stringValue": "java"
                        }
                    },
                    {
                        "key": "telemetry.sdk.name",
                        "value": {
                            "stringValue": "opentelemetry"
                        }
                    },
                    {
                        "key": "telemetry.sdk.version",
                        "value": {
                            "stringValue": "1.32.0"
                        }
                    },
                    {
                        "key": "service.name",
                        "value": {
                            "stringValue": "async_osb_demo"
                        }
                    }
                ],
                "droppedAttributesCount": 0
            },
            "instrumentationLibrarySpans": [
                {
                    "spans": [
                        {
                            "traceId": "dad471dc545adc4f9bca27e1ff4f265c",
                            "spanId": "c16ee228d871a378",
                            "parentSpanId": "0000000000000000",
                            "traceState": "",
                            "name": "GET",
                            "kind": "SPAN_KIND_CLIENT",
                            "startTimeUnixNano": 1742958361793000000,
                            "endTimeUnixNano": 1742958361835911200,
                            "attributes": [
                                {
                                    "key": "net.peer.name",
                                    "value": {
                                        "stringValue": "127.0.0.1"
                                    }
                                },
                                {
                                    "key": "thread.id",
                                    "value": {
                                        "intValue": 259
                                    }
                                },
                                {
                                    "key": "http.request_content_length",
                                    "value": {
                                        "intValue": 14
                                    }
                                },
                                {
                                    "key": "net.protocol.name",
                                    "value": {
                                        "stringValue": "http"
                                    }
                                },
                                {
                                    "key": "thread.name",
                                    "value": {
                                        "stringValue": "Camel (camel-1) thread #85 - seda://Comment"
                                    }
                                },
                                {
                                    "key": "net.peer.port",
                                    "value": {
                                        "intValue": 8079
                                    }
                                },
                                {
                                    "key": "http.response_content_length",
                                    "value": {
                                        "intValue": 4
                                    }
                                },
                                {
                                    "key": "net.protocol.version",
                                    "value": {
                                        "stringValue": "1.1"
                                    }
                                },
                                {
                                    "key": "http.method",
                                    "value": {
                                        "stringValue": "GET"
                                    }
                                },
                                {
                                    "key": "http.url",
                                    "value": {
                                        "stringValue": "http://127.0.0.1:8079/demo/echo"
                                    }
                                },
                                {
                                    "key": "http.status_code",
                                    "value": {
                                        "intValue": 200
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        }
                    ],
                    "instrumentationLibrary": {
                        "name": "io.opentelemetry.jetty-httpclient-9.2",
                        "version": "1.32.0-alpha"
                    }
                }
            ]
        }
    ]
}
```

**To Reproduce**
1. Start Tempo (tempo, version 2.3.1)
2. Perform Operations (metrics-generator)

**Expected behavior**

All service graph generated
**Environment:**
 - Deployment tool: helm
We are using helm and deploy tempo-distributed

![Image](https://github.com/user-attachments/assets/6e4c0f07-89e0-4890-8ca3-6d888cf19e2b)

**Additional Context**
