### ISSUE TITLE
Inconsistent query results with identical parameters in Tempo (single instance)

### ISSUE THREAD

**Issue by CuteLeon** [grafana/tempo#4938]
**Describe the bug**
I am encountering an issue with Grafana Tempo where running the exact same query with identical parameters multiple times in quick succession yields completely different sets of results. This behavior is unexpected and makes it difficult to rely on query results for accurate analysis.

**To Reproduce**
I Deploied a Tempo on my Windows Server with below config, Query for multiple times in quick succession on Grafana Explore page.
``` yaml
server:  
  http_listen_port: 3200
  grpc_listen_port: 9096
  
distributor:  
  receivers:  
    otlp:  
      protocols:  
        grpc:  
          endpoint: 0.0.0.0:4322
  
ingester:  
  lifecycler:  
    ring:  
      kvstore:  
        store: inmemory
      replication_factor: 1  
  
compactor:  
  compaction:  
    block_retention: 48h
  
storage:  
  trace:  
    backend: local  
    wal:  
      path: D:\Telemetry\GrafanaLabs\tempo\storage\wal
    local:  
      path: D:\Telemetry\GrafanaLabs\tempo\storage\traces
  
overrides:  
  max_traces_per_user: 500000
```
Query Result  1:
<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/9389fc76-4ba3-4322-a19a-23b037d2b11f" />
Query Result  2:
<img width="1918" alt="Image" src="https://github.com/user-attachments/assets/8bca51d0-4dcf-4e45-8ac0-7a2df3eaa3e7" />
Query Result  3:
<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/48e4c4ca-7f36-4ac2-8ed4-72703e3e03ba" />
Query Result  4:
<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/8c718a5b-cc72-4def-9234-801054d92753" />

Youn can see that Tempo resturns totaly different results in short time, would you please help to help to resolve this issue?

**Expected behavior**
Identical queries should return consistent results when: No new data is being written, Time range and filters are unchanged

**Environment:**
 - Windows Server 2022 Standard
 - Tempo 2.6.1

**Additional Context**
I tried to update to Tempo 2.7.2 but issue still exists.
