### ISSUE TITLE
reportingEnabled report config parsing error on service initialization.

### ISSUE THREAD

**Issue by ocontant** [grafana/tempo#5000]
## Describe the bug
The documentation make a reference to a config parameter to put in the yaml config file to disable Usage Reporting to stat.grafana.com: 
[latest/configuration/#usage-report](https://grafana.com/docs/tempo/latest/configuration/#usage-report )
``` yaml
reportingEnabled: true
```

**But this config component cause a parsing config error:**
``` shell
docker-compose logs tempo
tempo  | failed parsing config: failed to parse configFile /etc/tempo.yaml: yaml: unmarshal errors:
tempo  |   line 5: field reportingEnabled not found in type app.Config
```

------------------

## To Reproduce
``` yaml
reportingEnabled: true
```

``` shell
docker-compose logs tempo
tempo  | failed parsing config: failed to parse configFile /etc/tempo.yaml: yaml: unmarshal errors:
tempo  |   line 5: field reportingEnabled not found in type app.Config
```

--------------------------

## Expected behavior
Would expect the config parsing to pass with success and the service to start with Usage Report telemetry disabled.

--------------------------

## Environment:
``` shell
Docker Compose version 2.33.0 on MacOSX - Docker Desktop

tempo  | tempo, version v2.7.2 (branch: main, revision: dab81069f)
tempo  |   build user:
tempo  |   build date:
tempo  |   go version:       go1.24.1
tempo  |   platform:         linux/arm64
tempo  |   tags:             unknown
```
-----------------------

## Additional Context
**Official documentation is misleading.**
_Assumed because Telemetry is enabled by default, which is unethical._  

The documentation make a reference to a config parameter to put in the yaml config file: 
[latest/configuration/#usage-report](https://grafana.com/docs/tempo/latest/configuration/#usage-report )
``` yaml
reportingEnabled: true
```

**But this config component cause a parsing config error:**
``` shell
docker-compose logs tempo
tempo  | failed parsing config: failed to parse configFile /etc/tempo.yaml: yaml: unmarshal errors:
tempo  |   line 5: field reportingEnabled not found in type app.Config
```

``` yaml - Configuration used
server:
  http_listen_port: 3200
  http_listen_address: 0.0.0.0

reportingEnabled: false

distributor:
  receivers:                            # this configuration will listen on all ports and protocols that tempo is capable of.
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m                # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

compactor:
  compaction:
    block_retention: 24h                # overall Tempo trace retention. set for demo purposes

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /var/lib/tempo/generator/wal
    remote_write:
      - url: http://mimir:9090/api/v1/push
        send_exemplars: true

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /var/lib/tempo/wal         # where to store the the wal locally
    local:
      path: /var/lib/tempo/blocks

overrides:
  metrics_generator_processors: [service-graphs, span-metrics] # enables metrics generator
```

Related code:
``` go [module.goL632(https://github.com/grafana/tempo/blob/35009dd73db6c2bbe1138f7cf44eb5ab7340a3f1/cmd/tempo/app/modules.go#L632)
func (t *App) initUsageReport() (services.Service, error) {
	if !t.cfg.UsageReport.Enabled {
		return nil, nil
	}

	t.cfg.UsageReport.Leader = false
	if t.isModuleActive(Ingester) {
		t.cfg.UsageReport.Leader = true
	}

	usagestats.Target(t.cfg.Target)

	var err error
	var reader backend.RawReader
	var writer backend.RawWriter

	switch t.cfg.StorageConfig.Trace.Backend {
	case backend.Local:
		reader, writer, _, err = local.New(t.cfg.StorageConfig.Trace.Local)
	case backend.GCS:
		reader, writer, _, err = gcs.New(t.cfg.StorageConfig.Trace.GCS)
	case backend.S3:
		reader, writer, _, err = s3.New(t.cfg.StorageConfig.Trace.S3)
	case backend.Azure:
		reader, writer, _, err = azure.New(t.cfg.StorageConfig.Trace.Azure)
	default:
		err = fmt.Errorf("unknown backend %s", t.cfg.StorageConfig.Trace.Backend)
	}

	if err != nil {
		return nil, fmt.Errorf("failed to initialize usage report: %w", err)
	}

	ur, err := usagestats.NewReporter(t.cfg.UsageReport, t.cfg.Ingester.LifecyclerConfig.RingConfig.KVStore, reader, writer, util_log.Logger, prometheus.DefaultRegisterer)
	if err != nil {
		level.Info(util_log.Logger).Log("msg", "failed to initialize usage report", "err", err)
		return nil, nil
	}
	t.usageReport = ur
	return ur, nil
}

```

``` go [main.go:L127](https://github.com/grafana/tempo/blob/35009dd73db6c2bbe1138f7cf44eb5ab7340a3f1/cmd/tempo/main.go#L127)

func configIsValid(config *app.Config) bool {
	// Warn the user for suspect configurations
	if warnings := config.CheckConfig(); len(warnings) != 0 {
		level.Warn(log.Logger).Log("msg", "-- CONFIGURATION WARNINGS --")
		for _, w := range warnings {
			output := []any{"msg", w.Message}
			if w.Explain != "" {
				output = append(output, "explain", w.Explain)
			}
			level.Warn(log.Logger).Log(output...)
		}
		return false
	}
	return true
}
```

``` go [config.go:L60](https://github.com/grafana/tempo/blob/35009dd73db6c2bbe1138f7cf44eb5ab7340a3f1/cmd/tempo/app/config.go#L60)
UsageReport           usagestats.Config              `yaml:"usage_report,omitempty"`
```

``` go [config.go:L143](https://github.com/grafana/tempo/blob/35009dd73db6c2bbe1138f7cf44eb5ab7340a3f1/cmd/tempo/app/config.go#L143)
c.UsageReport.RegisterFlagsAndApplyDefaults(util.PrefixConfig(prefix, "reporting"), f)
```

``` go [module.go:L864](https://github.com/grafana/tempo/blob/35009dd73db6c2bbe1138f7cf44eb5ab7340a3f1/cmd/tempo/app/modules.go#L864)
func usageStatsHandler(urCfg usagestats.Config) http.HandlerFunc {
	if !urCfg.Enabled {
		return func(w http.ResponseWriter, r *http.Request) {
			http.Error(w, "usage-stats is not enabled", http.StatusOK)
		}
	}

	// usage stats is Enabled, build and return usage stats json
	reportStr, err := jsoniter.MarshalToString(usagestats.BuildStats())
	if err != nil {
		return func(w http.ResponseWriter, r *http.Request) {
			http.Error(w, "error building usage report", http.StatusInternalServerError)
		}
	}

	return func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, reportStr)
	}
}
```

--------------------------

## Bug or By Design ?

I'm not sure, why the config parameter is causing a config parsing error. 
We could to some extent set the override to look like a config parameter to achieve the same result.
``` yaml
 usage_report: {Enable: false, Leader: false }
 ```
