### ISSUE TITLE
Why is the query range limited to 30m.

### ISSUE THREAD

**Issue by ixiaoyi93** [grafana/tempo#5120]
**Describe the bug**

I cannot view data after 30 minutes through Grafana Explore without setting any query conditions.

![Image](https://github.com/user-attachments/assets/2b68ea79-1cd0-4ed8-a384-8378a58a1f9a)

And I can see it by checking the traces in the last 30m.

![Image](https://github.com/user-attachments/assets/0bee9fb7-c8fc-4ddf-8f8a-b72091aa95f5)

**Expected behavior**

Ability to query the compressor for the maximum amount of time data set by the `block_retention` parameter.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**

Tempo configuration file `tempo.yaml`.

```yaml
stream_over_http_enabled: true
cache:
  caches:
  - memcached:
      consistent_hash: true
      host: 'tempo-memcached'
      service: memcached-client
      timeout: 500ms
    roles:
    - parquet-footer
    - bloom
    - frontend-search
compactor:
  compaction:
    block_retention: 672h
    compacted_block_retention: 2h
    compaction_cycle: 30s
    compaction_window: 2h
    max_block_bytes: 107374182400
    max_compaction_objects: 6000000
    max_time_per_tenant: 5m
    retention_concurrency: 10
    v2_in_buffer_bytes: 5242880
    v2_out_buffer_bytes: 20971520
    v2_prefetch_traces_count: 1000
  ring:
    kvstore:
      store: memberlist
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  ring:
    kvstore:
      store: memberlist
  log_discarded_spans:
    enabled: true
    include_all_attributes: false
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
    tokens_file_path: /var/tempo/tokens.json
  max_block_bytes: 107374182400
  max_block_duration: 5m
  trace_idle_period: 10s
  complete_block_timeout: 15m
  flush_all_on_shutdown: true
memberlist:
  abort_if_cluster_join_fails: false
  bind_addr: []
  bind_port: 7946
  cluster_label: 'tempo.grafana-stack'
  gossip_interval: 3s
  gossip_nodes: 2
  gossip_to_dead_nodes_time: 30s
  join_members:
  - dns+tempo-gossip-ring:7946
  leave_timeout: 5s
  left_ingesters_timeout: 5m
  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s
  node_name: ""
  packet_dial_timeout: 5s
  packet_write_timeout: 5s
  pull_push_interval: 30s
  randomize_node_name: true
  rejoin_interval: 0s
  retransmit_factor: 2
  stream_timeout: 10s
metrics_generator:
  metrics_ingestion_time_range_slack: 30s
  registry:
    collection_interval: 15s
    external_labels: {}
    stale_duration: 15m
  ring:
    kvstore:
      store: memberlist
  storage:
    path: /var/tempo/wal
    remote_write: []
    remote_write_add_org_id_header: true
    remote_write_flush_deadline: 1m
  traces_storage:
    path: /var/tempo/traces
  processor:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true
multitenancy_enabled: false
querier:
  frontend_worker:
    frontend_address: tempo-query-frontend-discovery:9095
  max_concurrent_queries: 80
  search:
    query_timeout: 30s
  trace_by_id:
    query_timeout: 20s
query_frontend:
  max_outstanding_per_tenant: 2000
  max_retries: 2
  metrics:
    concurrent_jobs: 1000
    duration_slo: 0s
    interval: 5m
    max_duration: 168h
    query_backend_after: 1440m
    target_bytes_per_job: 104857600
    throughput_bytes_slo: 0
  search:
    duration_slo: 5s
    max_duration: 168h
    concurrent_jobs: 1000
    query_backend_after: 180m
    query_ingesters_until: 360m
    target_bytes_per_job: 104857600
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    query_shards: 50
    duration_slo: 5s
server:
  grpc_server_max_recv_msg_size: 41943040
  grpc_server_max_send_msg_size: 41943040
  http_listen_port: 3100
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  log_format: logfmt
  log_level: debug
storage:
  trace:
    backend: s3
    blocklist_poll: 5m
    local:
      path: /var/tempo/traces
    pool:
      max_workers: 400
      queue_depth: 20000
    s3:
      access_key: xxxxxxxxxx
      bucket: xxxxxxxxxx
      endpoint: xxxxxxxxxx
      insecure: true
      secret_key: xxxxxxxxxx
    wal:
      path: /var/tempo/wal
usage_report:
  reporting_enabled: false
overrides:
  defaults:
    ingestion:
      rate_strategy: local
      burst_size_bytes: 50000000
      rate_limit_bytes: 30000000
    read:
      max_bytes_per_tag_values_query: 10000000
      max_blocks_per_tag_values_query: 0
      max_search_duration: 0s
    compaction:
      block_retention: 0s
      compaction_window: 0s
      compaction_disabled: false
    metrics_generator:
      processors: [service-graphs, span-metrics, 'local-blocks']
    global:
      max_bytes_per_trace: 50000000
  per_tenant_override_config: /runtime-config/overrides.yaml
  per_tenant_override_period: 10s
```

The log level has been adjusted to debug mode, and no obvious errors have been found in the various components of tempo.
