### ISSUE TITLE
Tempo fails to start due to missing GCP credentials file despite proper configuration

### ISSUE THREAD

**Issue by rgarcia89** [grafana/tempo#5304]
## Summary of bug

Tempo fails to start due to service account credential file not being found, despite proper IAM permissions being configured.

## Steps to reproduce

1. Configure service account with required permissions (`roles/storage.objectAdmin` and `storage.buckets.get`)
2. Set up Tempo with GCS storage backend using the Helm chart
3. Deploy using the configuration below

## Current Helm values configuration

```yaml
tempo:
  reportingEnabled: false
  retention: 24h

  storage:
    trace:
      backend: gcs
      gcs:
        bucket_name: tempo-staging

  extraEnvFrom:
  - secretRef:
      name: tempo-gcs-credentials

tempoQuery:
  enabled: true

serviceMonitor:
  enabled: true
```

## Current Secret File
```yaml
apiVersion: v1
data:
  GOOGLE_APPLICATION_CREDENTIALS: BASE64
kind: Secret
metadata:
  name: tempo-gcs-credentials
  namespace: tempo
type: Opaque
```

## What is the current *bug* behavior?

Tempo fails to start with the following error:

```
level=error ts=2025-06-18T14:00:28.463350175Z caller=main.go:121 msg="error running Tempo" err="failed to init module services: error initialising module: store: failed to create store: creating bucket: creating google http transport: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open {\n  \"type\": \"service_account\",\n  \"project_id\": \"placeholder-staging...}: no such file or directory"
```

The error indicates that the service account credentials file cannot be found, not that there's a permission issue with the service account itself.

## What is the expected *correct* behavior?

Tempo should be able to locate and use the service account credentials file to authenticate with GCP and access the storage bucket.

## Relevant logs and/or screenshots

```
ts=1750254869.9202733 level=info msg="Server starts serving" address=0.0.0.0:7777
level=info ts=2025-06-18T14:00:28.461359855Z caller=main.go:114 msg="Starting Tempo" version="(version=v2.8.0, branch=HEAD, revision=ab76780c6)" target=all
level=error ts=2025-06-18T14:00:28.463350175Z caller=main.go:121 msg="error running Tempo" err="failed to init module services: error initialising module: store: failed to create store: creating bucket: creating google http transport: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open {\n  \"type\": \"service_account\",\n  \"project_id\": \"placeholder-staging...}: no such file or directory"
```
