### ISSUE TITLE
Helm 0.6.0: extra's(EnvFrom) not picked up by template statefulset.yaml

### ISSUE THREAD

**Issue by mvink-guida** [grafana/tempo#541]
** howdy great work and inspiration, thank you, i think i found small issue hope you recognize it.

**Describe the bug**
Use s3 access / secret env keys to get access to s3 (e.g. in combination with kubeseal secrets deployments)
[documentation s3 envs for tempo](https://grafana.com/docs/tempo/latest/configuration/s3/#permissions)
I would like to use the extraEnvFrom but it is not defined in templates/statefulset.yaml

**To Reproduce**

```yaml
# secret
apiVersion: v1
kind: Secret
metadata:
  name: tempo-s3-keys
  namespace: tempo
data:
  access_key: eHl6Cg==
  secret_access_key: MTIzNDU2Nzg5MAo=
```

# part of values:

```yaml
values:
  # -- Environment variables from secrets or configmaps to add
  extraEnvFrom:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: tempo-s3-keys
        key: access_key
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: tempo-s3-keys
        key: secret_access_key
```

**Expected behavior**
s3 access by use of env key / values (works also with loki s3)

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm / tempo chart 0.6.0

**Additional Context**
Might check the other extra<options> in values.yaml if they are actually called for in the templates.
