### ISSUE TITLE
error polling blocklist, fails to list blocks on Dell ECS

### ISSUE THREAD

**Issue by kradalby** [grafana/tempo#558]
**Describe the bug**

I am playing around with Tempo for a proof of concept were I use ECS (from Dell) as my S3 compatible storage. 
Currently I am experiencing the same issue as described #408 were traces are not available after being flushed to object store, however, as per suggestion, I checked the `tempodb_blocklist_length`, which is at `0`. This was curious and I then realised that I see a lot of:

```logfmt
level=error ts=2021-02-26T11:29:12.002142062Z caller=tempodb.go:353 msg="error polling blocklist" tenantID=single-tenant err="error parsing uuid of obj, objectName: single-tenant/0023b193-abff-4127-b9e1-c5acd3936416/: invalid UUID length: 13"
```

every 5 minutes.

I queried the S3 storage to see how the layout was and the UUID exist and I think they are valid.

**To Reproduce**
1. Start Tempo 0.6.0 (revision=a8bf22014)
2. Wait for periodic check

**Expected behavior**

I expect tempo to be able to read back from the bucket after writing traces to blob storage.

**Environment:**
 - Infrastructure: Kubernetes + ECS for blob
 - Deployment tool: Helm 3

**Additional Context**

```logfmt
level=error ts=2021-02-26T11:24:11.316995438Z caller=tempodb.go:353 msg="error polling blocklist" tenantID=single-tenant err="error parsing uuid of obj, objectName: single-tenant/0023b193-abff-4127-b9e1-c5acd3936416/: invalid UUID length: 13"
level=info ts=2021-02-26T11:24:35.31391784Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2021-02-26T11:24:35.314041368Z caller=compactor.go:92 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2021-02-26T11:25:05.313898155Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2021-02-26T11:25:05.313959923Z caller=compactor.go:92 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2021-02-26T11:25:35.313851404Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2021-02-26T11:25:35.313903952Z caller=compactor.go:92 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2021-02-26T11:26:05.313877031Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2021-02-26T11:26:05.313939847Z caller=compactor.go:92 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2021-02-26T11:26:35.313842908Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2021-02-26T11:26:35.313909537Z caller=compactor.go:92 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2021-02-26T11:27:05.313825937Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2021-02-26T11:27:05.313882433Z caller=compactor.go:92 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2021-02-26T11:27:35.313898734Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2021-02-26T11:27:35.313955449Z caller=compactor.go:92 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2021-02-26T11:28:05.313829471Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2021-02-26T11:28:05.313901838Z caller=compactor.go:92 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2021-02-26T11:28:35.313849769Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2021-02-26T11:28:35.313908214Z caller=compactor.go:92 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=info ts=2021-02-26T11:29:05.314177869Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
level=info ts=2021-02-26T11:29:05.314287994Z caller=compactor.go:92 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
level=error ts=2021-02-26T11:29:12.002142062Z caller=tempodb.go:353 msg="error polling blocklist" tenantID=single-tenant err="error parsing uuid of obj, objectName: single-tenant/0023b193-abff-4127-b9e1-c5acd3936416/: invalid UUID length: 13"
level=info ts=2021-02-26T11:29:35.313898863Z caller=compactor.go:88 msg="starting compaction cycle" tenantID=single-tenant offset=0
```

**Comment by annanay25** [comment]
@kradalby  👋  

Could you please paste the `storage` section of your config? Along with the directory nesting of files in your object storage?

Coincidentally, `single-tenant` has 13 letters, and I think Tempo is looking for blocks and finding tenants at that level in the bucket. I suspect a small configuration error.

**Comment by kradalby** [comment]
Oh, that is quite embarresing, should learn to count:

```yaml
    storage:
      trace:
        backend: s3                        # backend configuration to use
        wal:
          path: /tmp/tempo/wal             # where to store the the wal locally
          # bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
          # index_downsample: 10             # number of traces per index record
        s3:
          bucket: tracing-staging                  # how to store data in s3
          endpoint: internal.example.com:9020
          # access_key: tempo
          # secret_key: supersecret
          insecure: true
          # For using AWS, select the appropriate regional endpoint and region
          # endpoint: s3.dualstack.us-west-2.amazonaws.com
          # region: us-west-2
        pool:
          max_workers: 100                 # the worker pool mainly drives querying, but is also used for polling the blocklist
          queue_depth: 10000```
```
Access and key comes from Minio env vars:

```yaml
    MINIO_ACCESS_KEY:
      value: ecs-tracing-staging
    MINIO_SECRET_KEY:
      value: <redacted>
```

I could not really see single-tenant anywhere in my configuration, so I must have assumed it was a internal.
