### ISSUE TITLE
Tempo thrift http

### ISSUE THREAD

**Issue by sergeyshaykhullin** [grafana/tempo#786]
**Describe the bug**
I am trying to migrate ingress-nginx opentracing from jaeger to tempo.

1. Jaeger endpoint http://jaeger-jaeger-operator-jaeger-collector.jaeger:14268/api/traces
![image](https://user-images.githubusercontent.com/46970457/122968622-6818ac00-d394-11eb-9f1f-84e184295a55.png)
2. Tempo endpoint http://tempo-distributor.tempo:14268/api/traces

Tempo is not collecting thrift http traces

**To Reproduce**
1. Install ingress-nginx
2. Enable opentracing and provide jaeger-endpoint
3. Install tempo and jaeger
4. Apply ingress and run some service/use default backend
5. Try to request and collect traces

**Expected behavior**
Tempo is collecting thrift http traces same as jaeger does

**Environment:**
 - Infrastructure: k3s
 - Deployment tool: helm

**Additional Context**

I am using tempo-distributed helm chart

```yaml

traces:
  otlp:
    grpc: true
  jaeger:
    thriftHttp: true

...

config: |
  ...
  distributor:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      jaeger:
        protocols:
          thrift_http:
            endpoint: 0.0.0.0:14268
  ...
```
![image](https://user-images.githubusercontent.com/46970457/122969467-597ec480-d395-11eb-87ad-04c4dc6a7dd2.png)

![image](https://user-images.githubusercontent.com/46970457/122969706-9e0a6000-d395-11eb-99e5-8fa1055ba501.png)
