### ISSUE TITLE
Dashboards for distributed deployments require undocumented config

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#802]
The [dashboards in tempo-mixin](https://github.com/grafana/tempo/tree/main/operations/tempo-mixin) use a cluster and job matcher: https://github.com/grafana/tempo/blob/29c6e25f5c0f9750b16fca673d437a490a6e3069/operations/tempo-mixin/dashboard-utils.libsonnet#L31-L32

This requires a cluster and job label to be present in the time series, which is not documented anywhere.

We should either:

- document what is expected to use this dashboard
- adapt the dashboard to not require this

Ideally, we also update the tk and helm examples to use these dashboards out of the box.

**Comment by kvrhdn** [comment]
fyi, adding an external label worked for me.

Using the Grafana Agent:
```yaml
prometheus:
  global:
    external_labels:
      cluster: k3d-local-dev
  # ...
```
