### ISSUE TITLE
Memory consumption post usage

### ISSUE THREAD

**Issue by ashwin32187** [grafana/tempo#852]
We ran a soak test on our application which sends traces to Tempo running on a separate VM as a podman container.
We found that the memory consumption on the tempo VM kept growing ever after the test finished, and remained in use for hours after test completion.

Is this expected behaviour?  Are there any tweaks to configuration or environment vars needed to release memory when not used?

1. Start Tempo 1.0.0
2. Start application sending traces to Tempo
3. Perform soak test at relatively low loads.

Expected behavior:
Memory to be released post usage.

Environment:
 - Infrastructure: AWS VMs running podman containers

![IMG_20210804_122946_235](https://user-images.githubusercontent.com/56748597/128136450-c58695e5-f72c-407c-80a2-d6f33aebc70f.jpg)

The test eneded at 00:00 hours where CPU usage comes down but memory consumption grows until 06:00 before coming down.

**Comment by kvrhdn** [comment]
The reason Tempo does not release memory is because the Go runtime is not eager to release memory. This is described in this blogpost: https://blog.detectify.com/2019/09/05/how-we-tracked-down-a-memory-leak-in-one-of-our-go-microservices/
Unless the OS needs more memory, the Go runtime will hold on to that memory "just in case".

Keep in mind that Tempo also has a lot of asynchronous jobs. Even when it's not ingesting trace data, the ingesters will flush blocks to the backend (the object store) and the compactor will be compressing these blocks. This might be why memory keeps increasing even after the test is done.

We haven't encountered any OOM errors recently (especially not when idle) and we sometimes have instances running for weeks.

Regarding tweaks: the are a number of configuration settings which impact how much memory Tempo needs and uses, but setting these requires a good overview of how Tempo works.
They are documented here: https://grafana.com/docs/tempo/latest/configuration/

**Comment by ashwin32187** [comment]
Thanks for the info Koenraad, noted regarding golangs memory management behaviour and will check out the config tweaks.

**Comment by ashwin32187** [comment]
Closing as this is expect memory management behaviour with golang.

**Comment by marcbachmann** [comment]
So isn't there anybody seeing OOM kills?
![image](https://user-images.githubusercontent.com/431376/150423624-d2330a13-b684-406d-b86e-04b77d543585.png)

I'm using that configuration:
```yaml
    auth_enabled: false
    search_enabled: false
    compactor:
      compaction:
        compacted_block_retention: 24h
        chunk_size_bytes: 5242880
        compaction_window: 1h
    distributor:
      receivers:
        zipkin:
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_binary:
              endpoint: 0.0.0.0:6832
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_http:
              endpoint: 0.0.0.0:14268
    ingester:
      trace_idle_period: 10s
      flush_check_period: 10s
      lifecycler:
        ring:
          replication_factor: 1
    server:
      http_listen_port: 3100
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
          encoding: snappy

    overrides:
      max_bytes_per_trace: 500000
```
