### ISSUE TITLE
Document how to deploy Tempo to ingest traces from multiple clusters

### ISSUE THREAD

**Issue by yvrhdn** [grafana/tempo#977]
It's possible to ingest traces from multiple clusters into a single big Tempo instance. I believe this is a fairly common deployment setup, so we should try to describe this in our docs.

We should describe:
- how to setup ingress (set up a load balancer, add a gateway for authentication and routing)
- how to collect traces in each cluster and forward them to Tempo (i.e. set up a bunch of Grafana Agents with a service in front, remote write to Tempo)

Also good to mention: load balancing GRPC streams has some tricky behaviour, see https://grpc.io/blog/grpc-load-balancing/

Question about this setup in the community slack: https://grafana.slack.com/archives/C01D981PEE5/p1632219533109300

**Comment by BitProcessor** [comment]
I'm using the following:
```
  chart:
    repository: https://grafana.github.io/helm-charts
    name: tempo-distributed
    version: 0.9.14
```
and I added an Ingress object like this:
```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: prod-tempo
  name: tempo
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: GRPC    
spec:
  tls:
  - hosts:
    - otlp-grpc.tempo.internal.<hidden>.io
    secretName: le-prod-tempo
  rules:
  - host: otlp-grpc.tempo.internal.<hidden>.io
    http:
      paths:
      - path: /
        backend:
          serviceName: tempo-tempo-distributed-distributor
          servicePort: 4317
```

Seems to be working just fine for now.
This uses the opensource nginx-ingress in the back + AWS Classic ELB (private subnet shared between multiple clusters)
